<?php

/**
 * @file
 * Ubercart Taxes module.
 *
 * Allows tax rules to be set up and applied to orders.
 */

/******************************************************************************
 * Drupal Hooks                                                               *
 ******************************************************************************/

/**
 * Implements hook_permission().
 */
function uc_taxes_permission() {
  return array(
    'configure taxes' => array(
      'title' => t('Configure taxes'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function uc_taxes_menu() {
  $items = array();

  $items['admin/store/settings/taxes'] = array(
    'title' => 'Taxes',
    'description' => 'Configure tax rates and rules.',
    'page callback' => 'uc_taxes_admin_settings',
    'access arguments' => array('configure taxes'),
    'file' => 'uc_taxes.admin.inc',
  );
  $items['admin/store/settings/taxes/add'] = array(
    'title' => 'Add a tax rate',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_taxes_form'),
    'access arguments' => array('configure taxes'),
    'file' => 'uc_taxes.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/store/settings/taxes/%/edit'] = array(
    'title' => 'Edit a tax rate',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_taxes_form', 4),
    'access arguments' => array('configure taxes'),
    'file' => 'uc_taxes.admin.inc',
  );
  $items['admin/store/settings/taxes/%/clone'] = array(
    'page callback' => 'uc_taxes_clone',
    'page arguments' => array(4),
    'access arguments' => array('configure taxes'),
    'file' => 'uc_taxes.admin.inc',
  );
  $items['admin/store/settings/taxes/%/delete'] = array(
    'title' => 'Delete tax rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_taxes_delete_form', 4),
    'access arguments' => array('configure taxes'),
    'file' => 'uc_taxes.admin.inc',
  );

  $items += rules_ui()->config_menu('admin/store/settings/taxes');

  return $items;
}

/**
 * Implements hook_module_implements_alter().
 *
 * Ensures that all other line items are added to the order before tax
 * calculations are made.
 */
function uc_taxes_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'uc_order') {
    $group = $implementations['uc_taxes'];
    unset($implementations['uc_taxes']);
    $implementations['uc_taxes'] = $group;
  }
}

/**
 * Implements hook_form_uc_order_edit_form_alter().
 */
function uc_taxes_form_uc_order_edit_form_alter(&$form, &$form_state) {
  $order = $form['#order'];
  $line_items = $order->line_items;

  foreach ($line_items as $item) {
    // Tax line items are stored in the database, but they can't be changed by
    // the user.
    if ($item['type'] == 'tax') {
      $form['line_items'][$item['line_item_id']]['title'] = array(
        '#markup' => check_plain($item['title']),
      );
      $form['line_items'][$item['line_item_id']]['amount'] = array(
        '#theme' => 'uc_price',
        '#price' => $item['amount'],
      );
    }
  }
}

/**
 * Implements hook_uc_cart_item().
 *
 * Adds included taxes (VAT) to display price of applicable products.
 */
function uc_taxes_uc_cart_item($op, $item) {
  if ($op == 'load') {
    $product = node_load($item->nid);

    list($amount, $suffixes) = uc_taxes_get_included_tax($product, $item->price);

    $item->display_price += $amount;
    if (!empty($suffixes)) {
      $item->display_price_suffix .= implode(' ', $suffixes);
    }
  }
}

/**
 * Implements hook_node_load().
 *
 * Adds included taxes (VAT) to display price of applicable products.
 */
function uc_taxes_node_load($nodes, $types) {
  foreach ($nodes as &$node) {
    if (uc_product_is_product($node)) {
      $amount = 0;
      $suffixes = array();
      if ($node->type == 'product_kit') {
        // For product kits, the total tax is the sum of the tax on the discounted
        // prices of component products.
        foreach ($node->products as $pid => &$product) {
          $discount =  ($node->mutable != UC_PRODUCT_KIT_MUTABLE) ? $product->discount : 0;
          list($this_amount, $these_suffixes) = uc_taxes_get_included_tax($product, $product->sell_price + $discount);
          $amount += $this_amount * $product->qty;
          $suffixes += $these_suffixes;
        }
      }
      else {
        list($amount, $suffixes) = uc_taxes_get_included_tax($node);
      }
      $node->display_price += $amount;
      if (!empty($suffixes)) {
        $node->display_price_suffix .= implode(' ', $suffixes);
      }
    }
  }
}

/*******************************************************************************
 * Ubercart Hooks
 ******************************************************************************/

/**
 * Implements hook_uc_line_item().
 */
function uc_taxes_uc_line_item() {
  $items['tax'] = array(
    'title' => t('Tax'),
    'callback' => 'uc_line_item_tax',
    'weight' => 9,
    'stored' => TRUE,
    'default' => FALSE,
    'calculated' => TRUE,
    'display_only' => FALSE,
  );
  $items['tax_display'] = array(
    'title' => t('Tax'),
    'callback' => 'uc_line_item_tax_display',
    'weight' => 5,
    'stored' => FALSE,
    'calculated' => TRUE,
    'display_only' => TRUE,
  );
  $items['tax_subtotal'] = array(
    'title' => t('Subtotal excluding taxes'),
    'callback' => 'uc_line_item_tax_subtotal',
    'weight' => 7,
    'stored' => FALSE,
    'calculated' => FALSE,
    'display_only' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_uc_order().
 *
 * Updates and saves tax line items to the order.
 */
function uc_taxes_uc_order($op, $order, $arg2) {
  switch ($op) {
    case 'save':
      $changes = array();
      $callback = _uc_line_item_data('tax', 'callback');
      $line_items = $callback('load', $order);
      if (is_array($order->line_items)) {
        foreach ($order->line_items as $i => $line) {
          if ($line['type'] == 'tax') {
            $delete = TRUE;
            foreach ($line_items as $id => $new_line) {
              if ($new_line['data']['tax_id'] == $line['data']['tax_id']) {
                if ($new_line['amount'] != $line['amount']) {
                  uc_order_update_line_item($line['line_item_id'], $new_line['title'], $new_line['amount'], $new_line['data']);
                  $order->line_items[$i]['amount'] = $new_line['amount'];
                  $changes[] = t('Changed %title to %amount.', array('%amount' => uc_currency_format($new_line['amount']), '%title' => $new_line['title']));
                }
                unset($line_items[$id]);
                $delete = FALSE;
                break;
              }
            }
            if ($delete) {
              uc_order_delete_line_item($line['line_item_id']);
              unset($order->line_items[$i]);
              $changes[] = t('Removed %title.', array('%title' => $line['title']));
            }
          }
        }
      }
      if (is_array($line_items)) {
        foreach ($line_items as $line) {
          uc_order_line_item_add($order->order_id, $line['id'], $line['title'], $line['amount'], $line['weight'], $line['data']);
          $line['type'] = 'tax';
          $order->line_items[] = $line;
          $changes[] = t('Added %amount for %title.', array('%amount' => uc_currency_format($line['amount']), '%title' => $line['title']));
        }
      }
      if (count($changes)) {
        uc_order_log_changes($order->order_id, $changes);
      }
    break;
  }
}

/******************************************************************************
 * Menu Callbacks                                                             *
 ******************************************************************************/

/**
 * Handles the tax line item.
 */
function uc_line_item_tax($op, $order) {
  switch ($op) {
    case 'load':
      $lines = array();
      $taxes = uc_taxes_calculate($order);
      foreach ($taxes as $tax) {
        $lines[] = array(
          'id' => ($tax->summed ? 'tax' : 'tax_included'),
          'title' => $tax->name,
          'amount' => $tax->amount,
          'weight' => variable_get('uc_li_tax_weight', 9) + $tax->weight / 10,
          'data' => $tax->data,
        );
      }
      return $lines;
  }
}

function uc_line_item_tax_display($op, $order) {
  switch ($op) {
    case 'display':
      $lines = array();
      $taxes = uc_taxes_calculate($order);
      foreach ($taxes as $tax) {
        foreach ($order->line_items as $line_item) {
          if ($line_item['type'] == 'tax' && $line_item['data']['tax_id'] == $tax->id) {
            continue 2;
          }
        }

        $lines[] = array(
          'id' => ($tax->summed ? 'tax' : 'tax_included'),
          'title' => $tax->name,
          'amount' => $tax->amount,
          'weight' => variable_get('uc_li_tax_weight', 9) + $tax->weight / 10,
          'data' => $tax->data,
        );
      }
      return $lines;
  }
}

/**
 * Handles the line item subtotal before taxes.
 */
function uc_line_item_tax_subtotal($op, $order) {
  $amount = 0;
  switch ($op) {
    case 'display':
      $has_taxes = FALSE;
      $different = FALSE;

      if (is_array($order->products)) {
        foreach ($order->products as $item) {
          $amount += $item->price * $item->qty;
        }
      }
      if (is_array($order->line_items)) {
        foreach ($order->line_items as $key => $line_item) {
          if ($line_item['type'] == 'subtotal') {
            continue;
          }
          if (substr($line_item['type'], 0, 3) != 'tax') {
            $amount += $line_item['amount'];
            $different = TRUE;
          }
          else {
            $has_taxes = TRUE;
          }
        }
      }

      if (isset($order->taxes) && is_array($order->taxes) && count($order->taxes)) {
        $has_taxes = TRUE;
      }

      if ($different && $has_taxes) {
        return array(array(
          'id' => 'tax_subtotal',
          'title' => t('Subtotal excluding taxes'),
          'amount' => $amount,
          'weight' => variable_get('uc_li_tax_subtotal_weight', 7),
        ));
      }
      break;
  }
}


/******************************************************************************
 * Module and Helper Functions
 ******************************************************************************/

/**
 * Saves a tax rate to the database.
 *
 * @param $rate
 *   The tax rate object to be saved.
 *
 * @return
 *   The saved tax rate object including the rate ID for new rates.
 */
function uc_taxes_rate_save($rate) {
  // Save it as a new rate if no ID is specified.
  if (!$rate->id) {
    drupal_write_record('uc_taxes', $rate);
  }
  // Otherwise update the existing tax rate's data.
  else {
    drupal_write_record('uc_taxes', $rate, array('id'));
  }

  db_delete('uc_taxed_product_types')
    ->condition('tax_id', $rate->id)
    ->execute();
  db_delete('uc_taxed_line_items')
    ->condition('tax_id', $rate->id)
    ->execute();

  $p_insert = db_insert('uc_taxed_product_types')->fields(array('tax_id', 'type'));
  $l_insert = db_insert('uc_taxed_line_items')->fields(array('tax_id', 'type'));

  foreach ($rate->taxed_product_types as $type) {
    $p_insert->values(array(
      'tax_id' => $rate->id,
      'type' => $type,
    ));
  }

  foreach ($rate->taxed_line_items as $type) {
    $l_insert->values(array(
      'tax_id' => $rate->id,
      'type' => $type,
    ));
  }

  $p_insert->execute();
  $l_insert->execute();

  rules_clear_cache();

  return $rate;
}

/**
 * Loads a tax rate or all tax rates from the database.
 *
 * @param $rate_id
 *   The ID of the specific rate to load or NULL to return all available rates.
 *
 * @return
 *   An object representing the requested tax rate or an array of all tax rates
 *   keyed by rate ID.
 */
function uc_taxes_rate_load($rate_id = NULL) {
  static $rates = array();

  // If the rates have not been cached yet...
  if (empty($rates)) {
    // Get all the rate data from the database.
    $result = db_query("SELECT * FROM {uc_taxes} ORDER BY weight");

    // Loop through each returned row.
    foreach ($result as $rate) {
      $rate->taxed_product_types = array();
      $rate->taxed_line_items = array();

      $rates[$rate->id] = $rate;
    }

    foreach (array('taxed_product_types', 'taxed_line_items') as $field) {
      $result = db_select('uc_' . $field, 't')->fields('t', array('tax_id', 'type'))->execute();
      foreach ($result as $record) {
        $rates[$record->tax_id]->{$field}[] = $record->type;
      }
    }
  }

  // Return a rate as specified.
  if ($rate_id) {
    return $rates[$rate_id];
  }
  // Or return the whole shebang.
  else {
    return $rates;
  }
}

/**
 * Deletes a tax rate from the database.
 *
 * @param $rate_id
 *   The ID of the tax rate to delete.
 */
function uc_taxes_rate_delete($rate_id) {
  // Delete the tax rate record.
  db_delete('uc_taxes')
    ->condition('id', $rate_id)
    ->execute();

  db_delete('uc_taxed_product_types')
    ->condition('tax_id', $rate_id)
    ->execute();

  db_delete('uc_taxed_line_items')
    ->condition('tax_id', $rate_id)
    ->execute();

  // Delete the associated conditions if they have been saved to the database.
  rules_config_delete(array('uc_taxes_' . $rate_id));
}

/**
 * Calculates the taxes for an order based on enabled tax modules.
 *
 * @param $order
 *   The full order object for the order want to calculate taxes for.
 *
 * @return
 *   An array of taxes for the order.
 */
function uc_taxes_calculate($order) {
  // Find any taxes specified by enabled modules.
  $taxes = module_invoke_all('uc_calculate_tax', $order);

  return $taxes;
}

/**
 * Calculates the amount and types of taxes that apply to an order.
 */
function uc_taxes_uc_calculate_tax($order) {
  if (!is_object($order)) {
    return array();
  }
  if (empty($order->delivery_postal_code)) {
    $order->delivery_postal_code = $order->billing_postal_code;
  }
  if (empty($order->delivery_zone)) {
    $order->delivery_zone = $order->billing_zone;
  }
  if (empty($order->delivery_country)) {
    $order->delivery_country = $order->billing_country;
  }

  $order->taxes = array();

  if (isset($order->order_status)) {
    $state = uc_order_status_data($order->order_status, 'state');
    $use_same_rates = in_array($state, array('payment_received', 'completed'));
  }
  else {
    $use_same_rates = FALSE;
  }

  foreach (uc_taxes_rate_load() as $tax_rate) {
    $tax = clone ($tax_rate);
    if ($use_same_rates) {
      foreach ((array)$order->line_items as $old_line) {
        if ($old_line['type'] == 'tax' && $old_line['data']['tax_id'] == $tax->id) {
          $tax->rate = $old_line['data']['tax_rate'];
          break;
        }
      }
    }

    if (rules_invoke_component('uc_taxes_' . $tax->id, $order)) {
      $line_item = uc_taxes_apply_tax($order, $tax);
      if ($line_item) {
        $order->taxes[$line_item->id] = $line_item;
      }
    }
  }

  return $order->taxes;
}


/**
 * Calculates tax for a single product.
 */
function uc_taxes_apply_item_tax($item, $tax) {
  $node = node_load($item->nid);

  // Special handling for manually added "Blank line" products.
  if (!$node) {
    $node = new stdClass();
    $node->type = 'blank-line';
    $node->shippable = $item->weight > 0;
  }

  // Tax products if they are of a taxed type and if it is shippable if
  // the tax only applies to shippable products.
  if (in_array($node->type, $tax->taxed_product_types) && ($tax->shippable == 0 || $node->shippable == 1)) {
    return $item->price * $item->qty;
  }
}

/**
 * Applies taxes to an order.
 *
 * @param $order
 *   The order object being considered.
 * @param $tax
 *   The tax rule calculating the amount.
 *
 * @return
 *   The line item array representing the amount of tax.
 */
function uc_taxes_apply_tax($order, $tax) {
  $amount = 0;
  $taxable_amount = 0;
  if (is_array($order->products)) {
    foreach ($order->products as $item) {
      $taxable_amount += uc_taxes_apply_item_tax($item, $tax);
    }
  }
  $taxed_line_items = $tax->taxed_line_items;
  if (is_array($order->line_items) && is_array($taxed_line_items)) {
    foreach ($order->line_items as $key => $line_item) {
      if ($line_item['type'] == 'tax') {
        // Don't tax old taxes.
        continue;
      }
      if (in_array($line_item['type'], $taxed_line_items)) {
        $callback = _uc_line_item_data($line_item['type'], 'tax_adjustment');
        if (isset($callback) && function_exists($callback)) {
          $taxable_amount += $callback($line_item['amount'], $order, $tax);
        }
        else {
          $taxable_amount += $line_item['amount'];
        }
      }
    }
  }
  if (in_array('tax', $taxed_line_items)) {
    // Tax taxes that were just calculated.
    foreach ($order->taxes as $other_tax) {
      $taxable_amount += $other_tax->amount;
    }
  }
  $amount = $taxable_amount * $tax->rate;
  if ($amount) {
    $line_item = (object)array(
      'id' => $tax->id,
      'name' => $tax->name,
      'amount' => $amount,
      'weight' => $tax->weight,
      'summed' => 1,
    );
    $line_item->data = array(
      'tax_id' => $tax->id,
      'tax_rate' => $tax->rate,
      'taxable_amount' => $taxable_amount,
      'tax_jurisdiction' => $tax->name,
    );
    return $line_item;
  }
}

/**
 * Calculates the taxes that should be included in the display price of a product.
 * @param $product
 *   The product whose included taxes are to be calculated.
 * @param $price
 *   If specified, use this value as the tax-base.  Otherwise use the product sell price.
 */
function uc_taxes_get_included_tax($product, $price = FALSE) {
  $amount = 0;
  $suffixes = array();
  $price = ($price === FALSE) ? $product->sell_price : $price;
  foreach (uc_taxes_rate_load() as $tax) {
    if ($tax->display_include && in_array($product->type, $tax->taxed_product_types) && ($tax->shippable == 0 || $product->shippable == 1)) {
      $amount += $price * $tax->rate;
      $suffixes[$tax->inclusion_text] = $tax->inclusion_text;
    }
  }
  return array($amount, $suffixes);
}
