<?php
// $Id$

/**
 * @file
 * The product module for the bercart.
 * 
 * Provides information that is common to all products, and user-defined product
 * classes for more specification. Recommends the image and taxonomy modules.
 * 
 * Coded by: Lyle Mantooth
 */

/******************************************************************************
 * Drupal Hooks                                                               *
 ******************************************************************************/

/**
 * Implementation of hook_menu().
 */
function uc_product_menu($may_cache){
  $items = array();

  if ($may_cache){
    $items[] = array('path' => 'products',
      'title' => t('Products'),
      'access' => user_access('access content'),
      'callback' => 'uc_product_default',
      'type' => MENU_NORMAL_ITEM,
    );
    $items[] = array('path' => 'node/add/product',
      'title' => t('Product'),
      'access' => user_access('administer products'),
    );
    $items[] = array('path' => 'admin/store/products',
      'title' => t('Products'),
      'description' => t('Administer product attributes, classes, and general settings.'),
      'access' => user_access('administer products'),
      'callback' => 'uc_product_overview',
      'type' => MENU_NORMAL_ITEM,
    );
    $items[] = array(
      'path' => 'admin/store/products/view',
      'title' => t('View products'),
      'callback' => 'uc_product_administration',
      'access' => user_access('administer products'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => -12,
    );
    $items[] = array('path' => 'admin/store/products/create_product',
      'title' => t('Create product'),
      'access' => user_access('administer products'),
      'callback' => 'node_add',
      'callback arguments' => array('product'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => -10,
    );
    $items[] = array('path' => 'admin/store/products/classes',
      'title' => t('Manage classes'),
      'access' => user_access('administer product classes'),
      'callback' => 'uc_product_class_default',
      'type' => MENU_NORMAL_ITEM,
      'weight' => -2,
    );
    $items[] = array('path' => 'admin/store/settings/products',
      'title' => t('Product settings'),
      'access' => user_access('administer products'),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'uc_product_settings',
      'type' => MENU_NORMAL_ITEM,
    );
  }
  else {
    $items[] = array('path' => 'admin/store/settings/products/defaults/'. arg(5),
      'title' => t('Imagecache default settings'),
      'access' => user_access('administer products'),
      'callback' => 'uc_product_image_defaults',
      'callback arguments' => array(arg(5)),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4),
      'title' => t('Product class'),
      'access' => user_access('administer product classes'),
      'callback' => 'uc_product_class_view',
      'callback arguments' => array(arg(4)),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/edit',
      'title' => t('Edit class'),
      'access' => user_access('administer product classes'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('uc_product_class_form', arg(4)),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/delete',
      'access' => user_access('administer product classes'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('uc_product_class_delete_confirm', arg(4)),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/fields',
      'title' => t('fields'),
      'weight' => 0,
      'type' => MENU_DEFAULT_LOCAL_TASK
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/fields/add',
      'title' => t('Add field'),
      'access' => user_access('administer product classes'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('uc_product_class_field_form', arg(4), null),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/fields/'. arg(6) .'/edit',
      'title' => t('Edit field'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('uc_product_class_field_form', arg(4), arg(6)),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/fields/'. arg(6) .'/delete',
      'title' => t('Delete field'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('uc_product_class_field_delete_confirm', arg(4), arg(6)),
      'type' => MENU_CALLBACK_ITEM,
    );
    
    // This item is meant to be an internal link only. It is called from uc_product_form().
    // Do not point other links here.
    $items[] = array('path' => 'admin/store/products/classes/'. arg(4) .'/render',
      'access' => user_access('administer products'),
      'callback' => '_uc_product_class_fields_render',
      'callback arguments' => array(arg(4)),
      'type' => MENU_CALLBACK_ITEM,
    );
    $items[] = array('path' => 'products/field_image_cache/'. arg(2),
      'access' => true,
      'callback' => '_uc_product_get_image_field_filepath',
      'callback arguments' => array(arg(2)),
      'type' => MENU_CALLBACK_ITEM,
    );
    drupal_add_css(drupal_get_path('module', 'uc_product') .'/uc_product.css');
  }
  
  return $items;
}

/**
 * Implementation of hook_help().
 */
function uc_product_help($section = ''){
  // Do things here later. Figure out what you need to say for each section.
  switch($section){
    case 'admin/settings/module#description':
      $output = t('A module to represent items in an online store.');
      break;
  }
  return $output;
}

/**
 * Implementation of hook_perm().
 */
function uc_product_perm(){
  return array('administer products', 'administer product classes');
}

/**
 * Implementation of hook_access().
 */
function uc_product_access($op, $node){
  global $user;
  
  if ($op == 'create' || $op == 'update' || $op == 'delete'){
    return user_access('administer products');
  }
}

/**
 * Implementation of hook_node_info().
 */
function uc_product_node_info(){
  return array(
    'product' => array(
      'name' => t('Product'),
      'module' => 'uc_product', 
      'description' => t('This node displays the representation of a product for sale on the website. It includes 
        all the unique information that can be attributed to a specific model number.'),
      'title_label' => t('Name'),
      'body_label' => t('Description'),
    )
  );
}

function uc_product_forms(){
  $products = db_query("SELECT nid FROM {uc_products}");

  while ($prodrow = db_fetch_object($products))
  {
    $forms['uc_product_add_to_cart_form_'. $prodrow->nid] = array('callback' => 'uc_product_add_to_cart_form');
  }

  return $forms;
}

/**
 * Implementation of hook_form().
 */
function uc_product_form(&$node){
  // JQuery alters the form based on the product class chosen.
  drupal_add_js('$(document).ready(function(){
    if ($("#edit-class_select").val() > 0)
      mod_class_fields($("#edit-class_select").val(), 0);
  });

  function mod_class_fields(class_id) {
    var oldVal = $("#edit-class_fields").val();
    var cfields;
    
    if (class_id == "-1"){
      $("#edit-class_fields").hide()
    }
    else{
      $("#edit-class_fields").hide().empty().load("'. base_path() .'?q=admin/store/products/classes/" + class_id + "/render/'. $node->nid .'", function(){
        $(this).show()
      })
    }
  }', 'inline');
  
  $form['title'] = array('#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
    '#weight' => -5,
    '#default_value' => $node->title,
    '#description' => t('Name of the product.')
  );
  
  $form['body_filter']['body'] = array('#type' => 'textarea',
    '#title' => t('Description'),
    '#required' => FALSE,
    '#default_value' => $node->body,
    '#description' => t('Explain this whatchamacallit.'),
  );
  $form['body_filter']['format'] = filter_form($node->format);
  $form['body_filter']['#weight'] = -4;

  $form['base'] = array('#type' => 'fieldset',
    '#title' => t('Product Information'),
    '#collapsible' => true,
    '#collapsed' => false,
    '#weight' => -2,
    '#attributes' => array('class' => 'product-field'),
  );
  $form['base']['model'] = array('#type' => 'textfield',
    '#title' => t('SKU'),
    '#required' => TRUE,
    '#default_value' => $node->model,
    '#description' => t('Product SKU/model'),
    '#weight' => 1,
    '#size' => 32,
    '#maxlength' => 32,
  );
  
  $form['base']['prices'] = array('#weight' => 2,
    '#theme' => 'uc_product_form_prices',
  );
  
  $form['base']['prices']['list_price'] = array('#type' => 'textfield',
    '#title' => t('List Price'),
    '#required' => FALSE,
    '#default_value' => $node->list_price,
    '#description' => t('How much no one pays.'),
    '#weight' => 0,
    '#size' => 20,
    '#maxlength' => 35,
  );
  $form['base']['prices']['cost'] = array('#type' => 'textfield',
    '#title' => t('Cost'),
    '#required' => FALSE,
    '#default_value' => $node->cost,
    '#description' => t('How much we pay.'),
    '#weight' => 1,
    '#size' => 20,
    '#maxlength' => 35,
  );
  $form['base']['prices']['sell_price'] = array('#type' => 'textfield',
    '#title' => t('Sell Price'),
    '#required' => TRUE,
    '#default_value' => $node->sell_price,
    '#description' => t('How much our customers pay.'),
    '#weight' => 2,
    '#size' => 20,
    '#maxlength' => 35,
  );
  $units = array('LBS' => t('Pounds'),
    'KGS' => t('Kilograms'),
    'OZS' => t('Ounces'),
    'GRM' => t('Grams'),
  );
  $form['base']['units'] = array('#type' => 'select',
    '#title' => t('Unit of measurement'),
    '#default_value' => $node->units ? $node->units : variable_get('uc_weight_unit', 'LBS'),
    '#options' => $units,
    '#weight' => 3,
  );

  $form['base']['weight'] = array('#type' => 'textfield',
    '#title' => t('Weight'),
    '#default_value' => $node->weight,
    '#description' => t('How heavy it is.'),
    '#weight' => 4,
    '#size' => 10,
    '#maxlength' => 15,
  );

  $result = db_query("SELECT * FROM {uc_product_classes}");
  if (db_num_rows($result)){
    $classes = array(t('--Select product class--'));
    while ($c = db_fetch_object($result)){
      $classes[$c->pcid] = $c->name;
    }
    
    $form['c_fields'] = array('#type' => 'fieldset',
      '#title' => t('Class Fields'),
      '#collapsible' => true,
      '#collapsed' => false,
      '#weight' => -1,
    );
    $form['c_fields']['product_class'] = array('#type' => 'select',
      '#id' => 'edit-class_select',
      '#title' => t('Product class'),
      '#description' => t('Determines additional fields specific to this type of product.'),
      '#default_value' => $node->pcid,
      '#options' => $classes,
      '#weight' => 0,
      '#attributes' => array('onChange' => 'mod_class_fields(this.value)'),
      '#required' => true,
    );
    
    // Container for class-specific form fields. 
    $form['c_fields']['container'] = array('#type' => 'markup',
      '#value' => '<div id="edit-class_fields"></div>',
    );
  }
  else{
    $form['c_fields']['product_class'] = array('#type' => 'hidden',
      '#value' => 0
    );
  }
  
  $form['#validate']['uc_product_form_validate'] = array();
  //drupal_set_message(print_r($_POST, true));
  return $form;
}

function theme_uc_product_form_prices($prices){
  return '<table><tr><td>'. "\n". drupal_render($prices['list_price'])
    .'</td><td>'. drupal_render($prices['cost'])
    .'</td><td>'. drupal_render($prices['sell_price'])
    ."</td></tr></table>\n";
}

function uc_product_form_validate($form_id, $form_values){
//  drupal_set_message(print_r($form_values, true));
  $pattern = '/^\d*(\.\d*)?$/';
  $price_error = t('Price must be in a valid number format. No commas and only one decimal point.');
  if(!is_numeric($form_values['list_price']['#value']) && !preg_match($pattern, $form_values['list_price']['#value'])){
    form_set_error('list_price', $price_error);
  }
  if(!is_numeric($form_values['cost']['#value']) && !preg_match($pattern, $form_values['cost']['#value'])){
    form_set_error('cost', $price_error);
  }
  if(!is_numeric($form_values['sell_price']['#value']) && !preg_match($pattern, $form_values['sell_price']['#value'])){
    form_set_error('sell_price', $price_error);
  }
  if(!empty($form_values['weight']['#value']) && !is_numeric($form_values['weight']['#value'])){
    form_set_error('weight', t('Weight must be in a valid number format. No commas and only one decimal point.'));
  }
}

/**
 * Implementation of hook_insert().
 */
function uc_product_insert($node){
  // Collect class-specific information and form an array from it to
  // serialize it and store it in the database.
  $post = array();
  foreach ($_POST as $key => $val){
    if (strpos($key, 'ucpc_') !== false){
      $post[substr($key, 5)] = $val;
    }
  }
  $query = '';
  $values = array();
  foreach ($post as $cfid => $val){
    if (is_array($val)){
      foreach ($val as $return){
        $query .= "(%d, %d, '%s'),";
        $values[] = $node->nid;
        $values[] = $cfid;
        $values[] = $return;
      }
    }
    else{
      $query .= "(%d, %d, '%s'),";
      $values[] = $node->nid;
      $values[] = $cfid;
      $values[] = $val;
    }
  }
  $query = rtrim($query, ',');
  if ($node->product_class && !empty($values)){
    db_query("DELETE FROM {uc_product_class_choices} WHERE nid = %d", $node->nid);
    db_query("INSERT INTO {uc_product_class_choices} (nid, cfid, value) VALUES ". $query, $values);
  }
  db_query("INSERT INTO {uc_products} (nid, model, list_price, cost, sell_price, weight, units, pcid, unique_hash) VALUES (%d, '%s', %f, %f, %f, %f, '%s', %d, '%s')",
    $node->nid, $node->model, $node->list_price, $node->cost, $node->sell_price, $node->weight, $node->units, $node->product_class,
    md5($node->nid . $node->model . $node->list_price . $node->cost . $node->sell_price . $node->weight . $node->units . $node->product_class . time())
  );
}

/**
 * Implementation of hook_update().
 */
function uc_product_update($node){
  // Collect class-specific information and form an array.
  $post = array();
  foreach ($_POST as $key => $val){
    if (strpos($key, 'ucpc_') !== false){
        $post[substr($key, 5)] = $val;
    }
  }
  $query = '';
  $values = array();
  foreach ($post as $cfid => $val){
    if (is_array($val)){
      foreach ($val as $return){
        $query .= "(%d, %d, '%s'),";
        $values[] = $node->nid;
        $values[] = $cfid;
        $values[] = $return;
      }
    }
    else{
      $query .= "(%d, %d, '%s'),";
      $values[] = $node->nid;
      $values[] = $cfid;
      $values[] = $val;
    }
  }
  $query = rtrim($query, ',');
  db_query("DELETE FROM {uc_product_class_choices} WHERE nid = %d", $node->nid);
  if ($node->product_class && !empty($values)){
    db_query("INSERT INTO {uc_product_class_choices} (nid, cfid, value) VALUES ". $query, $values);
  }
  db_query("UPDATE {uc_products} SET model = '%s', list_price = %f, cost = %f, sell_price = %f, weight = %f, units = '%s', pcid = %d WHERE nid = %d",
    $node->model, $node->list_price, $node->cost, $node->sell_price, $node->weight, $node->units, $node->product_class, $node->nid);
}

/**
 * Implementation of hook_load().
 */
function uc_product_load(&$node) {
  $t = db_fetch_object(db_query('SELECT p.model, p.list_price, p.cost, p.sell_price, p.weight, p.units, p.pcid, p.unique_hash FROM {uc_products} p WHERE p.nid = %d', $node->nid));
  $t->fields = array();
  $class = uc_product_class_load($t->pcid);
  foreach ($class->fields as $cfid => $field){
    $result = db_query("SELECT * FROM {uc_product_class_choices} WHERE nid = %d AND cfid = %d", $node->nid, $cfid);
    while ($choice = db_fetch_object($result)){
      if ($field['type'] == 'checkboxes'){
        $t->fields[$cfid][$choice->value] = $choice->value;
      }
      else{
        $t->fields[$cfid] = $choice->value;
      }
    }
  }
  return $t;
}

/**
 * Implementation of hook_delete().
 */
function uc_product_delete(&$node) {
  db_query("DELETE FROM {uc_product_class_choices} WHERE nid = %d", $node->nid);
  db_query("DELETE from {uc_products} WHERE nid = %d", $node->nid);
}

/**
 * Implementation of hook_view().
 */
function uc_product_view($node, $teaser = 0, $page = 0) {
  //drupal_set_breadcrumb(array(l(t('Catalog'), 'catalog')));
  $node = node_prepare($node, $teaser);
  //$node->content['body'] = array('#value' => theme('uc_product', $node, $teaser));
  $defaults = variable_get('uc_product_default_fields', array(
    'model',
    'image',
    'display_price',
    'sell_price',
    'weight',
  ));
  if ($defaults['image'] && module_exists('imagecache')){
    if (isset($node->field_image_cache) && file_exists($node->field_image_cache[0]['filepath'])){
      $node->content['image'] = array('#value' => theme('uc_product_image', $node->field_image_cache),
        '#weight' => -2,
      );
    }
  }
  if ($defaults['display_price']){
    $node->content['display_price'] = array('#value' => theme('uc_product_display_price', $node->sell_price),
      '#weight' => -1,
    );
  }
  if (!$teaser){
    if ($defaults['model']){
      $node->content['model'] = array('#value' => theme('uc_product_model', $node->model),
        '#weight' => 0,
      );
    }
    $node->content['body']['#weight'] = 1;
    if ($defaults['list_price']){
      $node->content['list_price'] = array('#value' => theme('uc_product_price', $node->list_price, 'list_price'),
        '#weight' => 2,
      );
    }
    if ($defaults['cost'] && user_access('administer products')){
      $node->content['cost'] = array('#value' => theme('uc_product_price', $node->cost, 'cost'),
        '#weight' => 3,
      );
    }
  }
  else {
    $node->content['#attributes'] = array('style' => 'display: inline');
  }
  if ($defaults['sell_price']){
    $node->content['sell_price'] = array('#value' => theme('uc_product_sell_price', $node->sell_price, $teaser),
      '#weight' => 4,
    );
  }
  if (!$teaser){
    if ($defaults['weight']){
      $node->content['weight'] = array('#value' => theme('uc_product_weight', $node->weight, $node->units),
        '#weight' => 5,
      );
    }
    $node->content['class'] = array('#value' => theme('uc_product_class', $node),
      '#weight' => 6,
    );
    $node->content['add_to_cart'] = array('#value' => theme('uc_product_add_to_cart', $node),
      '#weight' => 10,
    );
  }
  else if (variable_get('uc_product_add_to_cart_teaser', true)){
    $node->content['add_to_cart'] = array('#value' => theme('uc_product_add_to_cart', $node),
      '#weight' => 10,
    );
  }
  //drupal_set_message('<pre>'. print_r($node, true) .'</pre>');
  return $node;
}

function uc_product_form_alter($form_id, &$form){
    if ($form_id == 'search_form' && arg(0) == 'admin' && arg(1) == 'store' && arg(2) == 'products' && user_access('use advanced search')) {
    // Keyword boxes:
    $form['advanced'] = array(
      '#type' => 'fieldset',
      '#title' => t('Advanced search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#attributes' => array('class' => 'search-advanced'),
    );
    $form['advanced']['keywords'] = array(
      '#prefix' => '<div class="criterion">',
      '#suffix' => '</div>',
    );
    $form['advanced']['keywords']['or'] = array(
      '#type' => 'textfield',
      '#title' => t('Containing any of the words'),
      '#size' => 30,
      '#maxlength' => 255,
    );
    $form['advanced']['keywords']['phrase'] = array(
      '#type' => 'textfield',
      '#title' => t('Containing the phrase'),
      '#size' => 30,
      '#maxlength' => 255,
    );
    $form['advanced']['keywords']['negative'] = array(
      '#type' => 'textfield',
      '#title' => t('Containing none of the words'),
      '#size' => 30,
      '#maxlength' => 255,
    );

    // Taxonomy box:
    if ($taxonomy = module_invoke('taxonomy', 'form_all', 1)) {
      $form['advanced']['category'] = array(
        '#type' => 'select',
        '#title' => t('Only in the category(s)'),
        '#prefix' => '<div class="criterion">',
        '#size' => 10,
        '#suffix' => '</div>',
        '#options' => $taxonomy,
        '#multiple' => TRUE,
      );
    }

    // Node types:
    $types = uc_catalog_node_types();
    $form['advanced']['type'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Only of the type(s)'),
      '#prefix' => '<div class="criterion">',
      '#suffix' => '</div>',
      '#options' => $types,
    );
    $form['advanced']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Advanced search'),
      '#prefix' => '<div class="action clear-block">',
      '#suffix' => '</div>',
    );

    $form['#validate']['node_search_validate'] = array();
  }
}

function uc_product_search($op, $keys = null){
  switch ($op){
    case 'name':
      return t('Products');
  }
}

/******************************************************************************
 * TAPIr Hooks                                                                *
 ******************************************************************************/

function uc_product_table_settings(){
  $tables = array();
  
  $tables[] = array(
    'id' => 'uc_product_table',
    'description' => t('Lists a group of products in an abbreviated format.'),
    'path' => 'admin/store/settings/tables',
    'access' => 'administer store',
    'preview' => FALSE,
  );
  
  return $tables;
}

function uc_product_table($op, $args = array('tid' => null)){
  switch($op){
    case 'fields':
      $fields = array();
      $fields[] = array('name' => 'image', 'title' => t('Image'), 'weight' => -5, 'enabled' => module_exists('imagecache'));
      $fields[] = array('name' => 'name', 'title' => t('Name'), 'weight' => 0, 'enabled' => true, 'attributes' => array('field' => 'n.title'));
      $fields[] = array('name' => 'price', 'title' => t('Price'), 'weight' => 5, 'enabled' => true, 'attributes' => array('field' => 'p.sell_price'));
      if (arg(0) != 'admin' || $_GET['q'] == 'admin/store/settings/tables/uc_product_table'){
        $fields[] = array(
          'name' => 'add_to_cart',
          'title' => t('Add to cart'),
          'weight' => 10,
          'enabled' => false,
          'attributes' => array('nowrap' => 'nowrap'),
        );
      }
      return $fields;
    case 'data':
      $header = tapir_get_header('uc_product_table', $args);
      $order = substr(tablesort_sql($header), 10);
      if (empty($order)){
        $order = 'n.title';
      }
      $data = array();
      $tid = $args['tid'];
      if (!isset($tid)){
        $nids = $args['nids'];
        if (empty($nids)){
          $result = pager_query(db_rewrite_sql("SELECT n.nid FROM {node} AS n RIGHT JOIN {uc_products} AS p ON n.nid = p.nid ORDER BY ". $order), variable_get('uc_product_default_nodes', 10), 0, null);
        }
        else{
          $result = pager_query(db_rewrite_sql("SELECT n.nid FROM {node} AS n RIGHT JOIN {uc_products} AS p ON n.nid = p.nid WHERE n.nid IN (%s) ORDER BY ". $order), variable_get('uc_product_default_nodes', 10), 0, null, implode(',', $nids));
        }
      }
      else{
        $sql = 'SELECT DISTINCT(n.nid), n.sticky, n.title, n.created FROM {node} n INNER JOIN {term_node} tn ON n.nid = tn.nid RIGHT JOIN {uc_products} AS p ON n.nid = p.nid WHERE tn.tid = %d AND n.status = 1 ORDER BY '. $order;
        $sql_count = 'SELECT COUNT(DISTINCT(n.nid)) FROM {node} n INNER JOIN {term_node} tn ON n.nid = tn.nid RIGHT JOIN {uc_products} AS p ON n.nid = p.nid WHERE tn.tid = %d AND n.status = 1';
        $sql = db_rewrite_sql($sql);
        $sql_count = db_rewrite_sql($sql_count);
        $result = pager_query($sql, variable_get('uc_product_default_nodes', 10), 0, $sql_count, $tid);
      }
      while ($node = db_fetch_object($result)) {
        $node = node_load($node->nid);
        if ($node->type != 'image'){
          if (module_exists('imagecache') && isset($node->field_image_cache) && file_exists($node->field_image_cache[0]['filepath'])){
            $data['image'][] = l(theme('imagecache', 'product', $node->field_image_cache[0]['filepath']), 'node/'. $node->nid, array(), null, null, false, true);
          }
          else{
            $data['image'][] = t('n/a');
          }
          $data['name'][] = array('data' => l($node->title, 'node/'. $node->nid), 'width' => '100%');
          $data['price'][] = theme('uc_product_sell_price', $node->sell_price, true);
          if (arg(0) != 'admin'){
            $data['add_to_cart'][] = drupal_get_form('uc_catalog_buy_it_now_form_'. $node->nid, $node);
          }
        }
      }
      return $data;
    case 'attributes':
      return $args['attributes'];
  }
}

/* function uc_product_table_alter($table_id, $op, $args){
  
} */

/******************************************************************************
 * Übercart Hooks                                                             *
 ******************************************************************************/

function uc_product_product_info(){
  return array(
    'product' => array(
      'module' => 'uc_product',
      'table' => 'uc_products',
    ),
  );
}

function uc_product_store_status(){
  $title = t('Images');
  if (!module_exists('imagefield') || !module_exists('imagecache')){
    $status = 'error';
    $description = t("In order to display product images, please <a href=\"!href\">enable</a> the <a href=\"http://drupal.org/project/cck\">Content</a>, <a href=\"http://drupal.org/project/imagefield\">CCK Image field</a>, and the <a href=\"http://drupal.org/project/imagecache\">Imagecache</a> modules.", array('!href' => url('admin/build/modules')));
  }
  else{
    $result = db_query("SELECT field_name, type FROM {node_field} WHERE field_name = 'field_image_cache' AND type = 'image'");
    $field_check = (bool)db_num_rows($result);
    $result = db_query("SELECT field_name, type_name FROM {node_field_instance} WHERE field_name = 'field_image_cache' AND type_name = 'product'");
    $product_field_check = (bool)db_num_rows($result);
    $presets = array('product', 'product_list', 'thumbnail');
    if (module_exists('uc_catalog')){
      $presets[] = 'category';
    }
    if (module_exists('uc_cart')){
      $presets[] = 'cart';
    }
    if (module_exists('uc_manufacturer')){
      $presets[] = 'manufacturer';
    }
    $result = db_query("SELECT presetid FROM {imagecache_preset} WHERE presetname IN ('". implode("','", $presets) ."')");
    $preset_check = (db_num_rows($result) == count($presets));
    $actions = array();
    while ($preset_id = db_fetch_array($result)){
      $actions[$preset_id['presetid']] = db_result(db_query("SELECT actionid FROM {imagecache_action} WHERE presetid = %d", $preset_id['presetid']));
    }
    $action_check = (count(array_filter($actions)) == count($presets));
    if ($field_check && $product_field_check && $preset_check && $action_check){
      $status = 'ok';
      $description = t("Imagefield and Imagecache have been set up to display product images.");
    }
    else{
      $status = 'warning';
      $checks = ($field_check << 3) + ($product_field_check << 2) + ($preset_check << 1) + $action_check;
      $description = t("Click <strong><a href=\"!path\">here</a></strong> to create defaults for the following problems:", array('!path' => url('admin/store/settings/products/defaults/'. $checks)));
      $description .= "\n<br /><ul>\n";
      if (!$field_check){
        $description .= "<li>". t("The Image field has not been created for CCK.") ."</li>\n";
      }
      if (!$product_field_check){
        $description .= "<li>". t("The Image field has not been attached to Product nodes.") ."</li>\n";
      }
      if (!$preset_check){
        $description .= "<li>". t('The expected Imagecache presets ("!presets") have not been created.', array('!presets' => implode('", "', $presets))) ."</li>\n";
      }
      if (!$action_check){
        $description .= "<li>". t('The Imagecache presets do not contain actions to perform on images. Images may be displayed in their original formats.') ."</li>\n";
      }
      $description .= "</ul>";
    }
  }
  
  return array(array('status' => $status, 'title' => $title, 'desc' => $description));
}

/**
 * Implementation of Übercart hook_cart_display().
 */
function uc_product_cart_display($item){
  $node = node_load($item->nid);
  $element = array();
  $element['nid'] = array('#type' => 'value', '#value' => $node->nid);
  $element['module'] = array('#type' => 'value', '#value' => 'uc_product');
  $element['remove'] = array('#type' => 'checkbox');
  $op_names = '';
  if (module_exists('uc_attribute')){
    $op_names = "<ul class=\"cart-options\">\n";
    foreach ($item->options as $option){
      $op_names .= '<li>'. $option['attribute'] .': '. $option['name'] ."</li>\n";
    }
    $op_names .= "</ul>\n";
  }
  $element['options'] = array('#value' => $op_names);
  $element['title'] = array(
    '#value' => l($node->title, 'node/'. $node->nid),
  );
  $element['#total'] = $item->price * $item->qty;
  $element['data'] = array('#type' => 'hidden', '#value' => serialize($item->data));
  $element['qty'] = array(
    '#type' => 'textfield',
    '#default_value' => $item->qty,
    '#size' => 3,
    '#maxlength' => 3
  );
  return $element;
}

/**
 * Update information about a specific item in current cart.
 */
function uc_product_update_cart_item($nid, $data = array(), $qty, $cid = NULL) {
  if (!$nid) return NULL;
  $cid = !(is_null($cid) || empty($cid)) ? $cid : uc_cart_get_id();
  if ($qty < 1){
    uc_cart_remove_item($nid, $cid, $data);
  }
  else{
    db_query("UPDATE {uc_cart_products} SET qty = %d, changed = %d WHERE nid = %d AND cart_id = '%s' AND data = '%s'", $qty, time(), $nid, $cid, serialize($data));
    cache_clear_all();
  }

  // Rebuild the items hash
  uc_cart_get_contents(NULL, 'rebuild');
  if (!substr(request_uri(), 'cart', -4)) {
    drupal_set_message(t('Your item(s) have been updated.'));
  }
}

function uc_product_add_to_cart_data($form_values){
  $product = node_load($form_values['nid']);
  $class = uc_product_class_load($product->pcid);
  if ($class){
    $p_fields = $product->fields;
    $c_fields = $class->fields;
    //$node->content['c_fields'] = array('#value' => '<pre>'. print_r($c_fields, true) .'</pre>');
    //$node->content['p_fields'] = array('#value' => '<pre>'. print_r($p_fields, true) .'</pre>');
    if (is_array($c_fields) && is_array($p_fields)){
      $output = array();
      foreach($c_fields as $cfid => $field_info){
        $label = $field_info['name'];
        if (is_array($p_fields[$cfid])){
          foreach ($p_fields[$cfid] as $ccid){
            $output[$label][] = $field_info['choices'][$ccid];
          }
        }
        else if (isset($field_info['choices'][$p_fields[$cfid]])){
          $output[$label] = $field_info['choices'][$p_fields[$cfid]];
        }
        else{
          $output[$label] = $p_fields[$cfid];
        }
      }
    }
  }
  return array('module' => 'uc_product', 'class_choices' => $output);
}

/******************************************************************************
 * Menu Callbacks                                                             *
 ******************************************************************************/

function uc_product_default(){
  $output = tapir_get_table('uc_product_table', $null);
  $output .= theme('pager');
  return $output;
}

function uc_product_image_defaults($checks){
  $field_check = $checks & 8;
  $product_field_check = $checks & 4;
  $preset_check = $checks & 2;
  $action_check = $checks & 1;
  
  $presets = array('product', 'product_list', 'thumbnail');
  if (module_exists('uc_catalog')){
    $presets[] = 'category';
  }
  if (module_exists('uc_cart')){
    $presets[] = 'cart';
  }
  if (module_exists('uc_manufacturer')){
    $presets[] = 'manufacturer';
  }

  if (!$field_check){
    db_query("INSERT INTO {node_field} (field_name, type, global_settings, required, multiple, db_storage) VALUES ('field_image_cache', 'image', '%s', 0, 1, 0)", 'a:0:{}');
    content_clear_type_cache();
  }
  if (!$product_field_check){
    db_query("INSERT INTO {node_field_instance} VALUES ('field_image_cache', 'product', -2, 'Image', 'image', '%s', '%s', '')", 'a:6:{s:14:"max_resolution";s:1:"0";s:10:"image_path";s:6:"ubercart_images";s:10:"custom_alt";i:1;s:12:"custom_title";i:1;s:13:"teaser_preset";N;s:11:"body_preset";N;}', 'a:3:{s:5:"label";a:1:{s:6:"format";s:6:"hidden";}s:6:"teaser";a:1:{s:6:"format";s:6:"hidden";}s:4:"full";a:1:{s:6:"format";s:6:"hidden";}}');
    switch ($GLOBALS['db_type']){
      case 'mysql':
      case 'mysqli':
        db_query("CREATE TABLE IF NOT EXISTS {content_field_image_cache} (
          `vid` int(10) unsigned NOT NULL default '0',
          `delta` int(10) unsigned NOT NULL default '0',
          `nid` int(10) unsigned NOT NULL default '0',
          `field_image_cache_fid` int(11) NOT NULL default '0',
          `field_image_cache_title` varchar(255) NOT NULL default '',
          `field_image_cache_alt` varchar(255) NOT NULL default '',
          PRIMARY KEY  (`vid`,`delta`)
        ) /*!40100 DEFAULT CHARACTER SET utf8 */;");
      break;
      case 'pgsql':
        db_query('CREATE TABLE {content_field_image_cache} (
          "vid" int(10) unsigned NOT NULL default \'0\',
          "delta" int(10) unsigned NOT NULL default \'0\',
          "nid" int(10) unsigned NOT NULL default \'0\',
          "field_image_cache_fid" int(11) NOT NULL default \'0\',
          "field_image_cache_title" varchar(255) NOT NULL,
          "field_image_cache_alt" varchar(255) NOT NULL,
          PRIMARY KEY  ("vid","delta")
        );');
      break;
    }
    content_clear_type_cache();
  }
  if (!$preset_check){
    $result = db_query("SELECT * FROM {imagecache_preset} WHERE presetname IN ('". implode("','", $presets) ."')");
    $preset_keys = array();
    foreach ($presets as $preset){
      $preset_keys[$preset] = 0;
    }
    $presets = $preset_keys;
    while ($preset = db_fetch_array($result)){
      $presets[$preset['presetname']] = $preset['presetid'];
    }
    //drupal_set_message('<pre>'. print_r($presets, true) .'</pre>');
    foreach ($presets as $name => $id){
      if ($id == 0){
        $id = db_next_id('{imagecache_preset}_presetid');
        db_query("INSERT INTO {imagecache_preset} (presetid, presetname) VALUES (%d, '%s')", $id, $name);
      }
    }
  }
  if (!$action_check){
    $result = db_query("SELECT ia.actionid, ip.presetid, ip.presetname FROM {imagecache_preset} AS ip LEFT JOIN {imagecache_action} AS ia ON ip.presetid = ia.presetid WHERE ip.presetname IN ('". implode("','", array_keys($presets)) ."')");
    $presets = array();
    while ($preset = db_fetch_array($result)){
      if (is_null($preset['actionid'])){
        switch ($preset['presetname']){
          case 'product':
            db_query("INSERT INTO {imagecache_action} (actionid, presetid, weight, data) VALUES (%d, %d, 0, '%s')", db_next_id('{imagecache_action}_actionid'), $preset['presetid'], 'a:4:{s:8:"function";s:5:"scale";s:3:"fit";s:6:"inside";s:5:"width";s:3:"100";s:6:"height";s:3:"100";}');
          break;
          case 'product_list':
            db_query("INSERT INTO {imagecache_action} (actionid, presetid, weight, data) VALUES (%d, %d, 0, '%s')", db_next_id('{imagecache_action}_actionid'), $preset['presetid'], 'a:4:{s:8:"function";s:5:"scale";s:3:"fit";s:6:"inside";s:5:"width";s:3:"100";s:6:"height";s:3:"100";}');
          break;
          case 'thumbnail':
            db_query("INSERT INTO {imagecache_action} (actionid, presetid, weight, data) VALUES (%d, %d, 0, '%s')", db_next_id('{imagecache_action}_actionid'), $preset['presetid'], 'a:4:{s:8:"function";s:5:"scale";s:3:"fit";s:6:"inside";s:5:"width";s:2:"35";s:6:"height";s:2:"35";}');
          break;
          case 'category':
            db_query("INSERT INTO {imagecache_action} (actionid, presetid, weight, data) VALUES (%d, %d, 0, '%s')", db_next_id('{imagecache_action}_actionid'), $preset['presetid'], 'a:4:{s:8:"function";s:5:"scale";s:3:"fit";s:6:"inside";s:5:"width";s:2:"96";s:6:"height";s:2:"96";}');
          break;
          case 'cart':
            db_query("INSERT INTO {imagecache_action} (actionid, presetid, weight, data) VALUES (%d, %d, 0, '%s')", db_next_id('{imagecache_action}_actionid'), $preset['presetid'], 'a:4:{s:8:"function";s:5:"scale";s:3:"fit";s:6:"inside";s:5:"width";s:2:"50";s:6:"height";s:2:"50";}');
          break;
          case 'manufacturer':
            db_query("INSERT INTO {imagecache_action} (actionid, presetid, weight, data) VALUES (%d, %d, 0, '%s')", db_next_id('{imagecache_action}_actionid'), $preset['presetid'], 'a:4:{s:8:"function";s:5:"scale";s:3:"fit";s:6:"inside";s:5:"width";s:2:"80";s:6:"height";s:2:"80";}');
          break;
        }
      }
    }
  }
  file_check_directory(file_create_path('ubercart_images'), FILE_CREATE_DIRECTORY);
  cache_clear_all('imagecache:presets', 'cache');
  drupal_goto('admin/store');
}

function uc_product_overview(){
  drupal_add_css(drupal_get_path('module', 'uc_store') .'/uc_store.css');
  drupal_add_js(drupal_get_path('module', 'uc_store') .'/uc_store.js', 'module');
  drupal_add_js("var text_show = '". t('- Show links -') ."';\nvar text_hide = '". t('- Hide links -') ."';\n", 'inline');

  $main_menu = menu_get_item(NULL, 'admin/store/products');
  usort($main_menu['children'], '_menu_sort');
  foreach ($main_menu['children'] as $mid) {
    if ($mid > 0) {
      $submenu[] = menu_get_item($mid);
    }
  }

  $output = '<table class="uc-store-admin-table" align="center"><tr valign="top">';

  $panels = 0;
  if (is_array($submenu)) {
    if (variable_get('uc_store_display_links', FALSE)) {
      $disp = '';
      $title = t('- Hide links -');
    }
    else {
      $disp = 'display: none;';
      $title = t('- Show links -');
    }
    foreach ($submenu as $menu) {
      $panel++;
      if ($panel % 4 == 0) {
        $output .= '</tr><tr valign="top">';
      }
      switch ($menu['path']){
        case 'admin/store/products/view':
          $file = 'file:search';
        break;
        case 'admin/store/products/create_product':
          $file = 'file:cut-n-measure';
        break;
        case 'admin/store/products/categories':
          $file = 'file:footprints';
        break;
        case 'admin/store/products/orphans':
          $file = 'file:missing';
        break;
        case 'admin/store/products/classes':
          $file = 'file:attachment';
        break;
        case 'admin/store/products/attributes':
          $file = 'file:paint';
        break;
        default:
          $file = $menu['path'];
        break;
      }
      $panel_title = $menu['title'];
      $panel_links = theme('admin_block_content', system_admin_menu_block($menu));
      $panel_table = '<table width="100%"><tr>'
                    .'<td>'. l(uc_store_get_icon($file), $menu['path'],
                               array(), NULL, NULL, FALSE, TRUE) .'</td>'
                    .'<td class="panel-title">'. l($menu['title'], $menu['path'])
                    .'</td></tr>';
      if (strlen($panel_links) > 0) {
        $panel_table .= '<tr><td nowrap colspan="2" class="panel-links" style="'. $disp .'">'
                     . $panel_links .'</td></tr><tr>'
                      .'<td align="center" colspan="2" class="panel-show-link" '
                      .'id="show-links-'. $panel .'"><a>'. $title
                      .'</a></td></tr>';
      }
      $panel_table .= '</table>';
      $output .= '<td class="uc-store-admin-panel" id="panel-'. $panel .'">'
               . $panel_table .'</td>';
    }
  }
  $output .= '</tr></table>';

  return $output;
}

/**
 * Lists the subcategories of product administration.
 */
function uc_product_administration(){
  $nids = array();
  $args = func_get_args();
  foreach ($args as $nid){
    if (is_numeric($nid)){
      $nids[] = (int)$nid;
    }
  }
  drupal_add_js(drupal_get_path('module', 'uc_product') .'/uc_product.js', 'module');
  $types = array_keys(module_invoke_all('product_info'));
  $types[] = 'product';
  $result = db_query("SELECT v.vid, v.name FROM {vocabulary} AS v LEFT JOIN {vocabulary_node_types} AS vnt ON v.vid = vnt.vid WHERE vnt.type IN ('". implode("','", $types) ."')");
  $vocab_options = array();
  while ($option = db_fetch_array($result)){
    $vocab_options[$option['vid']] = $option['name'];
  }
  $form['vocabs'] = array('#type' => 'select',
    '#id' => 'ubrowser-vocab-select',
    //'#parents' => array(),
    '#title' => t('Vocabulary'),
    '#default_value' => variable_get('uc_catalog_vid', variable_get('uc_manufacturer_vid', 0)),
    '#options' => $vocab_options,
  );
  drupal_add_js('$(document).ready(function(){
    $("#ubrowser-vocab-select").change(function(){
      switch_vocabulary("'. base_path() .'");
    });
  })', 'inline');
  drupal_prepare_form('vocab-switcher', $form);
  $output = drupal_render($form);
  $settings = array(
    'div' => '#products-selector',
    'class' => 'product-ubrowser',
    'vid' => variable_get('uc_catalog_vid', 0),
    'filter' => implode(',', uc_product_get_product_types()),
    'search' => 'true',
    'nids' => 'true',
    'nodesg' => 'product',
    'nodepl' => 'products',
    'multi' => 'true',
    'select' => 'buffer_products("'. base_path() .'","'. file_create_url('') .'")',
  );

  if (module_exists('uc_catalog')) {
    $output .= ubrowser($settings, 'products-selector');
    $output .= drupal_get_form('uc_product_buffer_form', $nids);
  }
  $args = array('nids' => $nids, 'attributes' => array('class' => 'product-list'));
  $output .= tapir_get_table('uc_product_table', $args);
  $output .= theme('pager');
  
  return $output;
}

function uc_product_buffer_form($nids){
  $buffer = '';
  foreach ($nids as $nid){
    $node = node_load($nid);
    $buffer .= theme('imagecache', 'thumbnail', $node->field_image_cache['filepath']);
  }
  $form['#attributes'] = array('class' => 'product-buffer');
  $form['thumbnails'] = array('#type' => 'markup',
    '#value' => '<div id="buffer-images"></div>',
  );
  $form['products'] = array('#type' => 'hidden',
  );
  $form['reset'] = array('#type' => 'submit',
    '#value' => t('Reset'),
  );
  $form['submit'] = array('#type' => 'submit',
    '#value' => t('List'),
  );

  return $form;
}

function uc_product_buffer_form_submit($form_id, $form_values){
  $item = menu_get_item(menu_get_active_item());
  //drupal_set_message(print_r($form_values, true));
  if ($form_values['op'] == t('Reset')){
    return $item['path'];
  }
  else{
    return $item['path'] . $form_values['products'];
  }
}

/**
 * Allows store administrators to control what product information is relavent to their store.
 */
function uc_product_settings(){
  $form = array();
  $options = array(
    'model' => t('Model'),
    'image' => t('Image'),
    'display_price' => t('Display Price'),
    'list_price' => t('List Price'),
    'cost' => t('Cost'),
    'sell_price' => t('Sell Price'),
    'weight' => t('Weight'),
  );
  
  $form['uc_product_default_fields'] = array('#type' => 'checkboxes',
    '#title' => t('Product Fields Displayed'),
    '#description' => t('Check the fields that will be displayed in the product listing.'),
    '#default_value' => variable_get('uc_product_default_fields', array(
      'model' => 'model',
      'image' => 'image',
      'display_price' => 'display_price',
      'sell_price' => 'sell_price',
      'weight' => 'weight',
    )),
    '#options' => $options,
    '#weight' => -10,
  );
  
  $options = array();
  for ($i = 10; $i <= 100; $i += 10) {
    $options[$i] = $i;
  }
  $form['uc_product_default_nodes'] = array('#type' => 'select',
    '#title' => t('Product List Page Size'),
    '#description' => t('The number of rows displayed by product lists on each page.'),
    '#default_value' => variable_get('uc_product_default_nodes', 10),
    '#options' => $options,
  );
  
  $form['uc_product_add_to_cart_teaser'] = array('#type' => 'radios',
   '#title' => t('Show Add to Cart form in node teasers?'),
   '#options' => array(1 => t('Yes'), 0 => t('No')),
   '#default_value' => variable_get('uc_product_add_to_cart_teaser', true),
  );
  
  return system_settings_form($form);
}

function uc_product_class_default(){
  $result = db_query("SELECT * FROM {uc_product_classes}");
  $header = array(t('Name'), t('# of Fields'), array('data' => t('Operations'), 'colspan' => '3'));
  $rows = array();
  while($class = db_fetch_object($result)){
    $class->fields = array();
    $field_result = db_query("SELECT * FROM {uc_class_fields} WHERE pcid = %d", $class->pcid);
    while ($field = db_fetch_object($field_result)){
      $class->fields[$field->cfid] = array(
        //'title' => $field->title,
        'name' => $field->name,
        'type' => $field->type,
      );
      $choices = array();
      $choice_result = db_query("SELECT * FROM {uc_class_choices} WHERE cfid = %d", $field->cfid);
      while ($choice = db_fetch_object($choice_result)){
        $choices[$choice->ccid] = $choice->name;
      }
      $class->fields[$field->cfid]['choices'] = $choices;
    }
    $fields = $class->fields;
    $rows[] = array(
      $class->name,
      is_array($fields) ? count($fields) : 0,
      l(t('fields'), 'admin/store/products/classes/'. $class->pcid .'/fields'),
      l(t('edit'), 'admin/store/products/classes/'. $class->pcid .'/edit'),
      l(t('delete'), 'admin/store/products/classes/'. $class->pcid .'/delete'),
    );
  }
  if (count($rows) == 0){
    $rows[] = array(array('data' => t('No product classes have been defined yet.'), 'colspan' => '5'));
  }
  
  $output = theme('table', $header, $rows);
  $output .= '<h2>'. t('Add a Class') .'</h2>';
  $output .= drupal_get_form('uc_product_class_form');
  
  return $output;
}

/**
 *  Form builder for product classes.
 */
function uc_product_class_form($pcid = null){
  if ($pcid){
    $class = uc_product_class_load($pcid);
    $form['pcid'] = array('#type' => 'hidden', '#value' => $pcid);
    
    $crumbs = drupal_get_breadcrumb();
    $crumbs[] = l(t('Classes'), 'admin/store/products/classes');
    drupal_set_breadcrumb($crumbs);
  }
  $form['name'] = array('#type' => 'textfield',
    '#title' => t('Class name'),
    '#default_value' => $class->name,
    '#weight' => 0,
  );
  $form['op'] = array('#type' => 'submit',
    '#value' => t('Submit'),
    '#weight' => 1,
  );
  
  return $form;
}

function uc_product_class_form_validate($form_id, $form_values){
  if (empty($form_values['name'])){
    form_set_error(t('You must name the product class.'));
  }
}

function uc_product_class_form_submit($form_id, $form_values){
  if (isset($form_values['pcid'])){
    db_query("UPDATE {uc_product_classes} SET name = '%s' WHERE pcid = %d", $form_values['name'], $form_values['pcid']);
  }
  else{
    db_query("INSERT INTO {uc_product_classes} (name) VALUES ('%s')", $form_values['name']);
  }
  return 'admin/store/products/classes';
}

function uc_product_class_delete_confirm($class_id){
  $result = db_query("SELECT COUNT(*) AS number FROM {uc_products} WHERE pcid = %d", $class_id);
  $products = db_fetch_object($result);
  $form['pcid'] = array('#type' => 'value', '#value' => $class_id);
  $form['#redirect'] = 'admin/store/products/classes';
  $output = confirm_form($form, t('Be very sure you want to delete this product class. '), 'admin/store/products/classes',
    format_plural($products->number, 'There is 1 product of this class. ', 'There are @count products of this class. ')
    . t('All the data associated with this class will be deleted as well.'), t('Continue'), t('Cancel'));
  
  return $output;
}

function uc_product_class_delete_confirm_submit($form_id, $form_values){
  if ($form_values['confirm']){
    db_query("UPDATE {uc_products} SET pcid = 0 WHERE pcid = %d", $form_values['pcid']);
    // Drupal had better get support for foreign key constraints soon...
    db_query("DELETE pcc FROM {uc_product_class_choices} AS pcc LEFT JOIN {uc_class_fields} AS cf ON pcc.cfid = cf.cfid WHERE cf.pcid = %d", $form_values['pcid']);
    db_query("DELETE cc FROM {uc_class_choices} AS cc LEFT JOIN {uc_class_fields} AS cf ON cc.cfid = cf.cfid WHERE cf.pcid = %d", $form_values['pcid']);
    db_query("DELETE FROM {uc_class_fields} WHERE pcid = %d", $form_values['pcid']);
    // because then all these queries would be completely unneccessary.
    db_query("DELETE FROM {uc_product_classes} WHERE pcid = %d", $form_values['pcid']);
    
    module_invoke_all('product_class', 'delete', 'class', $form_values['pcid']);
    
    drupal_set_message(t('Product class deleted.'));  
  }
}

/**
 * Not an implementation of hook_view() because product classes aren't nodes.
 */
function uc_product_class_view($class_id){
  if (!($class = uc_product_class_load($class_id))){
    drupal_set_message(t('Product class with pcid = @id does not exist.', array('@id' => $class_id)), 'error');
    drupal_goto('admin/store/products/classes');
  }
  $breadcrumbs = drupal_get_breadcrumb();
  $breadcrumbs[] = l(t('Classes'), 'admin/store/products/classes/');
  drupal_set_breadcrumb($breadcrumbs);
  $output = '<h2>'. $class->name .'</h2>';
  $fields = $class->fields ? $class->fields : array();
  $rows = array();
  foreach ($fields as $key => $field){
    $rows[] = array(/* $field['title'], */ $field['name'], $field['type'], empty($field['choices']) ? '' : implode(', ', $field['choices']), l(t('edit'), 'admin/store/products/classes/'. $class_id .'/fields/'. $key .'/edit'), l(t('delete'), 'admin/store/products/classes/'. $class_id .'/fields/'. $key .'/delete'));
  }
  if (count($rows) == 0){
    $rows[] = array(array('data' => t('No fields defined for this product class.'), 'colspan' => '5'));
  }
  $header = array(/* t('Title'), */ t('Name'), t('Type'), t('Options'), array('data' => t('Operations'), 'colspan' => '2'));
  $output .= theme('table', $header, $rows);
  $output .= l(t('Add a field'), 'admin/store/products/classes/'. $class_id .'/fields/add');
  return $output;
}

/**
 * Form building functions for adding or editing a product class' form field.
 */
function uc_product_class_field_form($class_id, $field_id = null){
  $form = array();
  $class = uc_product_class_load($class_id);
  $values_ = ($class && !is_null($field_id)) ? $class->fields : array();
  $values = !empty($values_) ? $values_[$field_id] : array();
  $crumbs = drupal_get_breadcrumb();
  $crumbs[] = l(t('Product Classes'), 'admin/store/products/classes');
  $crumbs[] = l($class->name, 'admin/store/products/classes/'. $class_id);
  drupal_set_breadcrumb($crumbs);
  
  $form['name'] = array('#type' => 'textfield',
    '#title' => t('Name'),
    '#default_value' => $values['name'],
    '#required' => true,
    '#weight' => 0,
  );
  $form['type'] = array('#type' => 'select',
    '#title' => t('Type'),
    '#options' => array(
      'checkboxes' => t('Check boxes'),
      //'date' => t('Date field'),
      //'file' => t('File upload field'),
      'radios' => t('Radio buttons'),
      'select' => t('Select boxes'),
      'textarea' => t('Text area'),
      'textfield' => t('Text field'),
    ),
    '#default_value' => isset($values['type']) ? $values['type'] : 'textfield',
    '#weight' => 1,
  );
  $form['choices'] = array('#type' => 'textarea',
    '#title' => t('Choices'),
    '#description' => t('The list of different choices for this field, one per line. This only applies to and is required for check boxes, radio buttons, and select boxes.'),
    '#default_value' => !empty($values['choices']) ? implode("\n", $values['choices']) : '',
    '#weight' => 2,
  );
  $form['pcid'] = array('#type' => 'hidden', '#value' => $class_id,);
  $form['cfid'] = array('#type' => 'hidden', '#value' => $field_id,);
  $form['op'] = array('#type' => 'submit',
    '#value' => t('Submit'),
    '#weight' => 3,
  );
  
  drupal_add_js('$(document).ready(function(){
    if ($("#edit-type option:selected").val() == "textfield" || $("#edit-type option:selected").val() == "textarea"){
      $("#edit-choices").attr("disabled", "disabled");
    }
    $("#edit-type").change(function(){
      var selection = $(this).children("option:selected");
      if (selection.val() == "textfield" || selection.val() == "textarea"){
        $("#edit-choices").attr("disabled", "disabled");
      }
      else{
        $("#edit-choices").removeAttr("disabled");
      }
    });
  })', 'inline');
  
  return $form;
}

function uc_product_class_field_form_validate($form_id, $form_values){
  if (empty($form_values['name'])){
    form_set_error('form_name', t('You must set a name for this field.'));
  }
  if (in_array($form_values['type'], array('checkboxes', 'radios', 'select')) && empty($form_values['choices'])){
    form_set_error('choices', t('At least one option must be supplied for @type.', array('@type' => $form_values['type'])));
  }
}

function uc_product_class_field_form_submit($form_id, $form_values){
  if ($class = uc_product_class_load($form_values['pcid'])){
    if (!isset($form_values['cfid']) || $form_values['cfid'] === ''){
      $form_values['cfid'] = db_next_id("{uc_class_fields}_cfid");      
      db_query("INSERT INTO {uc_class_fields} (cfid, pcid, name, type) VALUES (%d, %d, '%s', '%s')",
        $form_values['cfid'], $form_values['pcid'], $form_values['name'], $form_values['type']);
    }
    else{
      db_query("UPDATE {uc_class_fields} SET name = '%s', type = '%s' WHERE cfid = %d",
        $form_values['name'], $form_values['type'], $form_values['cfid']);
    }
    $result = db_query("SELECT * FROM {uc_class_choices} WHERE cfid = %d", $form_values['cfid']);
    $old_num = db_num_rows($result);
    $new_num = 0;
    $new_choices = explode("\n", trim($form_values['choices']));
    foreach ($new_choices as $new_choice){
      if ($old_choice = db_fetch_array($result)){
        db_query("UPDATE {uc_class_choices} SET name = '%s' WHERE ccid = %d", $new_choice, $old_choice['ccid']);
      }
      else{
        db_query("INSERT INTO {uc_class_choices} (cfid, name) VALUES (%d, '%s')", $form_values['cfid'], $new_choice);
      }
      $new_num++;
    }
    if ($new_num < $old_num){
      db_query("DELETE FROM {uc_class_choices} WHERE cfid = %d ORDER BY ccid DESC LIMIT %d", $form_values['cfid'], $old_num - $new_num);
      $affected_list = "<ul>\n";
      $result = db_query("SELECT nid, model FROM {uc_products} WHERE pcid = %d", $form_values['pcid']);
      while ($affected = db_fetch_object($result)){
        $affected_list .= "<li>". l($affected->model, 'node/'. $affected->nid) ."</li>\n";
      }
      $affected_list .= "</ul>\n";
      drupal_set_message(t('The following products have been affected by this action. Please check their class data for errors.'). $affected_list);
    }
    return 'admin/store/products/classes/'. $form_values['pcid'];
  }
  else{
    drupal_set_message(t('Error loading product class.'), 'error');
  }
}

function uc_product_class_field_delete_confirm($class_id, $field_id){
  $form['cfid'] = array('#type' => 'value', '#value' => $field_id);
  $form['#redirect'] = 'admin/store/products/classes/'. $class_id .'/edit';
  
  $result = db_query("SELECT COUNT(*) as number FROM {uc_products} WHERE pcid = %d", $class_id);
  $products = db_fetch_object($result);
  $output = confirm_form($form, t('Are you sure you want to delete this field?'), 'admin/store/products/classes/'. $class_id .'/edit',
    format_plural($products->number, 'There is 1 product of this class. ', 'There are @count products of this class. ')
    . t('All the data associated with this field will be deleted as well.'), t('Continue'), t('Cancel'));
  return $output;
}

function uc_product_class_field_delete_confirm_submit($form_id, $form_values){
  db_query("DELETE FROM {uc_product_class_choices} WHERE cfid = %d", $form_values['cfid']);
  db_query("DELETE FROM {uc_class_choices} WHERE cfid = %d", $form_values['cfid']);
  db_query("DELETE FROM {uc_class_fields} WHERE cfid = %d", $form_values['cfid']);
  
  module_invoke_all('product_class', 'field', 'delete', $form_values['cfid']);
  
  drupal_set_message(t('Product class field deleted.'));
}

/******************************************************************************
 * Module Functions                                                           *
 ******************************************************************************/

/**
 * Format a product node.
 *
 * @ingroup themeable
 */
function theme_uc_product($node, $teaser){
  $output = '';
  $defaults = variable_get('uc_product_default_fields', array(
    'model' => 'model',
    'display_price' => 'display_price',
    'sell_price' => 'sell_price',
    'weight' => 'weight',
  ));
  $output .= '<div class="uc_product_view">';
  if ($defaults['image']){
    if (isset($node->images['_original']) && $node->images['_original'] != ''){
      $output .= theme('uc_product_image', $node->images, true);
    }
/*    else{
      $output .= '<div class="no_image">No image to display.</div>';
    } */
  }
  if ($defaults['display_price']){
    $output .= theme('uc_product_display_price', $node->sell_price);
  }
  if (!$teaser){
    if ($defaults['model']){
      $output .= theme('uc_product_model', $node->model);
    }
    $output .= '<div>'. $node->body .'</div>';
    if ($defaults['list_price']){
      $output .= theme('uc_product_price', $node->list_price, 'list_price');
    }
    if ($defaults['cost'] && user_access('administer products')){
      $output .= theme('uc_product_price', $node->cost, 'cost');
    }
  }
  if ($defaults['sell_price']){
    $output .= theme('uc_product_sell_price', $node->sell_price, $teaser);
  }
  if (!$teaser){
    if ($defaults['weight']){
      $output .= theme('uc_product_weight', $node->weight);
    }
    $output .= theme('uc_product_class', $node);
    $output .= theme('uc_product_add_to_cart', $node->nid, $defaults['sell_price']);
  }
  $output .= '</div>';
  return $output;
}

/**
 * Format a product's model number.
 *
 * @ingroup themeable
 */
function theme_uc_product_model($model){
  $output = '<div class="model">';
  $output .= t('!m', array('!m' => $model));
  $output .= '</div>';
  return $output;
}

/**
 * Wrap the "Add to Cart" form in a <div>.
 *
 * @ingroup themeable
 */
function theme_uc_product_add_to_cart($node){
  $output = '<div class="add_to_cart">';
  $output .= drupal_get_form('uc_product_add_to_cart_form_'. $node->nid, $node);
  $output .= '</div>';
  return $output;
}

function uc_product_add_to_cart_form($node){
  $form = array();
  $form['#base'] = 'uc_product_add_to_cart_form';
  $form['nid'] = array('#type' => 'value', '#value' => $node->nid);
  $form['submit'] = array('#type' => 'submit', '#value' =>  t('Add to cart'), );
  return $form;
}

function uc_product_add_to_cart_form_submit($form_id, $form_values){
  return uc_cart_add_item($form_values['nid'], 1,  module_invoke_all('add_to_cart_data', $form_values));
}

/**
 * Format a product's price.
 *
 * @param $price
 *   The amount to print.
 * @param $class
 *   Determines the label and the CSS class of the <div>.
 * @ingroup themeable
 */
function theme_uc_product_price($price, $class){
  $label = preg_replace(array('/_/', '/\b(\w)/e'), array(' ', 'drupal_strtoupper($1)'), $class);
  $output = '<div class="'. $class .'">';
  $output .= t('@label: !price', array('@label' => $label, '!price' => uc_currency_format($price)));
  $output .= '</div>';
  return $output;
}

/**
 * Format the selling price based on the view mode.
 *
 * @param $price
 *   The price amount.
 * @param $teaser
 *   Passed from uc_product_view().
 * @ingroup themeable
 */
function theme_uc_product_sell_price($price, $teaser){
  if ($teaser){
    $output = '<span class="sell_price">';
    $output .= t('!price', array('!price' => uc_currency_format($price)));
    $output .= '</span>';
  }
  else{
    $output = '<div class="sell_price">';
    $output .= t('Price: !price', array('!price' => uc_currency_format($price)));
    $output .= '</div>';
  }
  return $output;
}

/**
 * Format a product's weight.
 *
 * @ingroup themeable
 */
function theme_uc_product_weight($weight, $unit = null){
  $output = '<div class="weight">';
  $output .= t('Weight: !weight', array('!weight' => uc_weight_format($weight, $unit)));
  $output .= '</div>';
  return $output;
}

/**
 * @ingroup themeable
 */
function theme_uc_product_image($images){
  $first = array_shift($images);
  $output = '<div class="product_image">';
  $output .= '<a href="'. check_url(file_create_url($first['filepath'])) .'" class="thickbox" rel="field_image_cache">';
  $output .= theme('imagecache', 'product', $first['filepath']);
  /* if (count($images)){
    $output .= '<br />'. t('Click for more images.');
  } */
  $output .= '</a><br />';
  foreach ($images as $thumbnail){
    $output .= '<a href="'. check_url(file_create_url($thumbnail['filepath'])) .'" class="thickbox" rel="field_image_cache">';
    $output .= theme('imagecache', 'thumbnail', $thumbnail['filepath']);
    $output .= '</a>';
  }
  $output .= '</div>';
  return $output;
}

/**
 * @ingroup themeable
 */
function theme_uc_product_display_price($price){
  $output = '<div class="display_price">';
  $output .= uc_currency_format($price);
  $output .= '</div>';
  return $output;
}

/**
 * @ingroup themeable
 */
function theme_uc_product_class($node){
  $output = '';
//  if (module_exists('taxonomy')) { $node->links = taxonomy_link('taxonomy terms', $node); }
//  print_r($node);
  $class = uc_product_class_load($node->pcid);
  if ($class){
    $p_fields = $node->fields;
    $c_fields = $class->fields;
    //$node->content['c_fields'] = array('#value' => '<pre>'. print_r($c_fields, true) .'</pre>');
    //$node->content['p_fields'] = array('#value' => '<pre>'. print_r($p_fields, true) .'</pre>');
    if (is_array($c_fields) && is_array($p_fields)){
      $output .= '<div class="class_fields">';
      foreach($c_fields as $cfid => $field_info){
        $label = $field_info['name'];
        $value = '';
        if (is_array($p_fields[$cfid])){
          foreach ($p_fields[$cfid] as $ccid){
            $value .= $field_info['choices'][$ccid] .', ';
          }
          $value = rtrim($value, ', ');
        }
        else if (isset($field_info['choices'][$p_fields[$cfid]])){
          $value = $field_info['choices'][$p_fields[$cfid]];
        }
        else{
          $value = $p_fields[$cfid];
        }
        $output .= theme('uc_product_class_field', $label, $value);
      }
      $output .= '</div>';
    }
  }
  return $output;
}

/**
 * Format a product's class's field.
 *
 * @ingroup themeable
 */
function theme_uc_product_class_field($label, $value){
  $output = '<div class="class_field">';
  $output .= t('@label: @value', array('@label' => $label, '@value' => $value));
  $output .= '</div>';
  return $output;
}

/**
 * Get the cost of a product node.
 *
 * @param $node_id
 *   nid of the selected node
 * @return
 *   float - cost
 */
function uc_product_get_cost($node_id){
  $product = node_load($node_id);
  return $product->cost;
}

/**
 * Get the selling price of a product node.
 *
 * @param $node_id
 *   nid of the selected node
 * @return
 *   float - sell price
 */
/* function uc_product_get_price($node_id){
  $product = node_load($node_id);
  return $product->sell_price;
} */

/**
 * Returns an HTML img tag based on a node's attached image.
 *
 * @param $node_id
 *   The node's id.
 * @param $format
 *   By default, 'thumbnail', with possible values of '_original', 'thumbnail', and 'preview'.
 * @return
 *   An HTML img. When $format is 'thumbnail', the image is a link to the node.
 *   When $format is 'preview', the image is a link to the image file.
 */
function uc_product_get_picture($node_id, $format = 'product'){
  $img = '';
  $product = node_load($node_id);
  if (!module_exists('imagecache')){
    return '';
  }
  $path = $product->field_image_cache[0]['filepath'];
  if (file_exists($path)){
    $img = theme('imagecache', $format, $path);
    if ($format == 'product'){
      $img = '<a href="'. check_url(file_create_url($path)) .'" class="thickbox" rel="field_image_cache">'. $img .'</a>';
    }
    else{
      $img = l($img, 'node/'. $product->nid, array(), null, null, false, true);
    }
  }  
  return $img;
}

/**
 * Implementation of hook_load().
 */
function uc_product_class_load($class_id){
  static $classes = array();
  
  if (empty($classes[$class_id])){
    $result = db_query("SELECT * FROM {uc_product_classes} WHERE pcid = %d", $class_id);
    $class = db_fetch_object($result);
    $class->fields = array();
    $field_result = db_query("SELECT * FROM {uc_class_fields} WHERE pcid = %d", $class_id);
    while ($field = db_fetch_object($field_result)){
      $class->fields[$field->cfid] = array(
        //'title' => $field->title,
        'name' => $field->name,
        'type' => $field->type,
      );
      $choices = array();
      $choice_result = db_query("SELECT * FROM {uc_class_choices} WHERE cfid = %d", $field->cfid);
      while ($choice = db_fetch_object($choice_result)){
        $choices[$choice->ccid] = $choice->name;
      }
      $class->fields[$field->cfid]['choices'] = $choices;
    }
    $classes[$class_id] = $class;
  }
  
  return $classes[$class_id];
}

/**
 * Displays the fields that accept user input about class-specific information.
 * 
 * This function is called when a product class is selected on the product edit page.
 */
function _uc_product_class_fields_render($class_id, $nid = null){
  if ($nid){
    $node = node_load($nid);
    $p_fields = $node->fields;
    //print 'Product Fields:<pre>'. print_r($p_fields, true) .'</pre>';
  }
  $class = uc_product_class_load($class_id);
  $fields = array();
  foreach($class->fields as $cfid => $field){
    $f = array(
      '#title' => $field['name'],
      '#name' => 'ucpc_'. $cfid,
      '#type' => $field['type'],
      '#parents' => array('c_fields'),
      '#id' => 'edit-ucpc-'. $cfid,
      '#options' => $field['choices'],
    );
    if (is_array($p_fields)){
      $f['#value'] = $p_fields[$cfid];
      // $f['#default_value'] = $p_fields[$cfid];
    }
    if ($f['#type'] == 'checkboxes'){
      $f = expand_checkboxes($f);
    }
    if ($f['#type'] == 'radios'){
      $f = expand_radios($f);
    }
    if ($f['#type'] == 'date'){
      $f = expand_date($f);
    }
    foreach (element_children($f) as $element){
      $f[$element]['#parents'] = array($f['#name']);
      $f[$element]['#name'] = $f['#name'] . ($f[$element]['#type'] == 'checkbox' ? '[]' : '');
      if (is_array($f['#value']) && in_array($element, $f['#value'])){
        $f[$element]['#value'] = 1;
      }
      elseif ($element == $f['#value']){
        $f[$element]['#attributes'] = array('checked' => 'checked');
      }
    }
//    print '<pre>'. print_r($fields[$cfid], true) .'</pre>';
    print drupal_render($f);
  }
}

function _uc_product_get_image_field_filepath($nid){
  $result = db_result(db_query("SELECT filepath FROM {files} WHERE nid = %d ORDER BY fid LIMIT 1", $nid));
  if ($result){
    print $result;
  }
  else{
    print 'false';
  }
  exit();
}

function uc_product_get_product_types(){
  $types = array();
  foreach (module_invoke_all('product_info') as $type => $product_type){
    $types[] = $type;
  }
  return $types;
}
