<?php
// $Id$

/**
 * @file
 * Defines the payment API that lets payment modules interact with Ubercart.
 *
 * The payment system in Ubercart relies on hooks to let the main program know
 * what payment modules are installed and what their current settings are.  The
 * customer can choose a payment type at checkout, and the proper information
 * will be collected to complete the purchase.
 *
 * Development sponsored by the Ubercart project.  http://www.ubercart.org
 */

require_once('uc_payment_checkout_pane.inc');
require_once('uc_payment_order_pane.inc');
require_once('uc_payment.ca.inc');

/*******************************************************************************
 * Hook Functions (Drupal)
 ******************************************************************************/

/**
 * Implementation of hook_menu().
 */
function uc_payment_menu() {
  $items['admin/store/settings/payment'] = array(
    'title' => 'Payment settings',
    'description' => 'Configure the payment settings.',
    'page callback' => 'uc_payment_settings_overview',
    'access arguments' => array('administer store'),
  );
  $items['admin/store/settings/payment/overview'] = array(
    'title' => 'Overview',
    'description' => 'View the payment settings.',
    'access arguments' => array('administer store'),
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/store/settings/payment/edit'] = array(
    'title' => 'Edit',
    'description' => t('Edit the payment settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_payment_settings_form'),
    'access arguments' => array('administer store'),
    'weight' => -5,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/store/settings/payment/edit/basic'] = array(
    'title' => 'Payment settings',
    'description' => 'Edit the basic payment settings.',
    'access arguments' => array('administer store'),
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/store/settings/payment/edit/methods'] = array(
    'title' => 'Payment methods',
    'description' => 'Edit the payment method settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_payment_methods_form'),
    'access arguments' => array('administer store'),
    'weight' => -5,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/store/settings/payment/edit/gateways'] = array(
    'title' => 'Payment gateways',
    'description' => 'Edit the payment gateway settings.',
    'access arguments' => array('administer store'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_payment_gateways_form'),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
  );

  $items['cart/checkout/line_items'] = array(
    'title' => 'Return order totals',
    'page callback' => 'uc_payment_get_totals',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['cart/checkout/payment_details/%'] = array(
    'title' => 'Payment details',
    'description' => 'Add the payment details to the checkout pane.',
    'page callback' => 'uc_payment_get_details',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/store/orders/%uc_order/payment_details/%'] = array(
    'title' => 'Payment details',
    'description' => 'Add the payment details to the order pane.',
    'page callback' => 'uc_payment_get_details',
    'page arguments' => array(5, 'order', 3),
    'access arguments' => array('edit orders'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/store/orders/%uc_order/payments/select/%'] = array(
    'title' => 'Select payment gateway',
    'page callback' => 'uc_payment_gateway_select',
    'access arguments' => array('view all orders'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/store/orders/%uc_order/payments'] = array(
    'title' => 'Payments',
    'page callback' => 'uc_payment_by_order',
    'page arguments' => array(3),
    'access callback' => 'uc_payment_tracking_access',
    'weight' => 5,
    'type' => MENU_LOCAL_TASK
  );
  $items['admin/store/orders/%uc_order/payments/%uc_payment/delete'] = array(
    'title' => 'Delete payment?',
    'description' => 'Delete payment?',
    'page callback' => 'uc_payment_delete_confirm',
    'page arguments' => array(3, 5),
    'access callback' => 'uc_payment_delete_access',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_token_values().
 */
function uc_payment_token_values($type, $object = NULL) {
  switch ($type) {
    case 'order':
      $order = $object;
      $values['order-payment-method'] = _payment_method_data($order->payment_method, 'review');
      if (empty($values['order-payment-method'])) {
        $values['order-payment-method'] = _payment_method_data($order->payment_method, 'name');
      }
      $values['order-payment-balance'] = uc_currency_format(uc_payment_balance($order));
      break;
  }

  return $values;
}

/**
 * Implementation of hook_token_list(). (token.module)
 */
function uc_payment_token_list($type = 'all') {
  if ($type == 'order' || $type == 'ubercart' || $type == 'all') {
    $tokens['order']['order-payment-method'] = t('The payment method of the order.');
    $tokens['order']['order-payment-balance'] = t('The payment balance of the order');
  }

  return $tokens;
}

/**
 * Implementation of hook_perm().
 */
function uc_payment_perm() {
  return array('view payments', 'manual payments', 'delete payments');
}

/**
 * Access callback to view list of payments.
 */
function uc_payment_tracking_access() {
  return user_access('view payments') && variable_get('uc_payment_tracking', TRUE);
}

/**
 * Access callback to delete a payment.
 */
function uc_payment_delete_access() {
  return user_access('delete payments') && variable_get('uc_payment_deleting', TRUE);
}

/**
 * Implementation of hook_theme().
 */
function uc_payment_theme() {
  return array(
    'uc_payment_method_table' => array(
      'arguments' => array('form' => NULL),
    ),
    'uc_payment_by_order_form' => array(
      'arguments' => array('form' => NULL),
    ),
    'uc_payment_method_select' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * Implementation of hook_form_alter().
 */
function uc_payment_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'uc_cart_checkout_form') {
    uc_add_js('misc/progress.js');
    uc_add_js(drupal_get_path('module', 'uc_payment') .'/uc_payment.js');
  }
}


/*******************************************************************************
 * Hook Functions (TAPIr)
 ******************************************************************************/

/**
 * Implementation of hook_table_settings().
 */
function uc_payment_table_settings() {
  $tables[] = array(
    'id' => 'uc_payments_table',
    'description' => t('The payments table on the order payments screen.'),
    'path' => 'admin/store/settings/tables',
    'access' => 'view all orders',
    'preview' => FALSE,
  );

  return $tables;
}


/*******************************************************************************
 * Hook Functions (Ubercart)
 ******************************************************************************/

/**
 * Implementation of hook_order().
 */
function uc_payment_order($op, &$arg1) {
  switch ($op) {
    case 'submit':
      $func = _payment_method_data($arg1->payment_method, 'callback');
      if (function_exists($func)) {
        return $func('order-submit', $arg1);
      }
      break;

    case 'load':
      $func = _payment_method_data($arg1->payment_method, 'callback');
      if (function_exists($func)) {
        $func('order-load', $arg1);
      }
      break;

    case 'save':
      $func = _payment_method_data($arg1->payment_method, 'callback');
      if (function_exists($func)) {
        $func('order-save', $arg1);
      }
      break;

    case 'can_delete':
      if (uc_payment_load_payments($arg1->order_id) !== FALSE) {
        return FALSE;
      }

    case 'delete':
      db_query("DELETE FROM {uc_payment_receipts} WHERE order_id = %d", $arg1->order_id);
      // Call each payment method to delete method specific data from the database.
      $methods = _payment_method_list();
      foreach ($methods as $method) {
        $func = $method['callback'];
        if (function_exists($func)) {
          $func('order-delete', $arg1);
        }
      }
      break;
  }
}

/**
 * Implementation of hook_checkout_pane().
 */
function uc_payment_checkout_pane() {
  $panes[] = array(
    'id' => 'payment',
    'title' => t('Payment method'),
    'desc' => t('Select a payment method from the enabled payment modules.'),
    'callback' => 'uc_checkout_pane_payment',
    'weight' => 6,
  );

  return $panes;
}

/**
 * Implementation of hook_order_pane().
 */
function uc_payment_order_pane() {
  $panes[] = array(
    'id' => 'payment',
    'callback' => 'uc_order_pane_payment',
    'title' => t('Payment'),
    'desc' => t('Specify and collect payment for an order.'),
    'class' => 'pos-left',
    'weight' => 4,
    'show' => array('view', 'edit', 'customer'), //, 'invoice', 'customer'),
  );

  return $panes;
}

/**
 * Implementation of hook_order_state().
 */
function uc_payment_order_state() {
  $states[] = array(
    'id' => 'payment_received',
    'title' => t('Payment received'),
    'weight' => 10,
    'scope' => 'general',
  );

  return $states;
}


/*******************************************************************************
 * Callback Functions, Forms, and Tables
 ******************************************************************************/

/**
 * Display the payment settings overview.
 */
function uc_payment_settings_overview() {
  $sections[] = array(
    'edit' => 'admin/store/settings/payment/edit',
    'title' => t('Payment settings'),
    'items' => array(
      t('Payment tracking is !status.', array('!status' => variable_get('uc_payment_tracking', TRUE) ? t('enabled') : t('disabled'))),
      t('Payments !status be deleted by approved users.', array('!status' => variable_get('uc_payment_deleting', TRUE) ? t('may') : t('may not'))),
      t('Payments are !status in the order logs.', array('!status' => variable_get('uc_payment_logging', TRUE) ? t('tracked') : t('not tracked'))),
      t('Default payment details message:<br/>%message', array('%message' => variable_get('uc_default_payment_msg', t('Continue with checkout to complete payment.')))),
    ),
  );

  $methods = _payment_method_list();
  foreach ($methods as $method) {
    $items[] = t('!title is !status for checkout.', array('!title' => $method['name'], '!status' => $method['checkout'] ? t('enabled') : t('disabled')));
  }
  $sections[] = array(
    'edit' => 'admin/store/settings/payment/edit/methods',
    'title' => t('Payment methods'),
    'items' => $items,
  );

  $items = array();
  $gateways = _payment_gateway_list();
  foreach ($gateways as $gateway) {
    $items[] = t('!title is !status.', array('!title' => $gateway['title'], '!status' => $gateway['enabled'] ? t('enabled') : t('disabled')));
  }
  $sections[] = array(
    'edit' => 'admin/store/settings/payment/edit/gateways',
    'title' => t('Payment gateways'),
    'items' => $items,
  );

  $output = theme('uc_settings_overview', $sections);

  return $output;
}

function uc_payment_settings_form() {
  $form['uc_payment_tracking'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable payment tracking.'),
    '#default_value' => variable_get('uc_payment_tracking', TRUE),
  );
  $form['uc_payment_deleting'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow payments to be deleted by users with permission.'),
    '#default_value' => variable_get('uc_payment_deleting', TRUE),
  );
  $form['uc_payment_logging'] = array(
    '#type' => 'checkbox',
    '#title' => t('Log payments entered and deleted to order log.'),
    '#default_value' => variable_get('uc_payment_logging', TRUE),
  );

  $form['uc_default_payment_msg'] = array(
    '#type' => 'textfield',
    '#title' => t('Default payment details message'),
    '#description' => t('Message displayed when a payment method does not display any further details.'),
    '#default_value' => variable_get('uc_default_payment_msg', t('Continue with checkout to complete payment.')),
  );

  return system_settings_form($form);
}

function uc_payment_methods_form() {
  $methods = _payment_method_list();

  $form['methods_info'] = array(
    '#value' => '<div><strong>'. t('Payment methods') .'</strong><br />'
              . t('The settings forms below are for the payment methods defined by enabled modules. Click a name to expand its options and adjust the settings accordingly. Methods are listed in order of appearance on the checkout screen, determined by the weight setting (current value shown in parentheses).') .'</div><br />',
  );

  $form['pmtable'] = array('#theme' => 'uc_payment_method_table');

  if (is_array($methods) && count($methods) > 0) {
    foreach ($methods as $method) {
      $form['pmtable'][$method['id']]['uc_payment_method_'. $method['id'] .'_checkout'] = array(
        '#type' => 'checkbox',
        '#default_value' => variable_get('uc_payment_method_'. $method['id'] .'_checkout', $method['checkout']),
      );
      $form['pmtable'][$method['id']]['name'] = array(
        '#value' => $method['name'],
      );
      $form['pmtable'][$method['id']]['uc_payment_method_'. $method['id'] .'_weight'] = array(
        '#type' => 'weight',
        '#default_value' => variable_get('uc_payment_method_'. $method['id'] .'_weight', $method['weight']),
      );

      if ($method['no_gateway'] === TRUE) {
        $form['pmtable'][$method['id']]['uc_payment_'. $method['id'] .'_gateway'] = array(
          '#value' => '-',
        );
      }
      else {
        $gateways = _payment_gateway_list($method['id'], TRUE);
        $options = array();
        $default = FALSE;
        if (is_array($gateways)) {
          foreach ($gateways as $gateway) {
            if (!$default) {
              $default = $gateway['id'];
            }
            $options[$gateway['id']] = $gateway['title'];
          }
        }
        if (!$default) {
          $options = array('none' => t('None available.'));
        }
        $form['pmtable'][$method['id']]['uc_payment_'. $method['id'] .'_gateway'] = array(
          '#type' => 'select',
          '#options' => $options,
          '#default_value' => variable_get('uc_payment_'. $method['id'] .'_gateway', 'none'),
        );
      }

      $null = NULL;
      $method_settings = $method['callback']('settings', $null);
      if (is_array($method_settings)) {
        $form['method_'. $method['id']] = array(
          '#type' => 'fieldset',
          '#title' => t('!method settings', array('!method' => $method['name'], '!weight' => $method['weight'])),
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
        );
        $form['method_'. $method['id']] = array_merge($form['method_'. $method['id']], $method_settings);
      }
    }
  }

  return system_settings_form($form);
}

function theme_uc_payment_method_table($form) {
  $header = array(t('Enabled'), t('Payment method'), t('Weight'), t('Default gateway'));

  foreach (element_children($form) as $method) {
    $rows[] = array(
      array('data' => drupal_render($form[$method]['uc_payment_method_'. $method .'_checkout']), 'align' => 'center'),
      drupal_render($form[$method]['name']),
      drupal_render($form[$method]['uc_payment_method_'. $method .'_weight']),
      drupal_render($form[$method]['uc_payment_'. $method .'_gateway']),
    );
  }

  if (empty($rows)) {
    $rows[] = array(
      array('data' => t('No payment methods founds.'), 'colspan' => 5),
    );
  }

  return theme('table', $header, $rows);
}

function uc_payment_gateways_form() {
  $gateways = _payment_gateway_list();
  $methods = _payment_method_list();

  if (is_array($gateways) && count($gateways) > 0) {
    $form['gateways_info'] = array(
      '#value' => '<div><strong>'. t('Payment gateways') .'</strong><br />'
                . t('Payment gateways are web services that allow you to process various types of payments remotely.  The settings forms below are for the payment gateways you have installed.  Click a name to expand its options and adjust the settings accordingly.') .'</div>',
    );
    foreach ($gateways as $gateway) {
      $prefix = 'uc_pg_'. $gateway['id'];
      $form[$prefix] = array(
        '#type' => 'fieldset',
        '#title' => t('!gateway_name settings', array('!gateway_name' => $gateway['title'])),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      $supported_methods = array();
      foreach ($methods as $method) {
        if (isset($gateway[$method['id']]) && function_exists($gateway[$method['id']])) {
          $supported_methods[] = $method['name'];
        }
      }
      $form[$prefix]['supported_methods'] = array(
        '#value' => '<div>'. t('This gateway supports the following payment methods:')
                   .'<br />'. implode(',', $supported_methods) .'</div>',
      );
      $form[$prefix][$prefix .'_enabled'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable this payment gateway for use.'),
        '#default_value' => variable_get($prefix .'_enabled', TRUE),
      );
      if (function_exists($gateway['settings'])) {
        $gateway_settings = $gateway['settings']();
        if (is_array($gateway_settings)) {
          $form[$prefix] = array_merge($form[$prefix], $gateway_settings);
        }
      }
    }
  }

  return system_settings_form($form);
}

function uc_payment_get_details($method_id, $view = 'cart', $order = NULL) {
  if ($view == 'cart') {
    if (!($order = uc_order_load($_SESSION['cart_order']))) {
      $_SESSION['cart_order'] = NULL;
      $order = NULL;
    }

    if ($order->order_status != 0 || ($user->uid && $user->uid != $order->uid)) {
      $order = NULL;
    }
  }

  $func = _payment_method_data($method_id, 'callback');
  if (function_exists($func)) {
    $output = $func($view .'-details', $order);
  }

  print $output;
  exit();
}

function uc_payment_get_totals() {
  if (is_array($_POST)) {
    foreach ($_POST as $key => $value) {
      $totals[$key] = explode(';', $value);
    }
  }

  if (is_array($totals) && count($totals) > 0) {
    usort($totals, '_total_sort');

    $output = t('Order total preview:')
             .' <span id="order-total-throbber"></span><table>';
    $grand_total = 0;

    foreach ($totals as $line) {
      if (!empty($line[2])) {
        $output .= '<tr><td align="right"><b>'. $line[2] .':</b></td>'
                  .'<td align="right">'. uc_currency_format($line[1]) .'</td></tr>';
        if ($line[3]) {
          $grand_total += round($line[1], 2);
        }
      }
    }

    $output .= '<tr><td align="right"><b>'. t('Order total:') .'</b></td>'
              .'<td align="right">'. uc_currency_format($grand_total)
              .'</td></tr></table>';
  }

  print $output;
  exit();
}

function _total_sort($a, $b) {
  if ($a[0] == $b[0]) {
       return 0;
   }

  return ($a[0] < $b[0]) ? -1 : 1;
}

/**
 * View a list of payments attached to an order.
 */
function uc_payment_by_order($order) {
  $output = '<p>'. drupal_get_form('uc_payment_by_order_form', $order) .'</p>';
  return $output;
}

function uc_payment_by_order_form($form_state, $order) {
  $total = $order->order_total;
  $payments = uc_payment_load_payments($order->order_id);

  $form['order_total'] = array('#value' => uc_currency_format($total));
  $form['payments'] = array('#tree' => TRUE);
  if ($payments !== FALSE) {
    foreach ($payments as $payment) {
      $form['payments'][$payment->receipt_id]['received'] = array(
        '#value' => format_date($payment->received, 'custom', variable_get('uc_date_format_default', 'm/d/Y') .'<b\r>H:i:s'),
      );
      $form['payments'][$payment->receipt_id]['user'] = array(
        '#value' => uc_get_initials($payment->uid),
      );
      $form['payments'][$payment->receipt_id]['method'] = array(
        '#value' => ($payment->method == '') ? t('Unknown') : $payment->method,
      );
      $form['payments'][$payment->receipt_id]['amount'] = array(
        '#value' => uc_currency_format($payment->amount),
      );
      $total -= $payment->amount;
      $form['payments'][$payment->receipt_id]['balance'] = array(
        '#value' => uc_currency_format($total),
      );
      $form['payments'][$payment->receipt_id]['comment'] = array(
        '#value' => ($payment->comment == '') ? '-' : filter_xss_admin($payment->comment),
      );
      if (variable_get('uc_payment_deleting', TRUE) && user_access('delete payments')) {
        $action_value = l(t('Delete'), 'admin/store/orders/'. $order->order_id .'/payments/'
                          . $payment->receipt_id .'/delete');
      }
      else {
        $action_value = '-';
      }
      $form['payments'][$payment->receipt_id]['action'] = array(
        '#value' => $action_value,
      );
    }
  }
  $form['balance'] = array('#value' => uc_currency_format($total));
  $form['order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order->order_id,
  );

  if (user_access('manual payments')) {
    $form['payments']['new']['received'] = array(
      '#value' => '-',
    );
    $form['payments']['new']['user'] = array(
      '#value' => '-',
    );
    $methods = _payment_method_list();
    foreach ($methods as $method) {
      $options[$method['id']] = $method['name'];
    }
    $form['payments']['new']['method'] = array(
      '#type' => 'select',
      '#options' => $options,
    );
    $form['payments']['new']['amount'] = array(
      '#type' => 'textfield',
      '#size' => 6,
    );
    $form['payments']['new']['balance'] = array(
      '#value' => '-',
    );
    $form['payments']['new']['comment'] = array(
      '#type' => 'textfield',
      '#size' => 32,
      '#maxlength' => 256,
    );
    $form['payments']['new']['action'] = array(
      '#type' => 'submit',
      '#value' => t('Enter'),
    );
  }

  return $form;
}

function theme_uc_payment_by_order_form($form) {
  $output = '<p><strong>'. t('Order total:') .'</strong> '. drupal_render($form['order_total'])
           .'<br /><strong>'. t('Current balance:') .'</strong> '
          . drupal_render($form['balance']) .'</p>';
  $output .= '<p>'. tapir_get_table('uc_payments_table', $form) .'</p>'
           . '<p>'. drupal_render($form['form_id'])
           . drupal_render($form['form_token']) .'</p>';
  return $output;
}

function uc_payment_by_order_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['payments']['new']['amount'])) {
    form_set_error('payments][new][amount', t('You must enter a number for the amount.'));
  }
  return TRUE;
}

function uc_payment_by_order_form_submit($form, &$form_state) {
  global $user;

  $payment = $form_state['values']['payments']['new'];
  uc_payment_enter($form_state['values']['order_id'], $payment['method'], $payment['amount'],
                   $user->uid, '', $payment['comment']);

  drupal_set_message(t('Payment entered.'));
}

function uc_payments_table($form_state, $cells) {
  $table = array();

  $fields[] = array(
    'id' => 'received',
    'cell' => t('Received'),
    'weight' => 0,
  );
  $fields[] = array(
    'id' => 'user',
    'cell' => t('User'),
    'weight' => 1,
  );
  $fields[] = array(
    'id' => 'method',
    'cell' => t('Method'),
    'weight' => 2,
  );
  $fields[] = array(
    'id' => 'amount',
    'cell' => t('Amount'),
    'weight' => 3,
  );
  $fields[] = array(
    'id' => 'balance',
    'cell' => t('Balance'),
    'weight' => 4,
  );
  $fields[] = array(
    'id' => 'comment',
    'cell' => t('Comment'),
    'weight' => 5,
  );
  $fields[] = array(
    'id' => 'action',
    'cell' => t('Action'),
    'weight' => 6,
  );
  $table['columns'] = $fields;

  foreach (element_children($cells['payments']) as $i) {
    $data = array();
    $data['received']['cell'] = drupal_render($cells['payments'][$i]['received']);
    $data['user']['cell'] = drupal_render($cells['payments'][$i]['user']);
    $data['method']['cell'] = drupal_render($cells['payments'][$i]['method']);
    $data['amount']['cell'] = drupal_render($cells['payments'][$i]['amount']);
    $data['balance']['cell'] = drupal_render($cells['payments'][$i]['balance']);
    $data['comment']['cell'] = drupal_render($cells['payments'][$i]['comment']);
    $data['action']['cell'] = drupal_render($cells['payments'][$i]['action']);
    $table['rows'][] = $data;
  }

  $form['table'] = array(
    '#value' => $table,
    '#theme' => 'tapir_table',
  );

  return $form;
}

/**
 * Delete a payment from an order.
 */
function uc_payment_delete_confirm($order, $payment) {
  if ($payment->order_id != $order->order_id) {
    drupal_set_message(t('An error loading the payment information occurred.'));
    drupal_goto('admin/store/orders/'. $order->order_id .'/payments');
  }

  $output = '<p><strong>'. t('Payment information:') .'</strong><br />'
          . t('!method payment of !amount received on !date.',
              array('!method' => $payment->method,
                    '!amount' => uc_currency_format($payment->amount),
                    '!date' => format_date($payment->received, 'custom', variable_get('uc_date_format_default', 'm/d/Y')))) .'</p>';
  $output .= t('Are you sure you want to delete this payment?') .'<p>'
           . drupal_get_form('uc_payment_delete_confirm_form', $order->order_id, $payment->receipt_id);

  return $output;
}

function uc_payment_delete_confirm_form($form_state, $order_id, $receipt_id) {
  $form['order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order_id
  );
  $form['receipt_id'] = array(
    '#type' => 'hidden',
    '#value' => $receipt_id,
  );
  $form['cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
  );
  $form['delete'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
  );

  return $form;
}

function uc_payment_delete_confirm_form_submit($form, &$form_state) {
  if ($form_state['values']['op'] == t('Delete')) {
    uc_payment_delete($form_state['values']['receipt_id']);
    drupal_set_message(t('Payment deleted.'));
  }
  $form_state['redirect'] = 'admin/store/orders/'. $form_state['values']['order_id'] .'/payments';
}

/**
 * Select a payment gateway to process a payment when multiple gateways
 * exist for a given payment method.
 */
function uc_payment_gateway_select() {
  $gateways = _payment_gateway_list($_SESSION['uc_payment_method'], TRUE);
  foreach ($gateways as $gateway) {
    $options[$gateway['id']] = $gateway['title'];
  }

  $output = t('Please choose a payment gateway to use for that payment.');

  $output .= drupal_get_form('uc_payment_gateway_select_form', $options,
               $_SESSION['uc_payment_method'], $_SESSION['uc_payment_order_id'],
               $_SESSION['uc_payment_amount'], $_SESSION['uc_payment_data']);

  return $output;
}

function uc_payment_gateway_select_form($form_state, $options, $method, $order_id, $amount, $data) {
  $form['method'] = array(
    '#type' => 'hidden',
    '#value' => $method,
  );
  $form['order_id'] = array(
    '#type' => 'hidden',
    '#value' => $order_id,
  );
  $form['amount'] = array(
    '#type' => 'hidden',
    '#value' => $amount,
  );
  $form['p_data'] = array(
    '#type' => 'hidden',
    '#value' => $data,
  );
  $form['p_selected'] = array(
    '#type' => 'select',
    '#title' => t('Use gateway'),
    '#options' => $options,
    '#default_value' => variable_get('uc_payment_'. $method .'_gateway', ''),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Process'),
  );

  return $form;
}

function uc_payment_gateway_select_form_submit($form, &$form_state) {
  unset($_SESSION['uc_payment_method']);
  unset($_SESSION['uc_payment_order_id']);
  unset($_SESSION['uc_payment_amount']);
  unset($_SESSION['uc_payment_data']);

  uc_payment_process($form_state['values']['method'], $form_state['values']['order_id'],
    $form_state['values']['amount'], unserialize($form_state['values']['p_data']), FALSE,
    $form_state['values']['p_selected']);

  $form_state['redirect'] = 'admin/store/orders/'. $form_state['values']['order_id'];
}

/*******************************************************************************
 * Module and Helper Functions
 ******************************************************************************/

/**
 * Process a payment through an enabled payment gateway.
 */
function uc_payment_process($method, $order_id, $amount, $data = NULL, $default = FALSE, $selected = NULL, $redirect = TRUE) {
  $gateways = _payment_gateway_list($method, TRUE);
  if (!is_array($gateways) || count($gateways) == 0) {
    if (!$default) {
      drupal_set_message(t('You are not able to process payments of type !type. ',
                           array('!type' => '<em>'. _payment_method_data($method, 'name') .'</em>')));
    }
    return FALSE;
  }
  if (count($gateways) == 1) {
    $keys = array_keys($gateways);
    if (function_exists($gateways[$keys[0]][$method])) {
      $result = $gateways[$keys[0]][$method]($order_id, $amount, $data);
    }
    else {
      if (user_access('administer store')) {
        drupal_set_message(t("Attempted to process payment but the gateway's function was not found."));
      }
    }
  }
  else {
    $func = FALSE;
    foreach ($gateways as $gateway) {
      if ($default && $gateway['id'] == variable_get('uc_payment_'. $method .'_gateway', '')) {
        $func = $gateway[$method];
      }
      if (!is_null($selected) && $gateway['id'] == $selected) {
        $func = $gateway[$method];
      }
    }
    if ($func !== FALSE) {
      if (function_exists($func)) {
        $result = $func($order_id, $amount, $data);
      }
      else {
        drupal_set_message(t('An error has occurred with your payment gateway.  The charge function could not be found.'));
        $result['success'] = FALSE;
      }
    }
    else {
      $_SESSION['uc_payment_method'] = $method;
      $_SESSION['uc_payment_order_id'] = $order_id;
      $_SESSION['uc_payment_amount'] = $amount;
      $_SESSION['uc_payment_data'] = serialize($data);

      drupal_goto('admin/store/orders/'. $order_id .'/payments/select/'. $method);
    }
  }

  if ($result['success'] === TRUE) {
    if (empty($result['uid'])) {
      $result['uid'] = 0;
    }
    uc_payment_enter($order_id, $method, $amount, $result['uid'], $result['data'], $result['comment']);
  }
  else {
    watchdog('uc_payment', 'Payment failed: !message', array('!message' => $result['message']), WATCHDOG_WARNING);
  }

  if (!empty($result['message']) && !$default) {
    drupal_set_message($result['message']);
  }

  if ($redirect) {
    drupal_goto('admin/store/orders/'. $order_id);
  }

  return $result['success'];
}

/**
 * Enter a payment for an order.
 */
function uc_payment_enter($order_id, $method, $amount, $uid, $data, $comment) {
  $method_name = _payment_method_data($method, 'review');
  if (empty($method_name)) {
    $method_name = _payment_method_data($method, 'name');
  }
  if (is_null($method_name)) {
    $method_name = t('Other');
  }
  if (is_array($data)) {
    $data = serialize($data);
  }

  if (variable_get('uc_payment_logging', TRUE)) {
    global $user;
    $log_message = t('!method payment for !amount entered by !user.',
                     array('!method' => $method_name,
                           '!amount' => uc_currency_format($amount),
                           '!user' => uc_get_initials($user->uid)));
    uc_order_log_changes($order_id, array($log_message));
  }

  db_query("INSERT INTO {uc_payment_receipts} (order_id, method, "
          ."amount, uid, data, comment, received) VALUES (%d, '%s', %f, "
          ."%d, '%s', '%s', %d)",
          $order_id, $method_name, $amount, $uid, $data, $comment, time());

  ca_pull_trigger('uc_payment_entered', uc_order_load($order_id));
}

/**
 * Delete a payment from the database.
 */
function uc_payment_delete($receipt_id) {
  if (!is_numeric($receipt_id)) {
    return FALSE;
  }

  if (variable_get('uc_payment_logging', TRUE)) {
    global $user;
    $payment = uc_payment_load($receipt_id);
    $log_message = t('!method payment for !amount deleted by !user.',
                     array('!method' => $payment->method,
                           '!amount' => uc_currency_format($payment->amount),
                           '!user' => uc_get_initials($user->uid)));
    uc_order_log_changes($payment->order_id, array($log_message));
  }

  db_query("DELETE FROM {uc_payment_receipts} WHERE receipt_id = %d", $receipt_id);
}

/**
 * Return the balance of payments on an order.
 */
function uc_payment_balance($order) {
  $total = $order->order_total;
  $payments = uc_payment_load_payments($order->order_id);

  if ($payments === FALSE) {
    return $total;
  }

  foreach ($payments as $payment) {
    $total -= $payment->amount;
  }

  return $total;
}

/**
 * Load a single payment from the database by receipt_id.
 */
function uc_payment_load($receipt_id) {
  if (!is_numeric($receipt_id)) {
    return FALSE;
  }

  $result = db_query("SELECT * FROM {uc_payment_receipts} WHERE receipt_id = %d ", $receipt_id);
  $payment = db_fetch_object($result);

  return $payment;
}

/**
 * Load an array of all the payments for order $order_id.
 */
function uc_payment_load_payments($order_id, $action = NULL) {
  $payments = array();

  $result = db_query("SELECT * FROM {uc_payment_receipts} WHERE order_id = %d "
                    ."ORDER BY received ASC", $order_id);
  while ($payment = db_fetch_object($result)) {
    $payments[] = $payment;
  }

  if (count($payments) == 0) {
    $payments = FALSE;
  }

  return $payments;
}

/**
 * Build a list of payment methods defined in the enabled modules.
 */
function _payment_method_list($action = NULL) {
  static $methods;

  if (count($methods) > 0 && $action !== 'rebuild') {
    return $methods;
  }

  $methods = module_invoke_all('payment_method');
  foreach ($methods as $i => $value) {
    $methods[$i]['checkout'] = variable_get('uc_payment_method_'. $methods[$i]['id'] .'_checkout', $methods[$i]['checkout']);
    $methods[$i]['weight'] = variable_get('uc_payment_method_'. $methods[$i]['id'] .'_weight', $methods[$i]['weight']);
  }
  usort($methods, 'uc_weight_sort');

  return $methods;
}

/**
 * Return data from a payment method by method ID and the array key.
 */
function _payment_method_data($method_id, $key) {
  $methods = _payment_method_list();
  foreach ($methods as $method) {
    if ($method['id'] == $method_id) {
      return $method[$key];
    }
  }
}

/**
 * Build a list of payment gateways defined in the enabled modules.
 */
function _payment_gateway_list($filter = NULL, $enabled_only = FALSE) {
  $gateways = module_invoke_all('payment_gateway');

  foreach ($gateways as $i => $value) {
    $gateways[$i]['enabled'] = variable_get('uc_pg_'. $gateways[$i]['id'] .'_enabled', TRUE);
    if ($filter != NULL) {
      if (!isset($gateways[$i][$filter]) || !function_exists($gateways[$i][$filter])) {
        unset($gateways[$i]);
      }
    }
    if ($enabled_only) {
      if (!variable_get('uc_pg_'. $gateways[$i]['id'] .'_enabled', TRUE)) {
        unset($gateways[$i]);
      }
    }
  }

  return $gateways;
}

/**
 * Return data from a payment gateway by gateway ID and the array key.
 */
function _payment_gateway_data($method_id, $key) {
  $gateways = _payment_gateway_list();
  foreach ($gateways as $gateway) {
    if ($gateway['id'] == $gateway_id) {
      return $gateway[$key];
    }
  }
}

