<?php
/**
 * @file
 * United States Postal Service (USPS) shipping quote module.
 */

/*******************************************************************************
 * Backdrop Hooks                                                              *
 ******************************************************************************/

/**
 * Implements hook_menu().
 */
function uc_usps_menu() {
  $items = array();

  $items['admin/store/settings/quotes/settings/usps'] = array(
    'title' => 'USPS',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_usps_admin_settings'),
    'access arguments' => array('configure quotes'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uc_usps.admin.inc',
  );

  if (module_exists('uc_reports')) {
    $items['admin/store/reports/usps-lookup'] = array(
      'title' => 'USPS lookup',
      'description' => 'Lookup function for USPS quotes',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('uc_usps_newapi_lookup_form'),
      'access arguments' => array('configure quotes'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'uc_usps.admin.inc',
    );
  }

  return $items;
}

/**
 * Implements hook_theme().
 */
function uc_usps_theme() {
  return array(
    'uc_usps_option_label' => array(
      'variables' => array(
        'service' => NULL,
        'packages' => NULL,
      ),
      'file' => 'uc_usps.theme.inc',
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * Adds package type to products.
 *
 * @see uc_product_form()
 */
function uc_usps_form_alter(&$form, &$form_state, $form_id) {
  if (uc_product_is_product_form($form, $form_state)) {
    $node = $form['#node'];
    $enabled = config_get('uc_quote.settings', 'uc_quote_enabled') + array(
      'usps' => FALSE,
      'usps_intl' => FALSE,
    );
    $weight = config_get('uc_quote.settings', 'uc_quote_method_weight') + array(
      'usps' => 0,
      'usps_intl' => 1,
    );

    $form['shipping']['usps'] = array(
      '#type' => 'fieldset',
      '#title' => t('USPS product description'),
      '#collapsible' => TRUE,
      '#collapsed' => ($enabled['usps'] == FALSE || uc_product_get_shipping_type($node) != 'small_package'),
      '#weight' => $weight['usps'],
      '#tree' => TRUE,
    );
    $form['shipping']['usps']['container'] = array(
      '#type' => 'select',
      '#title' => t('Package type'),
      '#options' => _uc_usps_pkg_types(),
      '#default_value' => isset($node->usps['container']) ? $node->usps['container'] : 'VARIABLE',
    );
  }
}

/**
 * Implements hook_node_insert().
 */
function uc_usps_node_insert($node) {
  uc_usps_node_update($node);
}

/**
 * Implements hook_node_update().
 */
function uc_usps_node_update($node) {
  if (uc_product_is_product($node->type)) {
    if (isset($node->usps)) {
      $usps_values = $node->usps;
      if (empty($node->revision)) {
        db_delete('uc_usps_products')
          ->condition('vid', $node->vid)
          ->execute();
      }

      db_insert('uc_usps_products')
        ->fields(array(
          'vid' => $node->vid,
          'nid' => $node->nid,
          'container' => $usps_values['container'],
        ))
        ->execute();
    }
  }
}

/**
 * Implements hook_node_load().
 */
function uc_usps_node_load($nodes, $types) {
  $product_types = array_intersect(uc_product_types(), $types);

  if (empty($product_types)) {
    return;
  }

  $vids = array();
  $shipping_type = config_get('uc_shipping.settings', 'uc_store_shipping_type');
  $shipping_types = db_query("
    SELECT id, shipping_type
    FROM {uc_quote_shipping_types}
    WHERE id_type = :type
    AND id IN (:ids)
    ", array(
      ':type' => 'product',
      ':ids' => array_keys($nodes),
    ))->fetchAllKeyed();

  foreach ($nodes as $nid => $node) {
    if (!in_array($node->type, $product_types)) {
      continue;
    }

    if (isset($shipping_types[$nid])) {
      $node->shipping_type = $shipping_types[$nid];
    }
    else {
      $node->shipping_type = $shipping_type;
    }

    if ($node->shipping_type == 'small_package') {
      $vids[$nid] = $node->vid;
    }
  }

  if ($vids) {
    $result = db_query("SELECT * FROM {uc_usps_products} WHERE vid IN (:vids)", array(':vids' => $vids), array('fetch' => PDO::FETCH_ASSOC));
    foreach ($result as $usps) {
      $nodes[$usps['nid']]->usps = $usps;
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function uc_usps_node_delete($node) {
  db_delete('uc_usps_products')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_node_revision_delete().
 */
function uc_usps_node_revision_delete($node) {
  db_delete('uc_usps_products')
    ->condition('vid', $node->vid)
    ->execute();
}

/**
 * Implements hook_config_info().
 */
function uc_usps_config_info() {
  $prefixes['uc_usps.settings'] = array(
    'label' => t('Ubercart USPS settings'),
    'group' => t('Configuration'),
  );

  return $prefixes;
}

/******************************************************************************
 * Ubercart Hooks                                                             *
 ******************************************************************************/

/**
 * Implements hook_uc_shipping_type().
 */
function uc_usps_uc_shipping_type() {
  $weight = config_get('uc_quote.settings', 'uc_quote_type_weight');

  $types = array(
    'envelope' => array(
      'id' => 'envelope',
      'title' => t('Envelope'),
      'weight' => isset($weight['envelope']) ? $weight['envelope'] : -1,
    ),
    'small_package' => array(
      'id' => 'small_package',
      'title' => t('Small package'),
      'weight' => isset($weight['small_package']) ? $weight['small_package'] : 0,
    ),
  );

  return $types;
}

/**
 * Implements hook_uc_shipping_method().
 */
function uc_usps_uc_shipping_method() {
  $operations = array(
    'configure' => array(
      'title' => t('configure'),
      'href' => 'admin/store/settings/quotes/settings/usps',
    ),
  );

  // Check whether we're using the legacy API or the new API.
  if (config_get('uc_usps.settings', 'uc_usps_authorization_method') == 'legacy') {
    return array(
      'usps_env' => array(
        'id' => 'usps_env',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Envelope)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'envelope',
          'callback' => 'uc_usps_quote',
          'accessorials' => _uc_usps_env_services(),
        ),
      ),
      'usps' => array(
        'id' => 'usps',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Parcel)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'small_package',
          'callback' => 'uc_usps_quote',
          'accessorials' => _uc_usps_services(),
        ),
      ),
      'usps_intl_env' => array(
        'id' => 'usps_intl_env',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Intl., Envelope)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'envelope',
          'callback' => 'uc_usps_quote',
          'accessorials' => _uc_usps_intl_env_services(),
        ),
        'weight' => 1,
      ),
      'usps_intl' => array(
        'id' => 'usps_intl',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Intl., Parcel)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'small_package',
          'callback' => 'uc_usps_quote',
          'accessorials' => _uc_usps_intl_services(),
        ),
        'weight' => 1,
      ),
    );
  }
  else { // authorization_method == 'newapi'
    // Use same IDs as legacy but different callback and services lists
    // (accessorials).
    return array(
      'usps_env' => array(
        'id' => 'usps_env',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Envelope)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'envelope',
          'callback' => 'uc_usps_newapi_quote',
          'accessorials' => uc_usps_newapi_dom_env_all_services(),
        ),
      ),
      'usps' => array(
        'id' => 'usps',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Parcel)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'small_package',
          'callback' => 'uc_usps_newapi_quote',
          'accessorials' => uc_usps_newapi_dom_parcel_all_services(),
        ),
      ),
      'usps_intl_env' => array(
        'id' => 'usps_intl_env',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Intl., Envelope)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'envelope',
          'callback' => 'uc_usps_newapi_quote',
          'accessorials' => uc_usps_newapi_intl_env_all_services(),
        ),
        'weight' => 1,
      ),
      'usps_intl' => array(
        'id' => 'usps_intl',
        'module' => 'uc_usps',
        'title' => t('U.S. Postal Service (Intl., Parcel)'),
        'operations' => $operations,
        'quote' => array(
          'type' => 'small_package',
          'callback' => 'uc_usps_newapi_quote',
          'accessorials' => uc_usps_newapi_intl_parcel_all_services(),
        ),
        'weight' => 1,
      ),
    );
  }
}

/******************************************************************************
 * Module Functions                                                           *
 ******************************************************************************/

/**
 * Callback for retrieving USPS shipping quote.
 *
 * @param $products
 *   Array of cart contents.
 * @param $details
 *   Order details other than product information.
 * @param $method
 *   The shipping method to create the quote.
 *
 * @return array
 *   array of services, keyed on service code, each element being an array with
 *   the following keys:
 *   - rate - the rate with markup for this service
 *   - label — a text string used as the line-item label
 *   - option_label — formatted HTML for the option presented for user choice
 *   In addition to the services, the return list can contain a special key:
 *   - data - array of data if there is debugging information or errors,
 *     containing one or both of the following keyed elements:
 *     - 'debug' - a string of debug information
 *     - 'errors' - an array of strings of the individual errors received.
 */
function uc_usps_quote($products, $details, $method) {
  // The uc_quote AJAX query can fire before the customer has completely
  // filled out the destination address, so check to see whether the address
  // has all needed fields. If not, abort.
  $destination = (object) $details;

  // Country code is always needed.
  if (empty($destination->country)) {
    // Skip this shipping method.
    return array();
  }

  // Shipments to the US also need zone and postal_code.
  if (($destination->country == 840) &&
      (empty($destination->zone) || empty($destination->postal_code))) {
    // Skip this shipping method.
    return array();
  }

  // USPS Production server.
  $connection_url = 'https://production.shippingapis.com/ShippingAPI.dll';

  // Initialize $debug_data to prevent PHP notices here and in uc_quote.
  $debug = user_access('configure quotes') && config_get('uc_quote.settings', 'uc_quote_display_debug');
  $config = config('uc_usps.settings');
  $debug_data = array(
    'debug' => NULL,
    'error' => array(),
  );
  $services = array();
  $addresses = array(
    UcAddress::__set_state(config_get('uc_quote.settings', 'uc_quote_store_default_address')),
  );
  $packages = _uc_usps_package_products($products, $addresses);
  if (!count($packages)) {
    return array();
  }

  foreach ($packages as $key => $ship_packages) {
    $orig = $addresses[$key];
    $orig->email = uc_store_email();

    if (strpos($method['id'], 'intl') && ($destination->country != 840)) {
      // Build XML for international rate request.
      $request = uc_usps_intl_rate_request($ship_packages, $orig, $destination);
    }
    elseif ($destination->country == 840) {
      // Build XML for domestic rate request.
      $request = uc_usps_rate_request($ship_packages, $orig, $destination);
    }

    if ($debug && $config->get('uc_usps_debug_request_data')) {
      $debug_data['debug'] .= t("REQUEST:\n@request\n\n", array('@request' => htmlentities(urldecode($request))));
    }

    $result = backdrop_http_request($connection_url, array(
      'method' => 'POST',
      'data' => $request,
    ));

    if ($debug && $config->get('uc_usps_debug_return_data')) {
      $debug_data['debug'] .= t("RETURN:\n@return\n\n", array('@return' => htmlentities($result->data)));
    }

    $rate_type = config_get('uc_usps.settings', 'uc_usps_online_rates');
    $response = new SimpleXMLElement($result->data);

    // Map double-encoded HTML markup in service names to Unicode characters.
    $service_markup = array(
      '&lt;sup&gt;&amp;reg;&lt;/sup&gt;' => '®',
      '&lt;sup&gt;&amp;trade;&lt;/sup&gt;' => '™',
      '&lt;sup&gt;&#174;&lt;/sup&gt;' => '®',
      '&lt;sup&gt;&#8482;&lt;/sup&gt;' => '™',
      '**' => '',
    );
    // Use this map to fix USPS service names.
    if (strpos($method['id'], 'intl')) {
      // Find and replace markup in International service names.
      foreach ($response->xpath('//Service') as $service) {
        $service->SvcDescription = str_replace(array_keys($service_markup), $service_markup, $service->SvcDescription);
      }
    }
    else {
      // Find and replace markup in Domestic service names.
      foreach ($response->xpath('//Postage') as $postage) {
        $postage->MailService = str_replace(array_keys($service_markup), $service_markup, $postage->MailService);
      }
    }

    if (isset($response->Package)) {
      foreach ($response->Package as $package) {
        if (isset($package->Error)) {
          $debug_data['error'][] = (string) $package->Error[0]->Description . '<br />';
        }
        else {
          if (strpos($method['id'], 'intl')) {
            foreach ($package->Service as $service) {
              $id = (string) $service['ID'];
              $services[$id]['label'] = t('U.S.P.S. @service', array('@service' => (string) $service->SvcDescription));
              // Markup rate before customer sees it.
              if (!isset($services[$id]['rate'])) {
                $services[$id]['rate'] = 0;
              }
              $services[$id]['rate'] += uc_usps_rate_markup((string) $service->Postage);
            }
          }
          else {
            foreach ($package->Postage as $postage) {
              $classid = (string) $postage['CLASSID'];
              if ($classid === '0') {
                if ((string) $postage->MailService == "First-Class Package Service - Retail™") {
                  $classid = 'zeroParcel';
                }
                elseif ((string) $postage->MailService == "First-Class Mail® Letter") {
                  $classid = 'zeroFlat';
                }
                else {
                  $classid = 'zero';
                }
              }
              if (!isset($services[$classid]['rate'])) {
                $services[$classid]['rate'] = 0;
              }
              $services[$classid]['label'] = t('U.S.P.S. @service', array('@service' => (string) $postage->MailService));
              // Markup rate before customer sees it.
              // Rates are stored differently if ONLINE $rate_type is requested.
              // First Class doesn't have online rates, so if CommercialRate
              // is missing use Rate instead.
              if ($rate_type && !empty($postage->CommercialRate)) {
                $services[$classid]['rate'] += uc_usps_rate_markup((string) $postage->CommercialRate);
              }
              else {
                $services[$classid]['rate'] += uc_usps_rate_markup((string) $postage->Rate);
              }
            }
          }
        }
      }
    }
  }

  if ($debug && $config->get('uc_usps_debug_service_data')) {
    $debug_data['debug'] .= t('SERVICES (before filtering)') . "\n" . var_export($services, TRUE) . "\n";
  }

  $method_services = 'uc_' . $method['id'] . '_services';
  $usps_services = array_filter(config_get('uc_usps.settings', $method_services));
  foreach ($services as $service => $quote) {
    if (!in_array($service, $usps_services)) {
      unset($services[$service]);
    }
  }
  foreach ($services as $key => $quote) {
    if (isset($quote['rate'])) {
      $services[$key]['rate'] = $quote['rate'];
      $services[$key]['option_label'] = theme('uc_usps_option_label', array('service' => $quote['label'], 'packages' => $packages));
    }
  }

  uasort($services, 'uc_quote_price_sort');

  // Merge debug data into $services.  This is necessary because
  // $debug_data is not sortable by a 'rate' key, so it has to be
  // kept separate from the $services data until this point.
  if (isset($debug_data['debug']) ||
      (isset($debug_data['error']) && count($debug_data['error']))) {
    $services['data'] = $debug_data;
  }

  return $services;
}

/**
 * Constructs a quote request for domestic shipments.
 *
 * @param $packages
 *   Array of packages received from the cart.
 * @param $origin
 *   Delivery origin address information.
 * @param $destination
 *   Delivery destination address information.
 *
 * @return
 *   RateV4Request XML document to send to USPS.
 */
function uc_usps_rate_request($packages, $origin, $destination) {
  $config = config('uc_usps.settings');
  $request  = '<RateV4Request USERID="' . $config->get('uc_usps_user_id') . '">';
  $request .= '<Revision>2</Revision>';

  $rate_type = $config->get('uc_usps_online_rates');

  $package_id = 0;
  foreach ($packages as $package) {
    $qty = $package->qty;
    for ($i = 0; $i < $qty; $i++) {
      $request .= '<Package ID="' . $package_id . '">' .
        '<Service>' . ($rate_type ? 'ONLINE' : 'ALL') . '</Service>' .
        '<ZipOrigination>' . substr(trim($origin->postal_code), 0, 5) . '</ZipOrigination>' .
        '<ZipDestination>' . substr(trim($destination->postal_code), 0, 5) . '</ZipDestination>' .
        '<Pounds>' . intval($package->pounds) . '</Pounds>' .
        '<Ounces>' . number_format($package->ounces, 1, '.', '') . '</Ounces>' .
        '<Container>' . $package->container . '</Container>' .
        '<Size>' . $package->size . '</Size>' .
        '<Width>' . $package->width . '</Width>' .
        '<Length>' . $package->length . '</Length>' .
        '<Height>' . $package->height . '</Height>' .
        '<Girth>' . $package->girth . '</Girth>' .
        '<Value>' . $package->price . '</Value>' .
        '<Machinable>' . ($package->machinable ? 'TRUE' : 'FALSE') . '</Machinable>' .
        '<ReturnLocations>TRUE</ReturnLocations>' .
        '<ShipDate Option="EMSH">' . format_date(time(), 'custom', 'd-M-Y', 'America/New_York', 'en') . '</ShipDate>';

      // Check if we need to add any special services to this package.
      if ($config->get('uc_usps_insurance')             ||
           $config->get('uc_usps_delivery_confirmation') ||
           $config->get('uc_usps_signature_confirmation')) {

        $request .= '<SpecialServices>';

        if ($config->get('uc_usps_insurance')) {
          $request .= '<SpecialService>1</SpecialService>';
        }
        if ($config->get('uc_usps_delivery_confirmation')) {
          $request .= '<SpecialService>13</SpecialService>';
        }
        if ($config->get('uc_usps_signature_confirmation')) {
          $request .= '<SpecialService>15</SpecialService>';
        }

        $request .= '</SpecialServices>';
      }

      // Close off Package tag.
      $request .= '</Package>';

      $package_id++;
    }
  }
  $request .= '</RateV4Request>';

  return 'API=RateV4&XML=' . backdrop_encode_path($request);
}

/**
 * Constructs a quote request for international shipments.
 *
 * @param $packages
 *   Array of packages received from the cart.
 * @param $origin
 *   Delivery origin address information.
 * @param $destination
 *   Delivery destination address information.
 *
 * @return
 *   IntlRateRequest XML document to send to USPS.
 */
function uc_usps_intl_rate_request($packages, $origin, $destination) {
  $config = config('uc_usps.settings');
  module_load_include('inc', 'uc_usps', 'uc_usps.countries');
  $request  = '<IntlRateV2Request USERID="' . $config->get('uc_usps_user_id') . '">';
  $request .= '<Revision>2</Revision>';

  // USPS does not use ISO 3166 country name in some cases so we
  // need to transform ISO country name into one USPS understands.
  $shipto_country = uc_usps_country_map($destination->country);

  $package_id = 0;
  foreach ($packages as $package) {
    $qty = $package->qty;
    for ($i = 0; $i < $qty; $i++) {
      $request .= '<Package ID="' . $package_id . '">' .
        '<Pounds>' . intval($package->pounds) . '</Pounds>' .
        '<Ounces>' . ceil($package->ounces) . '</Ounces>' .
        '<MailType>All</MailType>' .
        '<ValueOfContents>' . $package->price . '</ValueOfContents>' .
        '<Country>' . $shipto_country . '</Country>' .
        '<Container>' . 'RECTANGULAR' . '</Container>' .
        '<Size>' . 'REGULAR' . '</Size>' .
        '<Width>' . '</Width>' .
        '<Length>' . '</Length>' .
        '<Height>' . '</Height>' .
        '<Girth>' . '</Girth>' .
        '<OriginZip>' . substr(trim($origin->postal_code), 0, 5) . '</OriginZip>';

      // Check if we need to add any special services to this package.
      if ($config->get('uc_usps_insurance')) {
        $request .= '<ExtraServices><ExtraService>1</ExtraService></ExtraServices>';
      }

      // Close off Package tag.
      $request .= '</Package>';

      $package_id++;
    }
  }
  $request .= '</IntlRateV2Request>';

  $request = 'API=IntlRateV2&XML=' . backdrop_encode_path($request);
  return $request;
}

/**
 * Callback for retrieving USPS shipping quote using the new API.
 *
 * @param array $products
 *   Array of cart contents.
 * @param array $details
 *   Order details other than product information, which in this case is the
 *   destination address object (UcAddress).
 * @param array $method
 *   The shipping method to create the quote.
 *
 * @return array
 *   list of services, keyed on service_key, each element being an array with
 *   the following keys:
 *   - 'rate' - the rate with markup for this service
 *   - 'label' — a text string used as the line-item label
 *   - 'option_label' — formatted HTML for the option presented for user choice
 *   In addition to the services, the return list can contain a special key:
 *   - data - array of data if there is debugging information or errors,
 *     containing one or both of the following keyed elements:
 *     - 'debug' - a string of debug information
 *     - 'errors' - an array of strings of the individual errors received.
 */
function uc_usps_newapi_quote($products, $details, $method) {
  // The uc_quote AJAX query can fire before the customer has completely
  // filled out the destination address, so check to see whether the address
  // has all needed fields. If not, abort.
  $destination = (object) $details;

  // Country code is always needed.
  if (empty($destination->country)) {
    // Skip this shipping method.
    return array();
  }

  // Shipments to the US also need zone and postal_code.
  if (($destination->country == 840) &&
      (empty($destination->zone) || empty($destination->postal_code))) {
    // Skip this shipping method.
    return array();
  }

  $config = config('uc_usps.settings');
  $debug = user_access('configure quotes') && config_get('uc_quote.settings', 'uc_quote_display_debug');
  // Initialize $debug_data, which we will fill in as we get quotes.
  // $debug_data['debug'] is used for admin debugging; if $debug is TRUE, it
  // will contain all requests and results formatted as a single HTML string.
  // $debug_data['error'] will contain a list of any error messages that will be
  // displayed to the end user. We only report the existence of errors, leaving
  // it to admins to check the watchdog log for details.
  $debug_data = array(
    'debug' => NULL,
    'error' => array(),
  );
  $services = array();
  $addresses = array(
    UcAddress::__set_state(config_get('uc_quote.settings', 'uc_quote_store_default_address')),
  );

  // $packages will be a structured array of packages grouped by pickup address.
  $packages = _uc_usps_package_products($products, $addresses);
  if (!count($packages)) {
    return array();
  }
  $num_packages = 0; // The total number of packages.

  foreach ($packages as $key => $ship_packages) {
    $origin = $addresses[$key];
    $origin->email = uc_store_email();

    foreach ($ship_packages as $package) {
      // USPS new API only lets us do a rate request for one package at a
      // time so we'll have to do a rate lookup for each package and then
      // combine the results.
      $rate_info = uc_usps_newapi_package_quote($package, $origin, $destination, $method, $debug, $debug_data);
      $num_packages++;
      foreach ($rate_info as $key => $info) {
        $rate = $info['totalPrice'];
        if (!isset($services[$key])) {
          $services[$key] = array(
            'rate' => uc_usps_rate_markup((string) $rate),
            'label' => $info['description'],
            'option_label' => theme('uc_usps_option_label', array(
              'service' => $info['description'],
              'packages' => $packages,
            )),
            'count' => 1,
          );
        }
        else {
          $services[$key]['rate'] += $rate;
          $services[$key]['count']++;
        }
      }
    }
  }

  if ($debug && $config->get('uc_usps_debug_service_data')) {
    $debug_data['debug'] .= t('SERVICES (before filtering)') . "\n" . var_export($services, TRUE) . "\n\n";
  }

  // USPS module ships all packages via the same rate, so filter the list to
  // include only those services that were quoted for all packages.
  foreach ($services as $key => $service) {
    if ($service['count'] != $num_packages) {
      unset($services[$key]);
    }
    else {
      unset($services[$key]['count']);
    }
  }

  // Filter the list to include only those services that were checked in the
  // settings.
  $method_services = array(
    'usps_env' => 'uc_usps_newapi_dom_env_services',
    'usps' => 'uc_usps_newapi_dom_parcel_services',
    'usps_intl_env' => 'uc_usps_newapi_intl_env_services',
    'usps_intl' => 'uc_usps_newapi_intl_parcel_services',
  )[$method['id']];
  $usps_services = array_filter(config_get('uc_usps.settings', $method_services));
  foreach ($services as $service => $quote) {
    if (!in_array($service, $usps_services)) {
      unset($services[$service]);
    }
  }

  if (empty($services)) {
    if ($debug && $config->get('uc_usps_debug_service_data') && empty($debug_data['error'])) {
      // No errors, but no matching services. Add debugging information.
      $debug_data['debug'] .= t('None of the recommended services match those chosen in the settings.') . "\n";
    }
  }

  // Sort by price.
  uasort($services, 'uc_quote_price_sort');

  // Merge debug data into $services.  This is necessary because $debug_data is
  // not sortable by a 'rate' key, so it has to be kept separate from the
  // $services data until this point.
  if (isset($debug_data['debug']) ||
      (isset($debug_data['error']) && count($debug_data['error']))) {
    $services['data'] = $debug_data;
  }

  return $services;
}

/**
 * Get a USPS quote on a single package using the new API.
 *
 * @param object $package - the package to be quoted.
 * @param UcAddress $origin - its origin address.
 * @param object $destination - its destination.
 * @param array $method - the quote method.
 * @param bool $debug - whether to record debug information in $debug_data.
 * @param array $debug_data - diagnostic information (if requested) and errors.
 *
 * @return array
 *   An array of rate information for this package.
 *   The fields of each row are those returned by USPS and vary by mail class.
 *   Each rate has a key so that multi-package quotes can be combined by key.
 */
function uc_usps_newapi_package_quote($package, $origin, $destination, $method, $debug, &$debug_data) {
  if (empty($package) || empty($destination) || empty($destination->country)) {
    return array();
  }
  $domestic = _uc_usps_is_domestic($destination->country);
  if ($domestic && empty($destination->postal_code)) {
    // Domestic destinations need a ZIP code.
    return array();
  }
  if ($domestic && strpos($method['id'], 'intl')) {
    // Mismatch between destination and selected method.
    return array();
  }
  $config = config('uc_usps.settings');
  $price_type = $config->get('uc_usps_price_type');
  $access_token = _uc_usps_access_token();
  $mailing_date = (new DateTime('@' . (REQUEST_TIME)))->format('Y-m-d');
  $rate_info = array();

  // Get dimensions and sort them into canonical order no matter how the
  // packager might have packed products into the package.
  $dimensions = array(
    (float) $package->length,
    (float) $package->width,
    (float) $package->height,
  );
  rsort($dimensions);

  if ($domestic) { // Domestic
    // Get extra services for domestic.
    $extra_services = array();
    if ($config->get('uc_usps_insurance')) {
      if ($package->price <= 500.0) {
        $extra_services[] = 930; // Insurance <= $500
      }
      else {
        $extra_services[] = 931; // Insurance > $500
      }
    }
    if ($config->get('uc_usps_signature_confirmation')) {
      $extra_services[] = 921; // Signature Confirmation
    }

    // Always do a parcel quote because flat-rate envelopes will only show up
    // here.
    $connection_url = $config->get('uc_usps_connection_address') . '/prices/v3/total-rates/search';
    $request = array(
      'originZIPCode' => substr(trim($origin->postal_code), 0, 5),
      'destinationZIPCode' => substr(trim($destination->postal_code), 0, 5),
      'weight' => uc_usps_weight_markup($package->weight),
      'length' => $dimensions[0],
      'width' => $dimensions[1],
      'height' => $dimensions[2],
      'mailClasses' => [ 'ALL' ],
      'priceType' => $price_type,
      'mailingDate' => $mailing_date,
      'hasNonstandardCharacteristics' => $package->non_standard ?? FALSE,
      'extraServices' => $extra_services,
    );
    $request_data = backdrop_json_encode($request);
    if ($debug && $config->get('uc_usps_debug_request_data')) {
      $debug_data['debug'] .= t("REQUEST (DOM,PARCEL):\n@request\n", array('@request' => var_export($request, TRUE)));
    }
    $result = backdrop_http_request($connection_url, array(
      'method' => 'POST',
      'data' => $request_data,
      'headers' => array(
        'Content-Type' => 'application/json',
        'Authorization' => 'Bearer ' . $access_token,
      ),
    ));
    $data = backdrop_json_decode($result->data);
    if ($debug && $config->get('uc_usps_debug_return_data')) {
      $debug_data['debug'] .= t("RETURN:\n@data\n", array('@data' => var_export($data, TRUE)));
    }
    if (isset($data['error'])) {
      $errors[] = $data['error'];
      if ($debug && $config->get('uc_usps_debug_show_errors')) {
        $debug_data['debug'] .= t("ERRORS:\n@data\n", array('@data' => var_export($data['error'], TRUE)));
      }
    }
    else {
      // Accumulate $rate_info entries.
      if (isset($data['rateOptions'])) {
        foreach ($data['rateOptions'] as $rate_option) {
          $rate_row = $rate_option['rates'][0];
          $service_key = _uc_usps_newapi_service_key($rate_row);
          // Don't include special destination facilities for domestic mail.
          if ($rate_row['destinationEntryFacilityType'] != 'NONE') {
            continue;
          }
          // Don't include mailClass of SA, or USPS_MARKETING_MAIL.
          if (in_array($rate_row['mailClass'], array('SA', 'USPS_MARKETING_MAIL'))) {
            continue;
          }
          if ($package->nonstandard) {
           // If package is non-standard, only include NONSTANDARD processing.
           if ($rate_row['processingCategory'] != 'NONSTANDARD') {
              continue;
            }
          }
          else {
            // Package is not nonstandard, therefore it must be machinable, so
            // only include MACHINABLE or FLATS processing.
            if ($rate_row['processingCategory'] != 'MACHINABLE' && $rate_row['processingCategory'] != 'FLATS') {
              continue;
            }
          }
          // For envelope rates, check whether the package fits in the envelope.
          if (!_uc_usps_newapi_package_fits_envelope($package, $service_key)) {
            continue;
          }
          $rate_row['totalPrice'] = $rate_option['totalBasePrice'];
          // Add extra services to the price.
          if (isset($rate_option['extraServices'])) {
            foreach ($rate_option['extraServices'] as $extra_service) {
              if (in_array((float) $extra_service['extraService'], $extra_services)) {
                $rate_row['totalPrice'] += $extra_service['price'];
              }
            }
          }
          $rate_info[$service_key] = $rate_row;
        }
      }
    }
    // Add first-class letter/card/flat lookups only if the size of the package
    // qualifies for the mail class to be looked-up.
    $connection_url = $config->get('uc_usps_connection_address') . '/prices/v3/letter-rates/search';
    $request = array(
      'weight' => uc_usps_weight_markup($package->weight),
      'length' => $dimensions[0],
      'height' => $dimensions[1],
      'thickness' => $dimensions[2],
      'mailingDate' => $mailing_date,
    );
    // Letter rates have to be requested one-by-one, so make sure that the
    // rate is requested and the dimensions qualify to avoid unnecessary
    // lookups.
    foreach (array('LETTERS', 'CARDS', 'FLATS') as $rate) {
      if (_uc_usps_envelope_size_qualifies($dimensions, $rate)) {
        $request['processingCategory'] = $rate;
        $request_data = backdrop_json_encode($request);
        if ($debug && $config->get('uc_usps_debug_request_data')) {
          $debug_data['debug'] .= t("REQUEST (DOM,@rate):\n@request\n", array(
            '@rate' => $rate,
            '@request' => var_export($request, TRUE)),
          );
        }
        $result = backdrop_http_request($connection_url, array(
          'method' => 'POST',
          'data' => $request_data,
          'headers' => array(
            'Content-Type' => 'application/json',
            'Authorization' => 'Bearer ' . $access_token,
          ),
        ));
        $data = backdrop_json_decode($result->data);
        if ($debug && $config->get('uc_usps_debug_return_data')) {
          $debug_data['debug'] .= t("QUOTES:\n@data\n", array('@data' => var_export($data, TRUE)));
        }
        if (isset($data['error'])) {
          $errors[] = $data['error'];
          if ($debug && $config->get('uc_usps_debug_show_errors')) {
            $debug_data['debug'] .= t("ERRORS:\n@data\n", array('@data' => var_export($data['error'], TRUE)));
          }
        }
        else {
          if (!empty($data['rates'][0])) {
            $rate_row = $data['rates'][0];
            $service_key = _uc_usps_newapi_service_key($rate_row);
            $rate_row['totalPrice'] = $data['totalBasePrice'];
            // Add extra services to the price.
            if (isset($rate_row['extraServices'])) {
              foreach ($rate_row['extraServices'] as $extra_service) {
                if (in_array((float) $extra_service['extraService'], $extra_services)) {
                  $rate_row['totalPrice'] += $extra_service['price'];
                }
              }
            }
            $rate_info[$service_key] = $rate_row;
          }
        }
      }
    }
    if ($debug) {
      // Check whether any returned rates aren't in our lists of allowed rates.
      uc_usps_check_returned_rates($rate_info, array_merge(uc_usps_newapi_dom_env_all_services(), uc_usps_newapi_dom_parcel_all_services()));
    }
  }
  else { // International
    // Parcel quote
    $connection_url = $config->get('uc_usps_connection_address') . '/international-prices/v3/total-rates/search';

    // New API requires 2-letter ISO country codes.
    $country_code = db_query('
      SELECT country_iso_code_2
      FROM {uc_countries}
      WHERE country_id = :id
      ', array(':id' => $destination->country))
      ->fetchField();

    $request = array(
      'originZIPCode' => substr(trim($origin->postal_code), 0, 5),
      'foreignPostalCode' => trim($destination->postal_code),
      'destinationCountryCode' => $country_code,
      'weight' => uc_usps_weight_markup($package->weight),
      'length' => $dimensions[0],
      'width' => $dimensions[1],
      'height' => $dimensions[2],
      'mailClass' => 'ALL',
      'priceType' => $price_type,
      'mailingDate' => $mailing_date,
      'hasNonstandardCharacteristics' => $package->non_standard ?? FALSE,
      'extraServices' => [],
    );
    $request_data = backdrop_json_encode($request);
    if ($debug && $config->get('uc_usps_debug_request_data')) {
      $debug_data['debug'] .= t("REQUEST (INTL,PARCEL):\n@request\n", array('@request' => var_export($request, TRUE)));
    }
    $result = backdrop_http_request($connection_url, array(
      'method' => 'POST',
      'data' => $request_data,
      'headers' => array(
        'Content-Type' => 'application/json',
        'Authorization' => 'Bearer ' . $access_token,
      ),
    ));
    $data = backdrop_json_decode($result->data);
    if ($debug && $config->get('uc_usps_debug_return_data')) {
      $debug_data['debug'] .= t("RETURN:\n@data\n", array('@data' => var_export($data, TRUE)));
    }
    if (isset($data['error'])) {
      $errors[] = $data['error'];
      if ($debug && $config->get('uc_usps_debug_show_errors')) {
        $debug_data['debug'] .= t("ERRORS:\n@data\n", array('@data' => var_export($data['error'], TRUE)));
      }
    }
    else {
      // Accumulate $rate_info entries.
      if (isset($data['rateOptions'])) {
        foreach ($data['rateOptions'] as $rate_option) {
          $rate_row = $rate_option['rates'][0];
          $service_key = _uc_usps_newapi_service_key($rate_row);
          if ($package->nonstandard) {
           // If package is non-standard, only include NONSTANDARD processing.
           if ($rate_row['processingCategory'] != 'NONSTANDARD') {
              continue;
            }
          }
          else {
            // Package is not nonstandard, therefore it must be machinable, so
            // only include MACHINABLE and FLATS processing.
            if ($rate_row['processingCategory'] != 'MACHINABLE' && $rate_row['processingCategory'] != 'FLATS') {
              continue;
            }
          }
          // For envelope rates, check whether the package fits in the envelope.
          if (!_uc_usps_newapi_package_fits_envelope($package, $service_key)) {
            continue;
          }
          $rate_row['totalPrice'] = $rate_option['totalBasePrice'];
          // Add extra services to the price.
          if (isset($rate_option['extraServices'])) {
            foreach ($rate_option['extraServices'] as $extra_service) {
              if (in_array((float) $extra_service['extraService'], $extra_services)) {
                $rate_row['totalPrice'] += $extra_service['price'];
              }
            }
          }
          $rate_info[$service_key] = $rate_row;
        }
      }
    }
    // Letter/card/flat quote
    $connection_url = $config->get('uc_usps_connection_address') . '/international-prices/v3/letter-rates/search';
    $request = array(
      'destinationCountryCode' => $country_code,
      'weight' => uc_usps_weight_markup($package->weight),
      'length' => $dimensions[0],
      'height' => $dimensions[1],
      'thickness' => $dimensions[2],
      'mailingDate' => $mailing_date,
    );
    // Letter rates have to be requested one-by-one, so make sure that the
    // dimensions qualify to avoid unnecessary lookups.
    foreach (array('LETTERS', 'CARDS', 'FLATS') as $rate) {
      if (_uc_usps_envelope_size_qualifies($dimensions, $rate)) {
        $request['processingCategory'] = $rate;
        $request_data = backdrop_json_encode($request);
        if ($debug && $config->get('uc_usps_debug_request_data')) {
          $debug_data['debug'] .= t("REQUEST (INTL,@rate):\n@request\n", array(
            '@rate' => $rate,
            '@request' => var_export($request, TRUE)),
          );
        }
        $result = backdrop_http_request($connection_url, array(
          'method' => 'POST',
          'data' => $request_data,
          'headers' => array(
            'Content-Type' => 'application/json',
            'Authorization' => 'Bearer ' . $access_token,
          ),
        ));
        $data = backdrop_json_decode($result->data);
        if ($debug && $config->get('uc_usps_debug_return_data')) {
          $debug_data['debug'] .= t("QUOTES:\n@data\n", array('@data' => var_export($data, TRUE)));
        }
        if (isset($data['error'])) {
          $errors[] = $data['error'];
          if ($debug && $config->get('uc_usps_debug_show_errors')) {
            $debug_data['debug'] .= t("ERRORS:\n@data\n", array('@data' => var_export($data['error'], TRUE)));
          }
        }
        else {
          if (!empty($data['rates'][0])) {
            $rate_row = $data['rates'][0];
            $service_key = _uc_usps_newapi_service_key($rate_row);
            $rate_row['totalPrice'] = $data['totalBasePrice'];
            // Add extra services to the price.
            if (isset($rate_row['extraServices'])) {
              foreach ($rate_row['extraServices'] as $extra_service) {
                if (in_array((float) $extra_service['extraService'], $extra_services)) {
                  $rate_row['totalPrice'] += $extra_service['price'];
                }
              }
            }
            $rate_info[$service_key] = $rate_row;
          }
        }
      }
    }
    if ($debug) {
      // Check whether any returned rates aren't in our lists of allowed rates.
      uc_usps_check_returned_rates($rate_info, array_merge(uc_usps_newapi_intl_env_all_services(), uc_usps_newapi_intl_parcel_all_services()));
    }
  }

  // In the legacy API, we passed the product packaging type to the USPS rate
  // lookup, but there is no provision for that in the new API. Instead, we
  // filter the rate quotes according to their description text.
  $filter_text = _uc_usps_pkg_type_filter_text()[$package->container];
  if ($filter_text != '*') {
    if ($filter_text == '') {
      // This package type is no longer supported.
      $rate_info = array();
    }
    else {
      // Particular packaging type is called for; filter description text.
      foreach ($rate_info as $service_key => $info) {
        if (strpos(strtolower($info['description']), $filter_text) === FALSE) {
          unset($rate_info[$service_key]);
        }
      }
    }
  }

  // Reformat errors as individual strings and report them.
  if (!empty($errors)) {
    foreach ($errors as $error) {
      $quote_error = $error['code'] . ' ' . $error['message'];
      // This will put the quote error into the output buffer, where it will be
      // picked up and reported to watchdog if we're turned on error logging.
      // See uc_quote_action_get_quote().
      echo $quote_error;
    }
  }

  return $rate_info;
}

/**
 * Debugging utility to check whether returned rates aren't in our lists of
 * allowed rates. If such rates are missing, post a notice in the watchdog
 * log that contains the PHP code to add the missing rates to the appropriate
 * list of supported rates (env or parcel, dom or intl).
 *
 * @param array $rate_info - The formatted rates returned by USPS.
 * @param array $allowed_rates - The list of rates that this module supports.
 */
function uc_usps_check_returned_rates($rate_info, $allowed_rates) {
  $missing = array();
  foreach ($rate_info as $key => $data) {
    if (!isset($allowed_rates[$key])) {
      $missing[] = check_plain("'" . $key . "' => '" . $data['description'] . "',");
    }
  }
  if (!empty($missing)) {
    watchdog('uc_usps', "Missing rates:<br> !rates", array('!rates' => implode("<br>", $missing)), WATCHDOG_WARNING);
  }
}

/**
 * Utility to construct the service key from a rate_info row.
 *
 * The service key needs to be distinguish between all possible services
 * returned from a rate lookup and must be constructible from the parameters
 * returned by a rate lookup. Some of the obvious candidates don't work:
 * 'productName' is blank for many services. 'SKU' can be the same for multiple
 * services and can be different for the same service for different 'priceType'
 * settings. The 'description' field exists for all lookups and is the same for
 * the same service for different 'priceType' settings; for brevity, we create
 * a code from the first letter of each description (which is still unique for
 * each service).
 *
 * @param array $info
 *   A single row returned from a USPS rate request via the new API.
 *
 * @return string
 *   The service key, which is used as the row key for rate requests and the
 *   list of services returned by uc_usps_newapi_quote().
 */
function _uc_usps_newapi_service_key($info) {
  $ret = '';
  $dwords = explode(' ', ucwords($info['description']));
  foreach ($dwords as $dword) {
    $ret .= substr($dword, 0, 1);
  }
  return $ret;
}

/**
 * Modifies the rate received from USPS before displaying to the customer.
 *
 * @param $rate
 *   Shipping rate without any rate markup.
 *
 * @return
 *   Shipping rate after markup.
 */
function uc_usps_rate_markup($rate) {
  $config = config('uc_usps.settings');
  $markup = trim($config->get('uc_usps_rate_markup'));
  $type   = $config->get('uc_usps_rate_markup_type');

  if (is_numeric($markup)) {
    switch ($type) {
      case 'percentage':
        return $rate + $rate * floatval($markup) / 100;

      case 'multiplier':
        return $rate * floatval($markup);

      case 'currency':
        return $rate + floatval($markup);
    }
  }
  else {
    return $rate;
  }
}

/**
 * Modifies the weight of shipment before sending to USPS for a quote.
 *
 * @param $weight
 *   Shipping weight without any weight markup.
 *
 * @return
 *   Shipping weight after markup.
 */
function uc_usps_weight_markup($weight) {
  $config = config('uc_usps.settings');
  $markup = trim($config->get('uc_usps_weight_markup'));
  $type   = $config->get('uc_usps_weight_markup_type');

  if (is_numeric($markup)) {
    switch ($type) {
      case 'percentage':
        return $weight + $weight * floatval($markup) / 100;

      case 'multiplier':
        return $weight * floatval($markup);

      case 'mass':
        return $weight + floatval($markup);
    }
  }
  else {
    return $weight;
  }
}

/**
 * Get a valid access token from config or, if the old one has expired, fetch
 * a new token from the USPS server.
 *
 * @return string | FALSE - the token (if successful), FALSE if not.
 */
function _uc_usps_access_token() {
  $config = config('uc_usps.settings');
  $token_expiry = state_get('uc_usps_token_expiry');
  if ($token_expiry >= REQUEST_TIME + 60) {
    // If expiration is more than a minute away, return the currently stored
    // token. Tokens are valid for 8 hours after issuance.
    return state_get('uc_usps_access_token');
  }
  else {
    // If expiration is less than minute away, get a new token and return it.
    // The new token will be stored and the expiration updated.
    return _uc_usps_fetch_access_token();
  }
}

/**
 * Fetch an OAuth2 access token from the USPS website and store it in config.
 *
 * @return string|false
 *   Return the token if successful, otherwise return FALSE.
 *   FALSE.
 *
 * @see uc_ups_get_access_token()
 */
function _uc_usps_fetch_access_token() {
  $config = config('uc_usps.settings');
  $consumer_key = $config->get('uc_usps_consumer_key');
  $consumer_secret = $config->get('uc_usps_consumer_secret');
  $auth_url = $config->get('uc_usps_connection_address') . '/oauth2/v3/token';

  if (empty($consumer_key) || empty($consumer_secret)) {
    watchdog('uc_usps', 'ERROR: Missing USPS Consumer Key or Consumer Secret.', [], WATCHDOG_ERROR);
    return FALSE;
  }

  $data = array(
    'grant_type' => 'client_credentials',
    'client_id' => $consumer_key,
    'client_secret' => $consumer_secret,
  );
  $options = array(
    'method' => 'POST',
    'data' => backdrop_http_build_query($data),
    'headers' => array(
      'Content-Type' => 'application/x-www-form-urlencoded',
    ),
  );

  $result = backdrop_http_request($auth_url, $options);
  if ($result->code == 200) {
    $response = backdrop_json_decode($result->data);
    if (!empty($response['access_token'])) {
      // Store token in Backdrop state.
      state_set('uc_usps_access_token', $response['access_token']);
      state_set('uc_usps_token_expiry', round($response['issued_at'] / 1000) + $response['expires_in']);
      // Debug: Confirm token storage
      watchdog('uc_usps', '✅ Successfully retrieved and stored USPS OAuth token.', [], WATCHDOG_NOTICE);
      return $response['access_token'];
    }
    else {
      watchdog('uc_usps', '❌ USPS OAuth response missing access token. Response: @response', ['@response' => print_r($response, TRUE)], WATCHDOG_ERROR);
    }
  }
  else {
    watchdog('uc_usps', '❌ USPS OAuth request failed with HTTP Code @code. Response: @response', [
      '@code' => $result->code,
      '@response' => print_r($result, TRUE),
    ], WATCHDOG_ERROR);
  }

  return FALSE;
}

/**
 * Organizes products into packages for shipment.
 *
 * @param $products
 *   An array of product objects as they are represented in the cart or order.
 * @param &$addresses
 *   Reference to an array of addresses which are the pickup locations of each
 *   package. They are determined from the shipping addresses of their
 *   component products.
 *
 * @return
 *   Array of packaged products. Packages are separated by shipping address and
 *   weight or quantity limits imposed by the shipping method or the products.
 */
function _uc_usps_package_products($products, &$addresses = array()) {
  $last_key = 0;
  $packages = array();
  if (config_get('uc_usps.settings', 'uc_usps_all_in_one') && count($products) > 1) {
    // "All in one" packaging strategy.
    // Only need to do this if more than one product line item in order.
    $packages[$last_key] = array(0 => _uc_usps_new_package());
    foreach ($products as $product) {
      if ($product->nid) {
        // Packages are grouped by the address from which they will be
        // shipped. We will keep track of the different addresses in an array
        // and use their keys for the array of packages.

        $key = NULL;
        $address = uc_quote_get_default_shipping_address($product->nid);
        foreach ($addresses as $index => $value) {
          if ($address->isSamePhysicalLocation($value)) {
            // This is an existing address.
            $key = $index;
            break;
          }
        }

        if (!isset($key)) {
          // This is a new address. Increment the address counter $last_key
          // instead of using [] so that it can be used in $packages and
          // $addresses.
          $addresses[++$last_key] = $address;
          $key = $last_key;
          $packages[$key] = array(0 => _uc_usps_new_package());
        }
      }

      // Grab some product properties directly from the (cached) product
      // data. They are not normally available here because the $product
      // object is being read out of the $order object rather than from
      // the database, and the $order object only carries around a limited
      // number of product properties.
      $temp = node_load($product->nid);
      $product->length = $temp->length;
      $product->width = $temp->width;
      $product->height = $temp->height;
      $product->length_units = $temp->length_units;
      $product->usps['container'] = isset($temp->usps['container']) ? $temp->usps['container'] : 'VARIABLE';

      if (config_get('uc_usps.settings', 'uc_usps_authorization_method') == 'newapi') {
        // Stack products of varying size to get required package dimensions to
        // accommodate all products in the package.
        $dimensions = array(
          $product->length,
          $product->width,
          $product->height,
        );
        rsort($dimensions);
        $packages[$key][0]->length = max($packages[$key][0]->length, $dimensions[0]);
        $packages[$key][0]->width = max($packages[$key][0]->width, $dimensions[1]);
        $packages[$key][0]->height += $dimensions[2];
        $packages[$key][0]->girth = 2 * $packages[$key][0]->width + 2 * $packages[$key][0]->height;
      }

      $packages[$key][0]->price += $product->price * $product->qty;
      $packages[$key][0]->weight += $product->weight * $product->qty * uc_weight_conversion($product->weight_units, 'lb');
    }
    foreach ($packages as $key => $package) {
      $packages[$key][0]->pounds = floor($package[0]->weight);
      $packages[$key][0]->ounces = LB_TO_OZ * ($package[0]->weight - $packages[$key][0]->pounds);
      $packages[$key][0]->container = 'VARIABLE';
      $packages[$key][0]->size = 'REGULAR';
      $packages[$key][0]->qty = 1;
    }
  }
  else {
    // !(config_get('uc_usps.settings', 'uc_usps_all_in_one') && count($products) > 1)
    // "Each in own" packaging strategy, or only one product line item in order.
    foreach ($products as $product) {
      if ($product->nid) {
        $address = uc_quote_get_default_shipping_address($product->nid);
        if (in_array($address, $addresses)) {
          // This is an existing address.
          foreach ($addresses as $index => $value) {
            if ($address == $value) {
              $key = $index;
              break;
            }
          }
        }
        else {
          // This is a new address.
          $addresses[++$last_key] = $address;
          $key = $last_key;
        }
      }
      if (!isset($product->pkg_qty) || !$product->pkg_qty) {
        $product->pkg_qty = 1;
      }
      $num_of_pkgs = (int) ($product->qty / $product->pkg_qty);
      if ($num_of_pkgs) {
        $package = clone $product;
        $package->description = $product->model;
        $weight = $product->weight * $product->pkg_qty;
        switch ($product->weight_units) {
          case 'g':
            // Convert to kg and fall through.
            $weight = $weight * G_TO_KG;
          case 'kg':
            // Convert to lb and fall through.
            $weight = $weight * KG_TO_LB;
          case 'lb':
            $package->pounds = floor($weight); // DEPRECATED
            $package->ounces = LB_TO_OZ * ($weight - $package->pounds); // DEPRECATED
            break;

          case 'oz':
            $package->pounds = floor($weight * OZ_TO_LB); // DEPRECATED
            $package->ounces = $weight - $package->pounds * LB_TO_OZ; // DEPRECATED
            break;
        }
        $package->weight = $weight;

        // Grab some product properties directly from the (cached) product
        // data. They are not normally available here because the $product
        // object is being read out of the $order object rather than from
        // the database, and the $order object only carries around a limited
        // number of product properties.
        $temp = node_load($product->nid);
        $product->length = $temp->length;
        $product->width = $temp->width;
        $product->height = $temp->height;
        $product->length_units = $temp->length_units;
        $product->usps['container'] = isset($temp->usps['container']) ? $temp->usps['container'] : 'VARIABLE';

        $package->container = $product->usps['container'];
        $length_conversion = uc_length_conversion($product->length_units, 'in');
        $package->length = max($product->length, $product->width) * $length_conversion;
        $package->width = min($product->length, $product->width) * $length_conversion;
        $package->height = $product->height * $length_conversion;
        if ($package->length < $package->height) {
          list($package->length, $package->height) = array($package->height, $package->length);
        }
        $package->girth = 2 * $package->width + 2 * $package->height;
        $package->size = $package->length <= 12 ? 'REGULAR' : 'LARGE';
        $package->price = $product->price * $product->pkg_qty;
        $package->qty = $num_of_pkgs;
        $packages[$key][] = $package;
      }
      $remaining_qty = $product->qty % $product->pkg_qty;
      if ($remaining_qty) {
        $package = clone $product;
        $package->description = $product->model;
        $weight = $product->weight * $remaining_qty;
        switch ($product->weight_units) {
          case 'g':
            // Convert to kg and fall through.
            $weight = $weight * G_TO_KG;
          case 'kg':
            // Convert to lb and fall through.
            $weight = $weight * KG_TO_LB;
          case 'lb':
            $package->pounds = floor($weight);
            $package->ounces = LB_TO_OZ * ($weight - $package->pounds);
            break;

          case 'oz':
            $package->pounds = floor($weight * OZ_TO_LB);
            $package->ounces = $weight - $package->pounds * LB_TO_OZ;
            break;
        }
        $package->weight = $weight;

        $package->container = $product->usps['container'];
        $length_conversion = uc_length_conversion($product->length_units, 'in');
        $package->length = max($product->length, $product->width) * $length_conversion;
        $package->width = min($product->length, $product->width) * $length_conversion;
        $package->height = $product->height * $length_conversion;
        if ($package->length < $package->height) {
          list($package->length, $package->height) = array($package->height, $package->length);
        }
        $package->girth = 2 * $package->width + 2 * $package->height;
        $package->size = $package->length <= 12 ? 'REGULAR' : 'LARGE';
        $package->price = $product->price * $remaining_qty;
        $package->qty = 1;
        $packages[$key][] = $package;
      }
    }
  }
  // Set machinability and nonstandard-ness for all packages.
  foreach ($packages as $idx => $package_group) {
    foreach ($package_group as $jdx => $package) {
      $packages[$idx][$jdx]->machinable = (
        $package->length <= 34 &&
        $package->width <= 17 &&
        $package->height <= 17 &&
        $package->weight <= 35
      );
      // Nonstandard-ness is based on machinability but can also be overridden.
      $packages[$idx][$jdx]->nonstandard = !$package->machinable;
      if ($package->container == 'NONRECTANGULAR') {
        $packages[$idx][$jdx]->non_standard = TRUE;
      }
    }
  }
  return $packages;
}

/**
 * Select form elements for package types, which are a setting for each product.
 * This value is passed to rate lookup for the legacy API, but there is no
 * equivalent value passed to the new API. We'll have to map these to the rates
 * returned from the lookup function.
 *
 * @return array
 */
function _uc_usps_pkg_types() {
  if (config_get('uc_usps.settings', 'uc_usps_authorization_method') == 'legacy') {
    // Return the original set of packaging types, but note which ones are no
    // longer selectable in the new API.
    return array(
      'VARIABLE' => t('Variable'),
      'FLAT RATE ENVELOPE' => t('Flat rate envelope'),
      'PADDED FLAT RATE ENVELOPE' => t('Padded flat rate envelope'),
      'LEGAL FLAT RATE ENVELOPE' => t('Legal flat rate envelope'),
      'SMALL FLAT RATE ENVELOPE' => t('Small flat rate envelope (DEPRECATED)'),
      'WINDOW FLAT RATE ENVELOPE' => t('Window flat rate envelope (DEPRECATED)'),
      'GIFT CARD FLAT RATE BOX' => t('Gift card flat rate box (DEPRECATED)'),
      'FLAT RATE BOX' => t('Flat rate box'),
      'SM FLAT RATE BOX' => t('Small flat rate box'),
      'MD FLAT RATE BOX' => t('Medium flat rate box'),
      'LG FLAT RATE BOX' => t('Large flat rate box'),
      'REGIONALRATEBOXA' => t('Regional rate box A (DEPRECATED)'),
      'REGIONALRATEBOXB' => t('Regional rate box B (DEPRECATED)'),
      'RECTANGULAR' => t('Rectangular'),
      'NONRECTANGULAR' => t('Non-rectangular'),
    );
  }
  else { // New API, only include the supported package types.
    return array(
      'VARIABLE' => t('Variable'),
      'FLAT RATE ENVELOPE' => t('Flat rate envelope'),
      'PADDED FLAT RATE ENVELOPE' => t('Padded flat rate envelope'),
      'LEGAL FLAT RATE ENVELOPE' => t('Legal flat rate envelope'),
      'FLAT RATE BOX' => t('Flat rate box'),
      'SM FLAT RATE BOX' => t('Small flat rate box'),
      'MD FLAT RATE BOX' => t('Medium flat rate box'),
      'LG FLAT RATE BOX' => t('Large flat rate box'),
      'RECTANGULAR' => t('Rectangular'),
      'NONRECTANGULAR' => t('Non-rectangular'),
    );
  }
}

/**
 * Returns a rendered text block that displays all rates for a $rate_info array.
 * Useful for debugging.
 *
 * @param $rate_info
 *   An array of rate information as constructed within
 *   _uc_usps_newapi_package_quote().
 *
 * @return string
 *   Rendered HTML for the array key and description for each returned service.
 */
function _uc_usps_rate_info($rate_info) {
  $items = array();;
  foreach ($rate_info as $key => $data) {
    if (!isset($allowed_rates[$key])) {
      $items[] = check_plain("" . $key . " — " . $data['description'] . ": " . sprintf('$%0.2f', $data['totalPrice']));
    }
  }
  return theme('item_list', array('items' => $items));
}

/**
 * Returns a rendered text block that describes details of the packaging.
 *
 * @param $package_quotes
 *   Array of individual $package_quote arrays, each of which contains elements
 *   for these keys:
 *     label: the official name of the postal rate
 *     rate: the rate for this particular package (including markup)
 *     package: the package object itself.
 **/
function _uc_usps_package_info($package_quotes) {
  if (!is_array($package_quotes)) {
    return '';
  }
  $containers = _uc_usps_container_types();
  $items = array();
  foreach ($package_quotes as $key => $package_quote) {
    $package = $package_quote['package'];
    $product_info = array();
    foreach ($package->products as $product) {
      $product_info[] = $product->qty . '×' . $product->model;
    }
    $items[] = array(
      'data' => 'Package ' . (1 + $key),
      'children' => array(
        t('Container') . ': ' . $containers[$package->container],
        t('Shipping rate') . ': ' . $package_quote['label'],
        t('Price with per-pkg markup') . ': ' . sprintf('$%0.2f', $package_quote['rate']),
        t('Contents size') . ': ' .
          $package->length . '×' .
          $package->width . '×' .
          $package->height . ' ' .
          $package->length_units,
        t('Total weight') . ': ' .
          $package->weight . ' (' .
          $package->pounds . ' lb, ' .
          $package->ounces . ' oz)',
        t('Products') . ': ' . implode(', ', $product_info),
      ),
    );
  }
  // Temporary: add "New API" to the info comment for ease of comparison.
  if (config_get('uc_usps.settings', 'uc_usps_authorization_method') == 'newapi') {
    array_unshift($items, t('New API'));
  }
  return theme('item_list', array('items' => $items));
}

/**
 * Return whether a set of dimensions qualifies for a letter/card/flat rate.
 * @param array $dimensions - the array of length, width, thickness, as floats.
 * @param string $rate - one of 'LETTERS', 'CARDS', or 'FLATS'.
 *
 * @return array|false
 */
function _uc_usps_envelope_size_qualifies($dimensions, $rate) {
  switch ($rate) {
    case 'LETTERS':
      return
        $dimensions[0] >= 5.0 && $dimensions[0] <= 11.5 &&
        $dimensions[1] >= 2.5 && $dimensions[1] <= 6.125 &&
        $dimensions[2] >= 0.007 && $dimensions[2] <= 0.25;
      break;

    case 'CARDS':
      return
        $dimensions[0] >= 5.0 && $dimensions[0] <= 6.0 &&
        $dimensions[1] >= 3.5 && $dimensions[1] <= 4.25 &&
        $dimensions[2] >= 0.007 && $dimensions[2] <= 0.016;
      break;

    case 'FLATS':
      return
        ($dimensions[0] >= 11.5 || $dimensions[1] >= 6.125 || $dimensions[2] >= 0.25) &&
        $dimensions[0] <= 15.0 &&
        $dimensions[1] <= 12.0 &&
        $dimensions[2] <= 0.75;
      break;

    default:
      return FALSE;
  }
}

/**
 * Returns a list of filter text for the possible package types. For each type,
 * check the description field of the rate quote against the filter text:
 * '*' — all descriptions are acceptable.
 * '' — no descriptions are acceptable (this type is no longer supported).
 * '<text>' — <text> must be present in the description, case-insensitive.
 *
 * @return array
 */
function _uc_usps_pkg_type_filter_text() {
  return array(
    'VARIABLE' => '*',
    'FLAT RATE ENVELOPE' => 'flat rate envelope',
    'PADDED FLAT RATE ENVELOPE' => 'padded flat rate envelope',
    'LEGAL FLAT RATE ENVELOPE' => 'legal flat rate envelope',
    'SMALL FLAT RATE ENVELOPE' => '',
    'WINDOW FLAT RATE ENVELOPE' => '',
    'GIFT CARD FLAT RATE BOX' => '',
    'FLAT RATE BOX' => 'flat rate box',
    'SM FLAT RATE BOX' => 'small flat rate box',
    'MD FLAT RATE BOX' => 'medium flat rate box',
    'LG FLAT RATE BOX' => 'large flat rate box',
    'REGIONALRATEBOXA' => '',
    'REGIONALRATEBOXB' => '',
    'RECTANGULAR' => '*',
    'NONRECTANGULAR' => '*',
  );
}

/**
 * Returns an array of countries that qualify for domestic rates keyed on
 * country ID. (newapi)
 */
function _uc_usps_domestic_countries() {
  return array(
    840 => t('United States'),
    630 => t('Puerto Rico'),
    850 => t('Virgin Islands (US)'),
    16 => t('American Samoa'),
    316 => t('Guam'),
    580 => t('Northern Mariana Islands'),
    583 => t('Federated States of Micronesia'),
    584 => t('Marshall Islands'),
    585 => t('Palau'),
  );
}

/**
 * Returns an array of countries that qualify for domestic rates keyed on ISO
 * 2-letter codes. (newapi)
 */
function _uc_usps_domestic_countries_iso2() {
  return array(
    'US' => t('United States'),
    'PR' => t('Puerto Rico'),
    'VI' => t('Virgin Islands (US)'),
    'AS' => t('American Samoa'),
    'GU' => t('Guam'),
    'MP' => t('Northern Mariana Islands'),
    'FM' => t('Federated States of Micronesia'),
    'MH' => t('Marshall Islands'),
    'PW' => t('Palau'),
  );
}

/**
 * Returns TRUE if country code is domestic. (newapi)
 */
function _uc_usps_is_domestic($country) {
  $countries = _uc_usps_domestic_countries();
  return isset($countries[$country]);
}

/**
 * Return whether package contents fit within a specified type of envelope. If
 * the type isn't an envelope, return TRUE, because USPS automatically accounts
 * for the size for the fixed-size boxes. (newapi)
 *
 * @param object $package
 *   The package object containing the products.
 * @param string $service_key
 *   The service key for the rate returned by USPS, constructed from the first
 *   letters of the rate description.
 *
 * @return bool
 *   Return whether the package fits into the envelope for envelope services or
 *   TRUE for non-envelope USPS rates.
 */
function _uc_usps_newapi_package_fits_envelope($package, $service_key) {
  $legal = (strpos($service_key, 'LFRE') !== FALSE);
  $regular = (strpos($service_key, 'FRE') !== FALSE) && !$legal;
  if ($regular) {
    if ($package->length <= 12.5 && $package->width <= 9.5 && $package->height <= 0.5) {
      return TRUE;
    }
    if ($package->length <= 13.5 && $package->width <= 8.5 && $package->height <= 0.625) {
      return TRUE;
    }
    return FALSE;
  }
  elseif ($legal) {
    if ($package->length <= 11.25 && $package->width <= 9.25 && $package->height <= 0.75) {
      return TRUE;
    }
    if ($package->length <= 12.5 && $package->width <= 8.5 && $package->height <= 1.0) {
      return TRUE;
    }
    return FALSE;
  }
  return TRUE;
}

/**
 * Maps envelope shipment services to their IDs (legacy).
 *
 * @return array
 */
function _uc_usps_env_services() {
  return array(
    'zero' => t('U.S.P.S. First-Class Mail Postcard'),
    'zeroFlat' => t('U.S.P.S. First-Class Mail Letter'),
    12 => t('U.S.P.S. First-Class Postcard Stamped'),
    1 => t('U.S.P.S. Priority Mail'),
    16 => t('U.S.P.S. Priority Mail Flat-Rate Envelope'),
    3 => t('U.S.P.S. Express Mail'),
    13 => t('U.S.P.S. Express Mail Flat-Rate Envelope'),
    23 => t('U.S.P.S. Express Mail Sunday/Holiday Guarantee'),
    25 => t('U.S.P.S. Express Mail Flat-Rate Envelope Sunday/Holiday Guarantee'),
  );
}

/**
 * Maps parcel shipment services to their IDs (legacy).
 *
 * @return array
 */
function _uc_usps_services() {
  return array(
    'zeroFlat' => t('U.S.P.S. First-Class Mail Letter'),
    'zeroParcel' => t('U.S.P.S. First-Class Mail Parcel'),
    1 => t('U.S.P.S. Priority Mail'),
    28 => t('U.S.P.S. Priority Mail Small Flat-Rate Box'),
    17 => t('U.S.P.S. Priority Mail Regular/Medium Flat-Rate Box'),
    22 => t('U.S.P.S. Priority Mail Large Flat-Rate Box'),
    3 => t('U.S.P.S. Express Mail'),
    23 => t('U.S.P.S. Express Mail Sunday/Holiday Guarantee'),
    4 => t('U.S.P.S. Parcel Post'),
    5 => t('U.S.P.S. Bound Printed Matter'),
    6 => t('U.S.P.S. Media Mail'),
    7 => t('U.S.P.S. Library'),
  );
}

/**
 * Returns international envelope services to their IDs (legacy).
 *
 * @return array
 */
function _uc_usps_intl_env_services() {
  return array(
    13 => t('First Class Mail International Letter'),
    14 => t('First Class Mail International Large Envelope'),
    2 => t('Priority Mail International'),
    8 => t('Priority Mail International Flat Rate Envelope'),
    4 => t('Global Express Guaranteed'),
    12 => t('GXG Envelopes'),
    1 => t('Express Mail International (EMS)'),
    10 => t('Express Mail International (EMS) Flat Rate Envelope'),
  );
}

/**
 * Maps international parcel services to their IDs (legacy).
 *
 * @return array
 */
function _uc_usps_intl_services() {
  return array(
    15 => t('First Class Mail International Package'),
    2 => t('Priority Mail International'),
    16 => t('Priority Mail International Small Flat-Rate Box'),
    9 => t('Priority Mail International Regular/Medium Flat-Rate Box'),
    11 => t('Priority Mail International Large Flat-Rate Box'),
    4 => t('Global Express Guaranteed'),
    6 => t('Global Express Guaranteed Non-Document Rectangular'),
    7 => t('Global Express Guaranteed Non-Document Non-Rectangular'),
    1 => t('Express Mail International (EMS)'),
  );
}

/**
 * Maps domestic envelope services to their IDs (newapi).
 */
function uc_usps_newapi_dom_env_all_services() {
  return array(
    'FCLM' => 'First Class Letter Metered',
    'FCP' => 'First Class Postcards',
    'FCF' => 'First Class Flats',
    'PMFRE' => 'Priority Mail Flat Rate Envelope',
    'PMPFRE' => 'Priority Mail Padded Flat Rate Envelope',
    'PMLFRE' => 'Priority Mail Legal Flat Rate Envelope',
    'PMMS' => 'Priority Mail Machinable Single-piece',
    'PMEFRE' => 'Priority Mail Express Flat Rate Envelope',
    'PMEPFRE' => 'Priority Mail Express Padded Flat Rate Envelope',
    'PMELFRE' => 'Priority Mail Express Legal Flat Rate Envelope',
    'PMELFREHD' => 'Priority Mail Express Legal Flat Rate Envelope Holiday Delivery',
    'PMEMS' => 'Priority Mail Express Machinable Single-piece',
    'UGAMS' => 'USPS Ground Advantage Machinable Single-piece',
  );
}

/**
 * Maps domestic parcel services to their IDs (newapi).
 */
function uc_usps_newapi_dom_parcel_all_services() {
  return array(
    'FCLM' => 'First Class Letter Metered',
    'FCF' => 'First Class Flats',
    'PMMSFRB' => 'Priority Mail Machinable Small Flat Rate Box',
    'PMMMFRB' => 'Priority Mail Machinable Medium Flat Rate Box',
    'PMMLFRB' => 'Priority Mail Machinable Large Flat Rate Box',
    'PMMLFRBA' => 'Priority Mail Machinable Large Flat Rate Box APO/FPO/DPO',
    'PMMS' => 'Priority Mail Machinable Single-piece',
    'PMNS' => 'Priority Mail Nonstandard Single-piece',
    'PMMCNPT1' => 'Priority Mail Machinable Cubic Non-Soft Pack Tier 1',
    'PMMCSPT1' => 'Priority Mail Machinable Cubic Soft Pack Tier 1',
    'PMEMS' => 'Priority Mail Express Machinable Single-piece',
    'UGAMS' => 'USPS Ground Advantage Machinable Single-piece',
    'UGANS' => 'USPS Ground Advantage Nonstandard Single-piece',
    'UGAMCNPT1' => 'USPS Ground Advantage Machinable Cubic Non-Soft Pack Tier 1',
    'UGAMCSPT1' => 'USPS Ground Advantage Machinable Cubic Soft Pack Tier 1',
    'BPMMP' => 'Bound Printed Matter Machinable Presorted',
    'BPMNP' => 'Bound Printed Matter Nonstandard Presorted',
    'LMNB' => 'Library Mail Nonstandard Basic',
    'LMNS' => 'Library Mail Nonstandard Single-piece',
    'LMMS' => 'Library Mail Machinable Single-piece',
    'LMM5' => 'Library Mail Machinable 5-digit',
    'LMN5' => 'Library Mail Nonstandard 5-digit',
    'MMNB' => 'Media Mail Nonstandard Basic',
    'MMNS' => 'Media Mail Nonstandard Single-piece',
    'MMMS' => 'Media Mail Machinable Single-piece',
    'MMM5' => 'Media Mail Machinable 5-digit',
    'MMN5' => 'Media Mail Nonstandard 5-digit',
  );
}

/**
 * Maps international envelope services to their IDs (newapi).
 */
function uc_usps_newapi_intl_env_all_services() {
  return array(
    'FCLM' => 'First Class Letter Metered',
    'FCP' => 'First Class Postcards',
    'FCF' => 'First Class Flats',
    'FPISMIS' => 'First-Class Package International Service Machinable ISC Single-piece',
    'PMIIFRE' => 'Priority Mail International ISC Flat Rate Envelope',
    'PMIMIPFRE' => 'Priority Mail International Machinable ISC Padded Flat Rate Envelope',
    'PMIIS' => 'Priority Mail International ISC Single-piece',
    'PMIMIS' => 'Priority Mail International Machinable ISC Single-piece',
    'PMIILFRE' => 'Priority Mail International ISC Legal Flat Rate Envelope',
    'PMEIIFRE' => 'Priority Mail Express International ISC Flat Rate Envelope',
    'PMEIILFRE' => 'Priority Mail Express International ISC Legal Flat Rate Envelope',
    'PMEIIS' => 'Priority Mail Express International ISC Single-piece',
    'PMEIIPFRE' => 'Priority Mail Express International ISC Padded Flat Rate Envelope',
  );
}

/**
 * Maps international parcel services to their IDs (newapi).
 */
function uc_usps_newapi_intl_parcel_all_services() {
  return array(
    'FPISMIS' => 'First-Class Package International Service Machinable ISC Single-piece',
    'PMIMILFRB' => 'Priority Mail International Machinable ISC Large Flat Rate Box',
    'PMIMIMFRB' => 'Priority Mail International Machinable ISC Medium Flat Rate Box',
    'PMIIS' => 'Priority Mail International ISC Single-piece',
    'PMIMIS' => 'Priority Mail International Machinable ISC Single-piece',
    'PMINIS' => 'Priority Mail International Nonstandard ISC Single-piece',
    'PMEIIS' => 'Priority Mail Express International ISC Single-piece',
  );
}

/**
 * Pseudo-constructor to set default values of a package.
 */
function _uc_usps_new_package() {
  $package = new stdClass();

  $package->price = 0;
  $package->qty = 1;
  $package->pounds = 0;
  $package->ounces = 0;
  $package->weight = 0;
  $package->container = 0;
  $package->size = 0;
  $package->machinable = TRUE;
  $package->nonstandard = FALSE;

  $package->length = 0;
  $package->width = 0;
  $package->height = 0;
  $package->girth = 0;

  //  $package->length_units = 'in';
  //  $package->weight_units = 'lb';

  return $package;
}
