<?php

/**
 * @file
 * Provides PayPal Checkout payment method for Ubercart using PayPal REST API.
 * Modeled after commerce_paypal_checkout, adapted for Ubercart.
 */

/**
 * Implements hook_uc_payment_method().
 */
function uc_paypal_checkout_uc_payment_method() {
	$methods[] = array(
		'id' => 'paypal_checkout',
		'name' => t('PayPal Checkout'),
		'title' => t('Pay with PayPal Checkout. PayPal accounts and major credit cards accepted.'),
    'desc' => t('Pay securely using PayPal Checkout (REST API).'),
    'callback' => 'uc_paypal_checkout_payment_callback',
    'weight' => 2,
    'checkout' => TRUE,
    'no_gateway' => TRUE,
  );
	
	return $methods;
}

/**
 * Implements hook_autoload_info().
 */
function uc_paypal_checkout_autoload_info() {
  return array(
    'PayPalCheckoutClient' => 'lib/PayPalCheckoutClient.php',
    'PayPalCheckoutAuthenticationException' => 'lib/PayPalCheckoutExceptions.php',
    'PayPalCheckoutHttpException' => 'lib/PayPalCheckoutExceptions.php',
    'PayPalCheckoutHttpServerErrorException' => 'lib/PayPalCheckoutExceptions.php',
    'PayPalCheckoutHttpClientErrorException' => 'lib/PayPalCheckoutExceptions.php',
    'PayPalCheckoutHttpRedirectionException' => 'lib/PayPalCheckoutExceptions.php',
    'PayPalCheckoutInvalidResponseJsonException' => 'lib/PayPalCheckoutExceptions.php',
  );
}

/**
 * Implements hook_theme().
 * 
 * Used to theme the smart payment buttons shown during order review.
 */
function uc_paypal_checkout_theme() {
  return array(
    'uc_paypal_checkout_smart_payment_buttons' => array(
      'variables' => array(
        'payment_method' => '',
        'commit' => FALSE,
        'order' => NULL,
        'flow' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function uc_paypal_checkout_menu() {
	$items = array();

  // Add a menu item for capturing authorizations.
  $items['admin/store/orders/%uc_order/payments/%uc_payment/paypal-checkout-capture'] = array(
    'title' => 'Capture',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_paypal_checkout_capture_form', 3, 5),
    'access callback' => 'uc_paypal_checkout_capture_void_access',
    'access arguments' => array(3, 5),
    'type' => MENU_CALLBACK,
    'file' => 'uc_paypal_checkout.admin.inc',
  );
   // Add a menu item for voiding authorizations.
  $items['admin/store/orders/%uc_order/payments/%uc_payment/paypal-checkout-void'] = array(
    'title' => 'Void',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_paypal_checkout_void_form', 3, 5),
    'access callback' => 'uc_paypal_checkout_capture_void_access',
    'access arguments' => array(3, 5),
    'type' => MENU_CALLBACK,
    'weight' => 4,
    'file' => 'uc_paypal_checkout.admin.inc',
  );
  // Add a menu item for refunding settled transactions.
  $items['admin/store/orders/%uc_order/payments/%uc_payment/paypal-checkout-refund'] = array(
    'title' => 'Refund',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('uc_paypal_checkout_refund_form', 3, 5),
    'access callback' => 'uc_paypal_checkout_refund_access',
    'access arguments' => array(3, 5),
    'type' => MENU_CALLBACK,
    'weight' => 4,
    'file' => 'uc_paypal_checkout.admin.inc',
  );
	// Endpoints for AJAX and PayPal SDK callbacks (to be implemented).
	$items['uc_paypal_checkout/create-order/%uc_order'] = array(
		'page callback' => 'uc_paypal_checkout_create_order',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['uc_paypal_checkout/approve-order/%uc_order/%'] = array(
		'page callback' => 'uc_paypal_checkout_approve_order',
		'page arguments' => array(2, 3),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
  $items['uc_paypal_checkout/payment-approved/%uc_order'] = array(
    'page callback' => 'uc_paypal_checkout_payment_approved',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
	return $items;
}

/**
 * Validation callback for disable_funding.
 */
function uc_paypal_checkout_disable_funding_validate($element, &$form_state, $form) {
	form_set_value($element, array_filter($element['#value']), $form_state);
}

/**
 * Validation callback for disable_card.
 */
function uc_paypal_checkout_disable_card_validate($element, &$form_state, $form) {
	$parents = $element['#parents'];
	array_pop($parents);
	$parents[] = 'disable_funding';
	$disable_funding = backdrop_array_get_nested_value($form_state['values'], $parents);
	// When the "card" funding source is disabled, the "disable_card" setting cannot be specified.
	if (isset($disable_funding['card'])) {
		$element['#value'] = array();
	}
	form_set_value($element, array_filter($element['#value']), $form_state);
}

/**
 * Validation callback for customize_buttons (button style).
 */
function uc_paypal_checkout_customize_buttons_validate($element, &$form_state, $form) {
	// Make sure no style is saved when the "customize_buttons" checkbox is unchecked.
	$parents = $element['#parents'];
	array_pop($parents);
	$parents[] = 'style';
	if (empty($element['#value'])) {
		backdrop_array_set_nested_value($form_state['values'], $parents, array(), TRUE);
	}
	else {
		$style = backdrop_array_get_nested_value($form_state['values'], $parents);
		// The tagline is not allowed for the vertical layout.
		if (isset($style['layout']) && $style['layout'] == 'vertical') {
			unset($style['tagline']);
			backdrop_array_set_nested_value($form_state['values'], $parents, $style, TRUE);
		}
	}
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * Injects the PayPal smar buttons and disables the submit button.
 */
function uc_paypal_checkout_form_uc_cart_checkout_review_form_alter(&$form, &$form_state) {
  $order = $form_state['uc_order'];
  if ($order->payment_method == 'paypal_checkout') {
    $form['smart_payment_buttons'] = array(
      '#theme' => 'uc_paypal_checkout_smart_payment_buttons',
      '#payment_method' => 'uc_paypal_checkout',
      '#commit' => TRUE,
      '#order' => $order,
      '#flow' => 'mark',
    );
    $form['actions']['submit']['#access'] = FALSE;
  }
}

/**
 * Page callback: Provide the createOrder() callback expected by the SDK.
 */
function uc_paypal_checkout_create_order($order) {
	$settings = config_get('uc_paypal_checkout.settings');
	$api_client = new PayPalCheckoutClient($settings);
  if (!$api_client) {
    backdrop_json_output(array());
    backdrop_exit();
  }
	try {
  	$request_body = uc_paypal_checkout_prepare_order_request($order, $settings);
    backdrop_alter('uc_paypal_checkout_create_order_request', $request_body, $order);
		$json = $api_client->createOrder($request_body);
		backdrop_add_http_header('Content-Type', 'text/plain');
		echo isset($json['id']) ? $json['id'] : '';
		backdrop_exit();
	}
  catch (Exception $e) {
		watchdog_exception('uc_paypal_checkout', $e);
		backdrop_json_output(array());
		backdrop_exit();
	}
}

/**
 * Page callback: onApprove() callback.
 * 
 * Completes the order.
 */
function uc_paypal_checkout_approve_order($order, $flow) {
  $settings = config_get('uc_paypal_checkout.settings');

  // There are several spots where things could go wrong. Use a variable to
  // set a redirect back to the cart and a message.
  $error_redirect = url('cart');
  $error_message = t('We could not complete your payment with PayPal. Please try again or contact us if the problem persists.');

  $api_client = new PayPalCheckoutClient($settings);
  if (!$api_client) {
    watchdog('uc_paypal_checkout', 'Could not instantiate the PayPal Checkout API client.', array(), WATCHDOG_ERROR);
    backdrop_set_message($error_message, 'error');
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
  }

	$data = backdrop_json_decode(file_get_contents('php://input'));
  if (!in_array($flow, array('shortcut', 'mark')) || !isset($data['id'])) {
    watchdog('uc_paypal_checkout', 'Either the flow or the remote id for the order could not be determined.', array(), WATCHDOG_ERROR);
    backdrop_set_message($error_message, 'error');
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
  }

  $remote_id = $data['id'];
  // Store the PayPal order ID, and the "flow" used ("shortcut"|"mark").
  // Note that we don't perform any validation here, that happens inside
  // redirect validate callback from the $return_url set below.
	$order->data['uc_paypal_checkout'] = array(
    'flow' => $flow,
    'remote_id' => $remote_id,
  );

  // TODO: this does not seem necessary.
  if (empty($order->data['payment_redirect_key'])) {
    $order->data['payment_redirect_key'] = backdrop_hash_base64(time());
  }

  // We have to manually set the payment method if empty, it's also required
  // by the payment redirect form validate callback.
  // TODO: this may not be needed in UC.
  if (empty($order->data['payment_method'])) {
    $order->data['payment_method'] = 'uc_paypal_checkout';
  }

  try {
    // Retrieve the approved order.
    $paypal_order = $api_client->getOrder($remote_id);
  }
  catch (\Exception $exception) {
    watchdog_exception('uc_paypal_checkout', $exception);
    backdrop_set_message($error_message, 'error');
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
    // return FALSE;
  }
  $order_total = $order->order_total;
  $paypal_amount = $paypal_order['purchase_units'][0]['amount'];
  $paypal_total = $paypal_amount['value'];

  // Check the remote status.
  if (!in_array($paypal_order['status'], ['APPROVED', 'SAVED'])) {
    watchdog('uc_paypal_checkout', 'The PayPal order status is neither APPROVED nor SAVED and therefore it cannot be processed.', array(), WATCHDOG_ERROR);
    backdrop_set_message($error_message, 'error');
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
  }

  // Check that the PayPal total matches the order total.
  if ($paypal_total != $order_total || $paypal_amount['currency_code'] !=  $order->currency) {
    watchdog('uc_paypal_checkout', 'Either the total or the currency of the PayPal order does not match the ones in the Ubercart order.', array(), WATCHDOG_ERROR);
    backdrop_set_message($error_message, 'error');
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
  }

  // Store the intent for later reuse, it can't be updated, so no risk in
  // being out of sync.
  $intent = $paypal_order['intent'];
  $order->data['uc_paypal_checkout']['intent'] = strtolower($intent);

  $payer = $paypal_order['payer'];
  // If the user is anonymous, add their PayPal e-mail to the order.
  if (empty($order->primary_email)) {
    $order->primary_email = $payer['email_address'];
  }
  
  // Update billing information profile for the order with the available info.
  if (!empty($settings['update_billing_profiles'])) {
    uc_paypal_checkout_customer_profile($order, 'billing', $paypal_order);
  }
  // Update the delivery information profile for the order with the available
  // info.
  if (!empty($setting['update_shipping_profiles'])) {
    uc_paypal_checkout_customer_profile($order, 'delivery', $paypal_order);
  }

  // Actually capture or authorize the order.
  try {
    if ($intent == 'CAPTURE') {
      $response = $api_client->captureOrder($remote_id);
      $remote_payment = $response['purchase_units'][0]['payments']['captures'][0];
    }
    else {
      $response = $api_client->authorizeOrder($remote_id);
      $remote_payment = $response['purchase_units'][0]['payments']['authorizations'][0];
    }
  }
  catch (\Exception $exception) {
    watchdog_exception('uc_paypal_checkout', $exception);
    // Display an error message and remain on the same page.
    backdrop_set_message($error_message, 'error');
    watchdog('uc_paypal_checkout', 'PayPal Checkout transaction failed for order @order_number.', array('@order_number' => $order->order_id), WATCHDOG_ERROR);
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
  }

  $remote_status = strtolower($remote_payment['status']);

  // If status is denied, expired or declined, or if we do not know how to
  // handle this remote payment status, log an error and stop here.
  if (in_array($remote_status, ['denied', 'expired', 'declined']) || !in_array($remote_status, ['created', 'pending', 'completed'])) {
    uc_order_comment_save($order->order_id, $order->uid, t('The authorization or capture has failed due to remote status @status.', array('@status' => $remote_status)), 'admin');
    // Display an error message and exit.
    watchdog('uc_paypal_checkout', 'PayPal Checkout transaction failed for order @order_number. Remote stauts: @status.', array('@order_number' => $order->order_id, '@status' => $remote_status), WATCHDOG_ERROR);
    backdrop_set_message($error_message, 'error');
    rules_invoke_event('uc_paypal_checkout_event_failed', $order);
    backdrop_json_output(array('redirectUri' => $error_redirect));
    backdrop_exit();
  }

  // Update the order status for the shortcut flow.
  if ($flow == 'shortcut') {
    uc_order_comment_save($order->order_id, $order->uid, t('Customer clicked the Smart payment buttons on the cart page.'), 'admin');
  }
  // Save the changes to the order.
  $order->save();

  // Enter a payment record.
  $comment = t('PayPal Checkout remote ID: @remote_id. Remote status: @remote_status', array(
    '@remote_id' => $remote_payment['id'],
    '@remote_status' => $remote_status,
  ));
  $payment_data = array(
    'uc_paypal_checkout' => array(
      'remote_id' => $remote_payment['id'],
      'remote_status' => $remote_status,
    ),
  );
  uc_payment_enter($order->order_id, 'paypal_checkout', $order->order_total, $order->uid, $payment_data, $comment);
  if ($remote_status == 'pending' || $remote_status == 'created') {
    // This is an authorization, funds have not been captured.
    uc_order_update_status($order->order_id, 'paypal_checkout_pending');
    rules_invoke_event('uc_paypal_checkout_event_pending', $order);
  }
  else {
    rules_invoke_event('uc_paypal_checkout_event_completed', $order);
  }
  uc_order_comment_save($order->order_id, $order->uid, t('PayPal Checkout reported a payment of @amount @currency.', array('@amount' => uc_currency_format($paypal_total, FALSE), '@currency' => $paypal_amount['currency_code'])));
  unset($_SESSION['uc_checkout'][$order->order_id]['do_review']);
  $_SESSION['uc_checkout'][$order->order_id]['do_complete'] = TRUE;
  $return_url = url('cart/checkout/complete');
	backdrop_json_output(array('redirectUri' => $return_url));
	backdrop_exit();
}

/**
 * Prepare PayPal order request body from Ubercart order.
 */
function uc_paypal_checkout_prepare_order_request($order, $settings) {
	$items = array();
  $item_total = 0;
	foreach ($order->products as $product) {
		$item = array(
			'name' => mb_substr(strip_tags($product->title), 0, 127),
			'unit_amount' => array(
				'currency_code' => $order->currency,
				'value' => number_format($product->price, 2, '.', ''),
			),
			'quantity' => $product->qty,
		);
    if (isset($product->model)) {
      $item['sku'] = $product->model;
    }
    $item_total += ($product->price * $product->qty);
    $items[] = $item;
	}

  // Add generic line items to the items array.
  foreach ($order->line_items as $line_item) {
    if ($line_item['type'] != 'generic') {
      continue;
    }
    $item = array(
      'name' => mb_substr(strip_tags($line_item['title']), 0, 255),
      'unit_amount' => array(
        'currency_code' => $order->currency,
        'value' => number_format($line_item['amount'], 2, '.', ''),
      ),
      'quantity' => 1, // Generic line items do not contain a qty property.
    );
    $item_total += $line_item['amount'];
    $items[] = $item;
  }

  // Add item_total to the breakdown.
  $breakdown['item_total'] = array(
    'currency_code' => $order->currency,
    'value' => number_format($item_total, 2, '.', ''),
  );

  // Add special line items to the breakdown. For contrib modules that add other
  // line_item types, use hook_uc_paypal_checkout_create_order_request_alter().
  $line_item_totals = array(
    'shipping' => 0,
    'tax_total' => 0,
    'discount' => 0,
    'handling' => 0,
  );
  foreach ($order->line_items as $line_item) {
    switch ($line_item['type']) {
      case 'shipping':
        $line_item_totals['shipping'] += $line_item['amount'];
        break;
      case 'tax':
        $line_item_totals['tax_total'] += $line_item['amount'];
        break;
      case 'discount':
      case 'coupon':
        $line_item_totals['discount'] += abs($line_item['amount']);
        break;
      case 'fee':
        // Even though uc_fee is not yet ported, we preemtively add it to the
        // breakdown.
        $line_item_totals['handling'] += abs($line_item['amount']);
        break;
    }
  }

  foreach ($line_item_totals as $key => $total) {
    if ($total) {
      $breakdown[$key] = array(
        'currency_code' => $order->currency,
        'value' => number_format($total, 2, '.', ''),
      );
    }
  }

  // Add payer information including billing address.
  $payer = array();
  if (!empty($order->primary_mail)) {
    $payer['email_address'] = $order->primary_mail;
  }
  $payer += uc_paypal_checkout_format_address($order, 'billing');

  // Build the request body with all the info.
	$request_body = array(
		'intent' => strtoupper($settings['intent']),
		'purchase_units' => array(
			array(
				'reference_id' => 'default',
				'custom_id' => $order->order_id,
        'invoice_id' => $order->order_id . '-' . time(),
				'amount' => array(
					'currency_code' => $order->currency,
					'value' => number_format($order->order_total, 2, '.', ''),
					'breakdown' => $breakdown,
				),
				'items' => $items,
			),
		),
		'application_context' => array(
			'brand_name' => mb_substr(config_get('system.core', 'site_name'), 0, 127),
		),
	);

  // Send the payer if not empty.
  if ($payer) {
    $request_body['payer'] = $payer;
  }

  // Send shipping information.
  $shipping_exists = module_exists('uc_shipping');
  $shipping_address = FALSE;
  // If the shipping module is enabled...
  if ($shipping_exists) {
    // If we have a shipping address, pass it to PayPal.
    $shipping_address = uc_paypal_checkout_format_address($order, 'delivery');
  }
  $shipping_preference = $settings['shipping_preference'];

  // The shipping module isn't enabled, override the shipping preference
  // configured.
  if (!$shipping_exists) {
    $shipping_preference = 'no_shipping';
  }
  else {
    // If no shipping address was already collected, override the shipping
    // preference to "GET_FROM_FILE" so that the shipping address is collected
    // on the PayPal site.
    if ($shipping_preference == 'set_provided_address' && !$shipping_address) {
      $shipping_preference = 'get_from_file';
    }
  }
  // No need to pass a shipping_address if the shipping address collection
  // is configured to "no_shipping".
  if ($shipping_address && $shipping_preference !== 'no_shipping') {
    $request_body['purchase_units'][0]['shipping'] = $shipping_address;
  }
  $request_body['application_context']['shipping_preference'] = strtoupper($shipping_preference);

	return $request_body;
}

/**
 * Callback for PayPal Checkout payment method.
 * 
 * We only need the admin form for the PayPal Checkout here, since the rest of
 * the logic is handled by other custom callbacks provided by the SDK.
 */
function uc_paypal_checkout_payment_callback($op, &$order, $form = NULL, &$form_state = NULL) {
  if ($op =='settings') {
    $shipping_module_enabled = module_exists('uc_shipping');
    $config = config('uc_paypal_checkout.settings');
    $form['#config'] = 'uc_paypal_checkout.settings';
    $form['client_id'] = array(
      '#type' => 'textfield',
      '#title' => t('PayPal Client ID'),
      '#default_value' => $config->get('client_id'),
      '#required' => TRUE,
      '#maxlength' => 255,
    );
    $form['secret'] = array(
      '#type' => 'textfield',
      '#title' => t('PayPal Secret'),
      '#default_value' => $config->get('secret'),
      '#required' => TRUE,
      '#maxlength' => 255,
    );
    $form['server'] = array(
      '#type' => 'radios',
      '#title' => t('PayPal server'),
      '#options' => array(
        'sandbox' => t('Sandbox'),
        'live' => t('Live'),
        ),
      '#default_value' => $config->get('server'),
    );
    $form['intent'] = array(
      '#type' => 'radios',
      '#title' => t('Transaction type'),
      '#options' => array(
        'capture' => t('Capture'),
        'authorize' => t('Authorize'),
      ),
      '#default_value' => $config->get('intent'),
    );
    $form['disable_funding'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Disable funding sources'),
      '#options' => array(
        'card' => t('Credit or Debit Cards'),
        'credit' => t('PayPal Credit'),
        'sepa' => t('SEPA-Lastschrift'),
      ),
      '#default_value' => $config->get('disable_funding'),
      '#element_validate' => array('uc_paypal_checkout_disable_funding_validate'),
    );
    $form['disable_card'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Disable card types'),
      '#options' => array(
        'visa' => t('Visa'),
        'mastercard' => t('Mastercard'),
        'amex' => t('American Express'),
        'discover' => t('Discover'),
        'dinersclub' => t('Diners Club'),
        'unionpay' => t('UnionPay'),
        'jcb' => t('JCB'),
        'elo' => t('Elo'),
        'hiper' => t('Hiper'),
      ),
      '#default_value' => $config->get('disable_card'),
      '#element_validate' => array('uc_paypal_checkout_disable_card_validate'),
    );
    $form['shipping_preference'] = array(
      '#type' => 'radios',
      '#title' => t('Shipping address collection'),
      '#description' => t('PayPal Checkout will only request a shipping address if the Shipping module is enabled to store the address in the order.'),
      '#options' => array(
        'no_shipping' => t('Do not ask for a shipping address at PayPal.'),
      ),
      '#default_value' => 'no_shipping',
    );
    if ($shipping_module_enabled) {
      $form['shipping_preference']['#options'] += array(
        'get_from_file' => t('Ask for a shipping address at PayPal even if the order already has one.'),
        'set_provided_address' => t('Ask for a shipping address at PayPal if the order does not have one yet.'),
      );
      $form['shipping_preference']['#default_value'] = $config->get('shipping_preference');
    }
    $form['update_billing_profiles'] = array(
      '#type' => 'checkbox',
      '#title' => t('Update billing customer profiles with address information the customer enters at PayPal.'),
      '#default_value' => $config->get('update_billing_profiles'),
    );
    if ($shipping_module_enabled) {
      $form['update_shipping_profiles'] = array(
        '#type' => 'checkbox',
        '#title' => t('Update shipping customer profiles with address information the customer enters at PayPal.'),
        '#default_value' => $config->get('update_shipping_profiles'),
      );
    }
    $form['customize_buttons'] = array(
      '#type' => 'checkbox',
      '#title' => t('Customize PayPal button'),
      '#default_value' => !empty($config->get('style')),
      '#element_validate' => array('uc_paypal_checkout_customize_buttons_validate'),
    );
    $form['style'] = array(
      '#type' => 'fieldset',
      '#title' => t('Button Style'),
      '#description' => t('Customize the PayPal button appearance.'),
      '#tree' => TRUE,
      '#states' => array(
        'visible' => array(
          ':input[name="customize_buttons"]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['style']['layout'] = array(
      '#type' => 'select',
      '#title' => t('Layout'),
      '#options' => array('vertical' => t('Vertical'), 'horizontal' => t('Horizontal')),
      '#default_value' => $config->get('style.layout'),
    );
    $form['style']['color'] = array(
      '#type' => 'select',
      '#title' => t('Color'),
      '#options' => array('gold' => t('Gold'), 'blue' => t('Blue'), 'silver' => t('Silver')),
      '#default_value' => $config->get('style.color'),
    );
    $form['style']['shape'] = array(
      '#type' => 'select',
      '#title' => t('Shape'),
      '#options' => array('rect' => t('Rect'), 'pill' => t('Pill')),
      '#default_value' => $config->get('style.shape'),
    );
    $form['style']['label'] = array(
      '#type' => 'select',
      '#title' => t('Label'),
      '#options' => array('paypal' => t('PayPal'), 'checkout' => t('Checkout'), 'pay' => t('Pay')),
      '#default_value' => $config->get('style.label'),
    );
    $form['style']['tagline'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display tagline'),
      '#default_value' => $config->get('style.tagline'),
      '#states' => array(
        'visible' => array(
          ':input[name="style[layout]"]' => array('value' => 'horizontal'),
        ),
      ),
    );
    return $form;
  }
}

/**
 * Returns HTML for the Smart payment buttons.
 *
 * @param $variables
 *   An associative array containing:
 *   - payment_method: The payment method instance.
 *   - commit: A boolean indicating whether to commit the transaction.
 *   - order: The order.
 *   - flow: The flow ("shortcut"|"mark").
 *
 * @ingroup themeable
 */
function theme_uc_paypal_checkout_smart_payment_buttons($variables) {
  $settings = config_get('uc_paypal_checkout.settings');
  if (empty($settings['client_id']) || empty($variables['order']) || empty($variables['flow'])) {
    return;
  }
  $order = $variables['order'];
  $currency = $order->currency;
  $flow = $variables['flow'];
  $options = array(
    'external' => TRUE,
    'query' => array(
      'client-id' => $settings['client_id'],
      'commit' => $variables['commit'] ? 'true' : 'false',
      'intent' => $settings['intent'],
      'currency' => $currency,
    ),
  );
  if (!empty($settings['disable_funding'])) {
    $options['query']['disable-funding'] = implode(',', $settings['disable_funding']);
  }
  if (!empty($settings['disable_card'])) {
    $options['query']['disable-card'] = implode(',', $settings['disable_card']);
  }
  $path = backdrop_get_path('module', 'uc_paypal_checkout');
  $js_settings = array(
    'ucPaypalCheckout' => array(
      'src' => url('https://www.paypal.com/sdk/js', $options),
      'createOrderUri' => url("uc_paypal_checkout/create-order/$order->order_id"),
      'onApproveUri' => url("uc_paypal_checkout/approve-order/$order->order_id/$flow"),
      'style' => $settings['style'],
    ),
  );
  backdrop_add_css($path . '/css/uc_paypal_checkout.css');
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($path . '/js/uc_paypal_checkout.js');
  $id = backdrop_html_id('paypal-buttons-container');
  return '<div id="' . $id . '" class="paypal-buttons-container"></div>';
}


/**
 * Creates or updates customer information in the order based on information
 * obtained from PayPal after a payment via PayPal Checkout.
 *
 * @param UcOrder $order
 *   The order that was paid via PayPal Checkout.
 * @param string $profile_type
 *   The profile type. Either 'billing' or 'delivery'.
 * @param array $paypal_order
 *   The PayPal order retrieved via the getOrder() API call.
 * @param bool $skip_save
 *   Boolean indicating whether or not this function should skip saving the
 *   order; defaults to TRUE, requiring the caller to save the order.
 */
function uc_paypal_checkout_customer_profile($order, $profile_type, $paypal_order, $skip_save = TRUE) {
  $paypal_address = array();
  $name = array();
  // Use the first name and last name if the profile is a billing profile.
  if ($profile_type == 'billing') {
    $name['first_name'] = $paypal_order['payer']['name']['given_name'];
    $name['last_name'] = $paypal_order['payer']['name']['surname'];
    if (isset($paypal_order['payer']['address'])) {
      $paypal_address = $paypal_order['payer']['address'];
    }
  }
  // Otherwise if it's a delivery profile, populate the address with all of
  // the shipping information returned from PayPal.
  elseif ($profile_type == 'delivery') {
    // If no shipping info was returned by PayPal.
    if (empty($paypal_order['purchase_units'][0]['shipping'])) {
      return;
    }
    $shipping_info = $paypal_order['purchase_units'][0]['shipping'];
    $names = explode(' ', $shipping_info['name']['full_name']);
    $name['first_name'] = array_shift($names);
    $name['last_name'] = implode(' ', $names);
    if (isset($shipping_info['address'])) {
      $paypal_address = $shipping_info['address'];
    }
  }

  foreach (array('first_name', 'last_name') as $name_field) {
    $order_field = $profile_type . '_' . $name_field;
    $order->$order_field = $name[$name_field];
  }
  
  if ($paypal_address) {
    // Map PayPal address keys to order field keys.
    $mapping = array(
      'address_line_1' => 'street1',
      'address_line_2' => 'street2',
      'admin_area_1' => 'city',
      'admin_area_2' => 'zone',
      'postal_code' => 'postal_code',
      'country_code' => 'country',
    );
    foreach ($paypal_address as $key => $value) {
      if (!isset($mapping[$key])) {
        continue;
      }
      // PayPal address fields have a higher maximum length than ours.
      $value = $key == 'country_code' ? $value : mb_substr($value, 0, 255);

      // Country and state/zone are returned as 2-letter codes. Convert them to
      // numeric codes used by Ubercart.
      if ($key == 'country_code') {
        $country_data = uc_get_country_data(array('country_iso_code_2' => $value));
        $value = $country_data[0]['country_id'];
      }
      elseif ($key == 'admin_area_2') {
        $country_data = uc_get_country_data(array('country_iso_code_2' => $value));
        $country_id = $country_data[0]['country_id'];
        $value = db_query("SELECT zone_id FROM {uc_zones} 
          WHERE zone_code = :code
          AND zone_country_id = :country", 
          array(':code' => $value, ':country' => $country_id))
          ->fetchField();
      }
      $order_field = $profile_type . '_' . $mapping[$key];
      $order->$order_field = $value;
    }
  }

  // Save the order if specified.
  if (!$skip_save) {
    uc_order_save($order);
  }
}

/**
 * Formats the given address into a format expected by PayPal.
 *
 * @param UcOrder $order
 *   The address to format.
 * @param string $profile_type
 *   The profile type ("billing"|"shipping").
 *
 * @return array
 *   The formatted address.
 */
function uc_paypal_checkout_format_address($order, $profile_type) {
  $return = array();
  if (!empty($order->{$profile_type . '_postal_code'})) {

    // Convert the state/zone code to two-letter code.
    $zone_id = $order->{$profile_type . '_zone'};
    $paypal_state_code = uc_get_zone_code($zone_id);
    // Convert country numeric code to two-letter code.
    $country_id = $order->{$profile_type . '_country'};
    $country_data = uc_get_country_data(array('country_id' => $country_id));
    $paypal_country_code = $country_data[0]['country_iso_code_2'];

    $return = array(
      'address' => array_filter(array(
        'address_line_1' => $order->{$profile_type . '_street1'},
        'address_line_2' => $order->{$profile_type . '_street2'},
        'admin_area_2' => mb_substr($order->{$profile_type . '_city'}, 0, 120),
        'admin_area_1' => $paypal_state_code,
        'postal_code' => mb_substr($order->{$profile_type . '_postal_code'}, 0, 60),
        'country_code' => $paypal_country_code,
      )),
    );
  }
  if ($profile_type == 'billing') {
    $return['name'] = array(
      'given_name' => $order->{$profile_type . '_first_name'},
      'surname' => $order->{$profile_type . '_last_name'},
    );
  }
  elseif ($profile_type == 'shipping') {
    $return['name'] = array(
      'full_name' => $order->{$profile_type . '_first_name'} . ' ' . $order->{$profile_type . '_last_name'},
    );
  }
  return $return;
}

function uc_paypal_checkout_form_uc_payment_by_order_form_alter(&$form, &$form_state) {
  $order_id = $form['order_id']['#value'];
  $payments = uc_payment_load_payments($order_id);
  if ($payments !== FALSE) {
    foreach ($payments as $payment) {
      $links = [];
      $link_keys = element_children($form['payments'][$payment->receipt_id]['action']);
      if (!empty($link_keys)) {
        // Add needed new actions.
        if ($payment->method == 'PayPal Checkout') {
          // Set the existing action links.
          foreach ($link_keys as $link_key) {
            $links[$link_key] = array(
              'title' => $form['payments'][$payment->receipt_id]['action'][$link_key]['#title'],
              'href' => $form['payments'][$payment->receipt_id]['action'][$link_key]['#href'],
            );
            unset($form['payments'][$payment->receipt_id]['action'][$link_key]);
          }
          $data = unserialize($payment->data);
          if (isset($data['uc_paypal_checkout']['remote_status']) && in_array(strtolower($data['uc_paypal_checkout']['remote_status']), ['created', 'pending'])) {
            $links['capture'] = array(
              'title' => t('Capture'),
              'href' => "admin/store/orders/$order_id/payments/$payment->receipt_id/paypal-checkout-capture",
            );
            $links['void'] = array(
            'title' => t('Void'),
            'href' => "admin/store/orders/$order_id/payments/$payment->receipt_id/paypal-checkout-void",
          );
          }
          elseif (isset($data['uc_paypal_checkout']['remote_status']) && strtolower($data['uc_paypal_checkout']['remote_status']) == 'completed') {
            $links['refund'] = array(
              'title' => t('Refund'),
              'href' => "admin/store/orders/$order_id/payments/$payment->receipt_id/paypal-checkout-refund",
            );
          }
          $form['payments'][$payment->receipt_id]['action'] = array(
            '#type' => 'dropbutton',
            '#links' => $links,
          );
        }
      }
    }
  }
}
